### ISSUE TITLE
Bug: SyntaxError when generating tests

### ISSUE THREAD

**Issue by NikkTod** [vitalets/playwright-bdd#100]
Environment:

platform: Linux
node: v18.14.0
playwright-bdd: v5.8.0
@playwright/test: v1.42.1
ts-node: v10.9.1
typescript: v5.1.6

Hi @vitalets, would you be able to help me by checking the following error that I am getting within a remote Linux machine when running command npx bddgen.
Sorry due to company restrictions I am just able to paste it like picture. Locally on my windows machine with the same nodejs version I am not getting that error. Any thoughts by looking at the screenshot of what could cause this?

![image](https://github.com/vitalets/playwright-bdd/assets/94455079/65018b25-77a2-48aa-bcdf-007289fa9501)

**Comment by NikkTod** [comment]
Ah I think I found the reason, will check now, but it is probably because of that line in my config file 

![image](https://github.com/vitalets/playwright-bdd/assets/94455079/63a4e7e3-357d-40a6-92a7-0d5c8623da92)

I need to first create the env file as the parsing fails.

**Comment by vitalets** [comment]
No problem, you are welcome!
