### ISSUE TITLE
Steps are not being found (probably something simple I have missed) 

### ISSUE THREAD

**Issue by RichardCariven** [vitalets/playwright-bdd#101]
I have started a new Playwright BDD project following a cucumber playwright course but trying to replace al the cucumber runner functionality(world, before after hooks etc) with Playwright-BDD. On creating my initial tests I am getting an undefined step error. I have checked all the normal things, spelling etc, and my IDE is linking to the step from the feature file. I have also compared it against another Playwright-BDD framework I ahve written that does work and can't see what the issue might be. 

  ```
Error: Undefined step: "I am on the home page"

       5 |
       6 |   test("As a user I expect to be able to see contacts", async ({ Given, page, Then }) => {
    >  7 |     await Given("I am on the home page", null, { page });
         |           ^
       8 |     await Then("the contacts header should contain the text Contacts", null, { page });
       9 |   });

```

Feature in e2e/src/features/home-page.feature
```
Feature: As a user I expect to be able to navigate to the home page

  Scenario: As a user I expect to be able to see contacts
    Given I am on the home page
    Then the contacts header should contain the text Contacts
```

Navigation Step located at /e2e/src/step-definitions/navigation.ts
```
import { createBdd } from 'playwright-bdd';
import { test } from "../step-definitions/hooks/hooks"

const { Given } = createBdd(test);

Given('I am on the home page', async () => {
    console.log("I am on the homepage");

    await global.page.goto("http://localhost:3000/")
})
```

Assertion Step located at e2e/src/step-definitions/assertions/verify-element-visibility.ts

```
import { createBdd } from 'playwright-bdd';
import { test } from "../hooks/hooks"
import { expect } from '@playwright/test'

const { Then } = createBdd(test);


Then('the contacts header should contain the text Contacts', async() => {

        console.log("the contacts header should contain the text Contacts")

        const content = await global.page.textContent("[data-id='contacts']")

        expect(content).toBe('Contacts')
})

```
 relevant sections of playwright config
 Note the regex for features and steps is because the course builds up more over time

```
import { defineConfig, devices } from '@playwright/test';
import { defineBddConfig } from 'playwright-bdd';
const testDir = defineBddConfig({
  paths: ['e2e/src/features/**/*.features'],
  require: ['e2e/src/step-definitions/**/**/*.ts'],
  importTestFrom: 'src/step-definitions/hooks/hooks.ts',
});


export default defineConfig({
  testDir,
```

I have also  created a hooks file trying to replace the before all/after all hooks that the course uses but I doubt this is the issue as I am not even getting to the point of running this. 

```
import { test as base } from "playwright-bdd";
import {chromium} from "@playwright/test";

export const test = base.extend({
    beforeAfterAll: async({}, use) => {
        global.browser = await chromium.launch({
            headless:false,
            })
        global.context = await global.browser.newContext();
        global.page = await global.context.newPage()

        await use({})
        await global.page.close()
        await global.browser.close()
    }
})
```

Is there anything obvious leaping out here that I am doing wrong?

**Comment by RichardCariven** [comment]
please delete was a very simple fix all my paths where wrong in the config

**Comment by RichardCariven** [comment]
Please delete my paths where wrong, really simple fix

**Comment by vitalets** [comment]
No problem! Feel free to report any issues.
Btw, you can also pull [playwright-bdd-example](https://github.com/vitalets/playwright-bdd-example) repo and run it locally to check some stuff.
