### ISSUE TITLE
Question around best practice for Fixtures and BDD World. 

### ISSUE THREAD

**Issue by RichardCariven** [vitalets/playwright-bdd#105]
So the Framework I am trying to recreate in playwright BDD uses Cucumber world to pass the page identifiers and element identifiers around.

Is it your intention with this playwright BDD framework to have Fixtures replace World? In what instances would you see World being used instead of Fixtures? 

The framework itself does not follow the POM, in fact it is a framework I have never seen implemented anywhere else. The steps are completely agnostic of page, an example below 

Steps are generic with the Element identifier included in the step 
   ```
    Given I am on the "home" page
    And I click the "create" button
    When I am directed to the "create contact" page
    And I fill in the "name" input with "Lisa Simpson"
    Then I select the "Female" option from the "gender"
    And I fill in the "phone" input with "939-555-0113"
    And I fill in the "street" input with "742 Evergreen Terrace"
    And I fill in the "city" input with "Springfield"
    And I click the "save" button
    And I am directed to the "home" page
```

```
When(
    /^I click the "([^"]*)" (?:button|link)$/,
    async function (this: ScenarioWorld, elementKey: ElementKey) {
        const {
            screen: { page },
            globalConfig,
        } = this

        logger.log(`I click the ${elementKey} (?:button|link|icon|element|radio button)`)

        const elementIdentifier = getElementLocator(page, elementKey, globalConfig)

        await waitFor(async () => {
                const elementStable = await waitForSelector(page, elementIdentifier)

                if (elementStable) {
                    await clickElement(page, elementIdentifier)
                    return waitForResult.PASS
                }

                return waitForResult.ELEMENT_NOT_AVAILABLE
            },
            globalConfig,
            {target: elementKey})
    }
)


```
The CucumberWorld function, I am ignoring all the browser functionality because I can move all of that into the Playwright config directly, 
```
import playwright, {
    BrowserContextOptions,
    Page,
    Browser,
    BrowserContext,
    BrowserType
} from "playwright";
import { env } from '../../env/parseEnv'
import { World, IWorldOptions, setWorldConstructor} from "@cucumber/cucumber";
import { GlobalConfig, GlobalVariables } from '../../env/global';

export type Screen = {
    browser: Browser;
    context: BrowserContext;
    page: Page;
}

export class ScenarioWorld extends World {
    constructor(options: IWorldOptions) {
        super(options)

        this.globalConfig = options.parameters as GlobalConfig;
        this.globalVariables = { currentScreen: ""};
    }

    globalConfig: GlobalConfig;

    globalVariables: GlobalVariables;

    screen!: Screen;

    async init(contextOptions?: BrowserContextOptions): Promise<Screen> {
        await this.screen?.page?.close();
        await this.screen?.context?.close()
        await this.screen?.browser?.close()

        const browser = await this.newBrowser();
        const context = await browser.newContext(contextOptions)
        const page = await context.newPage();

        this.screen = { browser, context, page };

        return this.screen
    }

    private newBrowser = async (): Promise<Browser> => {

        const automationBrowsers = ['chromium', 'firefox', 'webkit']
        type AutomationBrowser = typeof automationBrowsers[number]
        const automationBrowser = env('UI_AUTOMATION_BROWSER') as AutomationBrowser

        const browserType: BrowserType = playwright[automationBrowser];
        const browser = await browserType.launch({
            headless: process.env.HEADLESS !== 'false',
            args: ['--disable-web-security', '--disable-features=IsolateOrigins, site-per-process'],
        })
        return browser;
    }

}

setWorldConstructor(ScenarioWorld)
```
happy to share more if you need more context but my question is mainly looking at the above based on how you intend playwrigth-Bdd to be used would it be beter to simply convert this to BDDworld, or turn it into a fixture?

**Comment by RichardCariven** [comment]
Will do that, happy sharing the git repo if people want to watch my efforts to try and get it transposed over. :) I fully agree through that the browser stuff could all come out, just trying to step through it slowly and not break it to much all at once :)

**Comment by RichardCariven** [comment]
have added you to the repo of the the original cucumber project I am trying to rewrite, don't worry to much about the features I will switch them all over to the Playwright style, My main issues right now are refactoring the World and the Index files, and also where the config is passed through the runner how I go about changing that. to be honest not sure where to start, I am right at the limit right now of my Typescript and Playwright knowledge (only been using typescript the past 3 months in this new role) I think if I can overcome that hurdle the rest should all fall out pretty easily.

Just as am overview of how this framework is different to the POM, as you will see the steps are very agnostic and relate to actions or assertions in general, not linked to specific pages. The Element Identifiers are then stored in a mappings directory, and the framework looks to see what page the the test is on, and then looks up the selectors defined for that page, or goes to a common list of selectors that span multiple pages. This allows you to have a framework that does not nee to be page dependant. 

[git@github.com](mailto:git@github.com):RichardCariven/Test-Framework.git

**Comment by RichardCariven** [comment]
I have made a start on refactoring. 

Refactoring the Index TS which sets the world (see below) 

From 

i```
mport dotenv from 'dotenv'
import { env, getJsonFromFile } from './env/parseEnv'
import {
    GlobalConfig,
    HostsConfig,
    PagesConfig,
    PageElementMappings,
} from './env/global';
import fs from "fs";

dotenv.config({path: env('COMMON_CONFIG_FILE')})

const hostsConfig: HostsConfig = getJsonFromFile(env('HOSTS_URLS_PATH'));
const pagesConfig: PagesConfig = getJsonFromFile(env('PAGE_URLS_PATH'));

const mappingFiles = fs.readdirSync(`${process.cwd()}${env('PAGE_ELEMENTS_PATH')}`);

const pageElementMappings: PageElementMappings = mappingFiles.reduce(
    (pageElementConfigAcc, file) => {
        const key = file.replace('.json', '');
        const elementMappings = getJsonFromFile(`${env('PAGE_ELEMENTS_PATH')}${file}`);
        return { ...pageElementConfigAcc, [key]: elementMappings };
    },
    {}
);

const worldParameters: GlobalConfig = {
    hostsConfig,
    pagesConfig,
    pageElementMappings,
};

const common = `./src/features/**/*.feature \
                --require-module ts-node/register \
                --require ./src/step-definitions/**/**/*.ts \
                -f json:./reports/report.json \
                --world-parameters ${JSON.stringify(worldParameters)} \
                --format progress-bar`;

const dev = `${common} --tags '@dev'`;
const smoke = `${common} --tags '@smoke'`;
const regression = `${common} --tags '@regression'`;

export { dev, smoke, regression}
```

To 
```

import dotenv from 'dotenv'
import { env, getJsonFromFile } from '../../env/parseEnv'
import {
    GlobalConfig,
    HostsConfig,
    PagesConfig,
    PageElementMappings,
} from '../../env/global';
import fs from "fs";
import {test as baseTest } from 'playwright-bdd'


type PageMapType = {
    worldParameters: GlobalConfig
    common: string
    dev: string
    smoke: string
    regression: string
}

const pageMapfixture = baseTest.extend<PageMapType>({
    worldParameters: async ({}, use) => {
        dotenv.config({path: env('COMMON_CONFIG_FILE')})
        const hostsConfig: HostsConfig = getJsonFromFile(env('HOSTS_URLS_PATH'));
        const pagesConfig: PagesConfig = getJsonFromFile(env('PAGE_URLS_PATH'));
        const mappingFiles = fs.readdirSync(`${process.cwd()}${env('PAGE_ELEMENTS_PATH')}`);
        const pageElementMappings: PageElementMappings = mappingFiles.reduce(
            (pageElementConfigAcc, file) => {
                const key = file.replace('.json', '');
                const elementMappings = getJsonFromFile(`${env('PAGE_ELEMENTS_PATH')}${file}`);
                return { ...pageElementConfigAcc, [key]: elementMappings };
            },
            {}
        );
        await use({hostsConfig, pagesConfig, pageElementMappings})

    },

})

export const test = pageMapfixture
```

I am struggling though to work out how to refactor the World file I shared above 

I have stripped out all of the Browser Start functionality so I just have 

```
import { World, IWorldOptions, setWorldConstructor} from "@cucumber/cucumber";
import { GlobalConfig, GlobalVariables } from '../../env/global';


export class ScenarioWorld extends World {
    constructor(options: IWorldOptions) {
        super(options)

        this.globalConfig = options.parameters as GlobalConfig;
        this.globalVariables = { currentScreen: ""};
    }

    globalConfig: GlobalConfig;

    globalVariables: GlobalVariables;



}

setWorldConstructor(ScenarioWorld)
```

But I am unsure how to refactor the constructor here and the options.parameters. 

Any suggestions greatly appreciated thank you.

**Comment by vitalets** [comment]
`ScenarioWorld` should extend `BddWorld` instead of Cucumber `World`:

```ts
import { setWorldConstructor } from '@cucumber/cucumber';
import { BddWorld, BddWorldOptions } from 'playwright-bdd';
import { GlobalConfig, GlobalVariables } from '../../env/global';

export class ScenarioWorld extends BddWorld {
    constructor(options: BddWorldOptions) {
        super(options)
        this.globalConfig = options.parameters as GlobalConfig;
        this.globalVariables = { currentScreen: ""};
    }

    globalConfig: GlobalConfig;
    globalVariables: GlobalVariables;
}

setWorldConstructor(ScenarioWorld);
```
Here are more details on BddWorld in [documentation](https://vitalets.github.io/playwright-bdd/#/writing-steps/cucumber-style?id=custom-world).

Then in step definition (see comments in code):
```ts
import { Then } from '@cucumber/cucumber'
import { expect } from '@playwright/test'
import { ElementKey } from '../../env/global';
import { getElementLocator } from '../../support/web-element-helper';
import { waitFor } from '../../support/wait-for-behavior';

import { ScenarioWorld } from './world'; // <-- import ScenarioWorld just for typing

Then<ScenarioWorld>( // <-- add typing for ScenarioWorld to have correct 'this' inside step
    /^the "([^"]*)" should be displayed$/,
    async function(elementKey: ElementKey) {
        const {
            screen: { page },
            globalVariables,
            globalConfig,
        } = this;

        console.log(`the ${elementKey} should be displayed`)

        const elementIdentifier = getElementLocator(page, elementKey, globalVariables, globalConfig);

        await waitFor(async () => {
            const isElementVisible = (await this.page.$(elementIdentifier)) != null; // <-- notice this.page
            return isElementVisible;
        });
    }
)
```

**Comment by RichardCariven** [comment]
HI sorry I was trying to make all of this a fixture as opposed to using BDD world.

**Comment by RichardCariven** [comment]
closing this and opening another specificially around porting Cucumber World to a Fixture
