### ISSUE TITLE
May be a bug, unsure. Cant call init on BddWorld 

### ISSUE THREAD

**Issue by RichardCariven** [vitalets/playwright-bdd#106]
I am converting a Cucumber World file to BddWorld and am getting a type error I cant work out how to correct. 

Below is the file I have converted, however I am getting an error on the init 

```
import playwright, {
    BrowserContextOptions,
    Page,
    Browser,
    BrowserContext,
    BrowserType
} from "playwright";
import { env } from '../../env/parseEnv'
import { setWorldConstructor} from "@cucumber/cucumber";
import { GlobalConfig, GlobalVariables } from '../../env/global';
import {BddWorld, BddWorldOptions} from "playwright-bdd";

export type Screen = {
    browser: Browser;
    context: BrowserContext;
    page: Page;
}

export class ScenarioWorld extends BddWorld {
    constructor(options: BddWorldOptions) {
        super(options)

        this.globalConfig = options.parameters as GlobalConfig;
        this.globalVariables = { currentScreen: ""};
    }

    globalConfig: GlobalConfig;

    globalVariables: GlobalVariables;

    screen!: Screen;

    async init(contextOptions?: BrowserContextOptions): Promise<Screen> {
        await this.screen?.page?.close();
        await this.screen?.context?.close()
        await this.screen?.browser?.close()

        const browser = await this.newBrowser();
        const context = await browser.newContext(contextOptions)
        const page = await context.newPage();

        this.screen = { browser, context, page };

        return this.screen
    }

    private newBrowser = async (): Promise<Browser> => {

        const automationBrowsers = ['chromium', 'firefox', 'webkit']
        type AutomationBrowser = typeof automationBrowsers[number]
        const automationBrowser = env('UI_AUTOMATION_BROWSER') as AutomationBrowser

        const browserType: BrowserType = playwright[automationBrowser];
        const browser = await browserType.launch({
            headless: process.env.HEADLESS !== 'false',
            args: ['--disable-web-security', '--disable-features=IsolateOrigins, site-per-process'],
        })
        return browser;
    }

}

setWorldConstructor(ScenarioWorld)
```
The error 
```
TS2416: Property init in type ScenarioWorld is not assignable to the same property in base type BddWorld<any, TestTypeCommon>
Type
(contextOptions?: BrowserContextOptions | undefined) => Promise<Screen>
is not assignable to type () => Promise<void>
Type Promise<Screen> is not assignable to type Promise<void>
Type Screen is not assignable to type void
```

**Comment by vitalets** [comment]
World.init() is called internally by playwright-bdd without any parameters. 
I guess you call world.init() manually in some before hook. So you can just rename this method (e.g. world.setup()) and it should work. Or another option - remove parameters from init method and take them from the world itself. E.g. 
'''ts
const { browser, context, page } = this;
...
'''
Also I've noticed that you manually create and close browser and page in this init() method - in Playwight runner this is usually not needed, Playwright does this job for us. So maybe you can remove this init() method at all.

**Comment by RichardCariven** [comment]
have added you to the repo of the the original cucumber project I am trying to rewrite, don't worry to much about the features I will switch them all over to the Playwright style, My main issues right now are refactoring the World and the Index files, and also where the config is passed through the runner how I go about changing that. I think if I can overcome that hurdle the rest should all fall out pretty easily. 

git@github.com:RichardCariven/Test-Framework.git

**Comment by RichardCariven** [comment]
closing this as we are carrying on the disccusion about using fixtures in another thread
