### ISSUE TITLE
Question: How do you organize steps in multiple TypeScript files (Playwright-style)?

### ISSUE THREAD

**Issue by runenielsen** [vitalets/playwright-bdd#109]
How do you organize steps in multiple TypeScript files (Playwright-style)?

The examples say to call `const { Given, When, Then } = createBdd(test);` in the top of the step file, but they all seem to only have one step file.

How should this be done, if I want to organize my steps in multiple different step files? I assume it should not be called in all step files, since then it may be called several times in a feature...

Thanks in advance.

**Comment by vitalets** [comment]
Calling `const { Given, When, Then } = createBdd()` at the top of each step file is totally ok, it returns lightweight wrappers without heavy operations.

I've [updated](https://vitalets.github.io/playwright-bdd/#/writing-steps/playwright-style?id=playwright-style-steps) docs on that, thanks for raising this!

**Comment by runenielsen** [comment]
Thanks a lot!
