### ISSUE TITLE
Feature: Add keyword in feature file

### ISSUE THREAD

**Issue by lrami** [vitalets/playwright-bdd#111]
Hi @vitalets thanks for your work on playwright-bdd, your library is famous. 
I would like to pitch you an idea for a new feature for playwright-bdd.

In Cumcumber style tests we can use the And keyword instead of repeating the previous keyword. 

For example:

When the user fills out his username
And the user fills out his password
And the user clicks on the send button
Then the user is logged in

Do you think it would be possible to implement this feature ?

Thanks in advance

**Comment by vitalets** [comment]
Hi @lrami ! That is really useful and already implemented :) 
You can use `And` in feature file with any of steps defined with `Given() / When() / Then()`.
Feel free to re-open this issue if in your project it does not work for some reasons.
