### ISSUE TITLE
Feature: support defineParameterType for decorator playwright mode?

### ISSUE THREAD

**Issue by swayf** [vitalets/playwright-bdd#112]
May be I doing something wrong, but I become always: 
```
You're calling functions (e.g. "defineParameterType") on an instance of Cucumber that isn't running.
          This means you have an invalid installation, mostly likely due to:
          - Cucumber being installed globally
          - A project structure where your support code is depending on a different instance of Cucumber
          Either way, you'll need to address this in order for Cucumber to work.
          See https://github.com/cucumber/cucumber-js/blob/main/docs/installation.md#invalid-installations
```
Is there any right place for defineParameterType definitions? :)
PS: Thank you for such amazing library :+1:

**Comment by vitalets** [comment]
Currently it is not possible, but this is a good feature request.
Added [note](https://vitalets.github.io/playwright-bdd/#/writing-steps/decorators?id=limitations) in the docs and converted the issue into enhancement. Thanks!

**Comment by vitalets** [comment]
Released in **v7 RC**. 
I would appreciate if you try and share the feedback. [Migration guide](https://vitalets.github.io/playwright-bdd/#/guides/migration-v7).

**Comment by vitalets** [comment]
Landed in v7 🎉
Feel free to create new issue in case of any problems.
