### ISSUE TITLE
How to debug the bdd tests?

### ISSUE THREAD

**Issue by kashiMathura** [vitalets/playwright-bdd#114]
Could you please share how do we debug the playwright-bdd tests?

**Comment by vitalets** [comment]
Playwright-bdd outputs regular Playwright test files, so you can use any of [Playwright debugging methods](https://playwright.dev/docs/debug) for BDD tests.

Personally, I prefer running tests with `--debug` flag:
```
npx bddgen && npx playwright test --debug
```
![image](https://github.com/vitalets/playwright-bdd/assets/1473072/7a1c2651-1c8d-417c-a0cf-547a58c24c1c)

Added this answer to [docs for debugging](https://vitalets.github.io/playwright-bdd/#/guides/debugging?id=debugging).
If something does not work, feel free to report!
