### ISSUE TITLE
Bug: Getting testInfo._runAsStep is not a function after updating to Canary playwright

### ISSUE THREAD

**Issue by NikkTod** [vitalets/playwright-bdd#119]
I am using the Decorators syntax and wanted to try a new feature in playwright, so I updated to 1.43.0-alpha-2024-03-26

With this playwright version if I try to run a test I get an error:

![image](https://github.com/vitalets/playwright-bdd/assets/94455079/3d19c079-451d-40d7-8a2e-6fb7aecd611e)

![image](https://github.com/vitalets/playwright-bdd/assets/94455079/5e9bb427-9678-4de9-9ff7-ad59de0acd33)

**Environment**
node: v18.14.0
playwright-bdd: v6.0.1
playwright: 1.43.0-alpha-2024-03-26
cucumber: v10.3.1

**Comment by vitalets** [comment]
Thanks for reporting, will investigate.
Also I will add Playwright canary to test suite to detect such issues earlier.

**Comment by vitalets** [comment]
There are two pending issues with upcoming Playwright 1.43. Addressed them in the Playwright repo:
  * https://github.com/microsoft/playwright/issues/30175
  * https://github.com/microsoft/playwright/issues/30179

**Comment by jonyo** [comment]
It seems Playwright 1.43.0 shipped with the issues intact, is there a workaround for this? We don't use decorators but do use tags and are getting that error.

Is the workaround to pin to the [1.42.1](https://github.com/microsoft/playwright/releases/tag/v1.42.1) for now?

**Comment by vitalets** [comment]
@jonyo please check on just released `playwright-bdd@6.1.0`, it should work.
Feel free to re-open if there are any issues.
