### ISSUE TITLE
v2.0.0 - Only generates for 1st item in Examples table

### ISSUE THREAD

**Issue by jlattimer** [vitalets/playwright-bdd#12]
Examples:
| name | value |
| foo1  | bar1   |
| foo2  | bar2   |

Will ony generate code for "foo1" .

This is new in v2.0.0 - it was working as expected in v1.3.0

**Comment by jlattimer** [comment]
I figured out that if I define the scenario  with "Secenario: ..." it will only generate the first example. If I use "Scenario Outline: ..." then it will generate more than the first example.

It appears that using "Scenario Outline" when using an examples table is the proper way to define this. So everything is working as it should in the current version and it probably shouldn't have worked in the previous version. Thanks!

**Comment by vitalets** [comment]
You are welcome :)
