### ISSUE TITLE
Question: Do we allow run specific tag?

### ISSUE THREAD

**Issue by zmimi-lael** [vitalets/playwright-bdd#121]
Hi,

I tried to clone the playwright-bdd-example and add some tags on the sample feature. Then using command `npx playwright test -g "@fast"` it gives me `Error: No tests found`

![image](https://github.com/vitalets/playwright-bdd/assets/148584709/5d7d1662-2158-4609-9fcd-3c6350041e8c)

**Comment by vitalets** [comment]
Hi @zmimi-lael 
In the current playwright-bdd version (6.0.3) you can run specific tags with the following syntax:
```
npx bddgen --tags "@fast" && npx playwright test
```
See details [here](https://vitalets.github.io/playwright-bdd/#/writing-features/index?id=tags).

In the nearest release there is an upcoming support for the new syntax of Playwright tags #98.
After that we will be able to run either:
```
npx bddgen --tags "@fast" && npx playwright test
# or 
npx bddgen && npx playwright test -g "@fast"
```
