### ISSUE TITLE
Feature: add @fail into the default tags to allow test.fail() functionality to be easily applied. 

### ISSUE THREAD

**Issue by RichardCariven** [vitalets/playwright-bdd#123]
**The problem**
Playwright allows the ability to mark tests as failing, this means they will run but not fail the test unless they actually pass. This can be useful as a way of marking a feature with known bugs as knowingly failing rather then just marking it to be skipped, or using fixme, which may be incorrect as the feature might be right but a low priority bug is present that needs to be fixed. 

**A solution**
add in '@ fail' as a default cucumber tag allowing this to run alongside the '@ skip' and the '@ fixme' tags.

**Comment by vitalets** [comment]
Released in **v6.1.0**.
See [special tags](https://vitalets.github.io/playwright-bdd/#/writing-features/special-tags?id=fail) in docs.
Thanks for the suggestion! Feel free to re-open if there are any issues.
