### ISSUE TITLE
Question:Refactoring Cucumber Framework to Playwright BDD. Passing values between steps without Cucumber World. 

### ISSUE THREAD

**Issue by RichardCariven** [vitalets/playwright-bdd#127]
Thanks to your help I have refactored the World function into a fixture. However this has now caused a problem. 

In the original framework World was being used to pass a value from step to step. 

```
import { Given } from '@cucumber/cucumber'
import {
    navigateToPage,
} from '../support/navigation-behavior';
import { PageId } from '../env/global';

Given(
    /^I am on the "([^"]*)" page$/,
    async function(pageId: PageId) {
        const {
            screen: { page },
            globalVariables,
            globalConfig,
        } = this;

        console.log(`I am on the ${pageId} page`);

        globalVariables.currentScreen = pageId;

        await navigateToPage(page, pageId, globalConfig);

    }
)
```
globalVariables would then store the pageId allowing it to be used to find the page locators on that page via a mappings json. 

```
import { Then } from '@cucumber/cucumber'
import { expect } from '@playwright/test'
import { ElementKey } from '../../env/global';
import { getElementLocator } from '../../support/web-element-helper';
import { waitFor } from '../../support/wait-for-behavior';

Then(
    /^the "([^"]*)" should be displayed$/,
    async function(elementKey: ElementKey) {
        const {
            screen: { page },
            globalVariables,
            globalConfig,
        } = this;

        console.log(`the ${elementKey} should be displayed`)
        console.log(globalVariables)
        const elementIdentifier = getElementLocator(page, elementKey, globalVariables, globalConfig);
        console.log(elementIdentifier)

        await waitFor(async () => {
            const isElementVisible = (await page.$(elementIdentifier)) != null;
            return isElementVisible;
        });
    }
)
```

Get Element Locator links the mappings 

```
import { Page } from 'playwright';
import {ElementKey, ElementLocator, GlobalConfig, GlobalVariables} from '../env/global';

export const getElementLocator = (
    page: Page,
    elementKey: ElementKey,
    globalVariables: GlobalVariables,
    globalConfig: GlobalConfig,
): ElementLocator => {

    const { pageElementMappings } = globalConfig;

    const currentPage = globalVariables.currentScreen;

    return pageElementMappings[currentPage]?.[elementKey] || pageElementMappings.common?.[elementKey];
};


```
the first step has now become

```
import { createBdd } from 'playwright-bdd';
import { test } from "./setup/fixtures"
import {
    navigateToPage,
} from '../support/navigation-behavior';
const { Given } = createBdd(test);

Given('I am on the {string} page', async ({page, globalVariables, worldParameters}, pageId: string) => {

    console.log(`I am on the ${pageId} page`);
    globalVariables.currentScreen = pageId;

    await navigateToPage(page, pageId, worldParameters);
})
```

By removing the Cucumber World functionality I am no longer persisting my pageId in the globalVariables. Is there a way to do something similar using Playwright, or do I need to revert back to using the cucumber world for this use case?

**Comment by vitalets** [comment]
Your step code should persist pageId:
```ts
Given('I am on the {string} page', async ({page, globalVariables, worldParameters}, pageId: string) => {
    console.log(`I am on the ${pageId} page`);
    globalVariables.currentScreen = pageId;
    await navigateToPage(page, pageId, worldParameters);
});

When('Some action on the current page', async ({ globalVariables }) => {
    const pageId = globalVariables.currentScreen;
    console.log(`Some action on the ${pageId} page`);
});
```
if it does not, could you show how do you consume pageId on the subsequent steps?

**Comment by RichardCariven** [comment]
So in the new framework 

Same feature 

```
import { createBdd } from 'playwright-bdd';
import { test } from "./setup/fixtures"
import {
    navigateToPage,
} from '../support/navigation-behavior';
const { Given } = createBdd(test);

Given('I am on the {string} page', async ({page, globalVariables, worldParameters}, pageId: string) => {

    console.log(`I am on the ${pageId} page`);
    globalVariables.currentScreen = pageId;

    await navigateToPage(page, pageId, worldParameters);
})
```

i```
mport { ElementKey } from '../../env/global';
import {getElementLocator} from "../../support/web-element-helper";
import { waitFor } from '../../support/wait-for-behavior';
import { createBdd } from 'playwright-bdd';
import { test } from "../setup/fixtures"
const { Then } = createBdd(test);
Then(
    "the {string} should contain the text {string}",
    async ({page, worldParameters, globalVariables }, elementKey: ElementKey, expectedElementText: string) => {
        const currentScreen = globalVariables.currentScreen

        const elementIdentifier = getElementLocator(page, elementKey, currentScreen, worldParameters)

        await waitFor(async () => {
            const elementText = await page.textContent(elementIdentifier)
            return elementText?.includes(expectedElementText);
        });

    }
)

Then(
    "the {string} should be displayed",
    async ({page, worldParameters, globalVariables }, elementKey: ElementKey, expectedElementText: string) => {

        console.log(`the ${elementKey} should be displayed`)
        console.log(globalVariables)
        const elementIdentifier = getElementLocator(page, elementKey, globalVariables, worldParameters);
        console.log(elementIdentifier)

        await waitFor(async () => {
            const isElementVisible = (await page.$(elementIdentifier)) != null;
            return isElementVisible;
        });
    }
)
```
get element locator is unchanged 

below is the new index.fixture that combines the index and world.ts from the original framework (given above) 
```
import dotenv from 'dotenv'
import { env, getJsonFromFile } from '../../env/parseEnv'
import {
    GlobalConfig,
    HostsConfig,
    PagesConfig,
    PageElementMappings, GlobalVariables,
} from '../../env/global';
import fs from "fs";
import {test as baseTest } from 'playwright-bdd'

type PageMapType = {
    worldParameters: GlobalConfig
    globalVariables: GlobalVariables
}

const pageMapfixture = baseTest.extend<PageMapType>({
    worldParameters: async ({}, use) => {dotenv.config({path: env('COMMON_CONFIG_FILE')});
        const hostsConfig: HostsConfig = getJsonFromFile(env('HOSTS_URLS_PATH'));
        const pagesConfig: PagesConfig = getJsonFromFile(env('PAGE_URLS_PATH'));
        const mappingFiles = fs.readdirSync(`${process.cwd()}${env('PAGE_ELEMENTS_PATH')}`);
        const pageElementMappings: PageElementMappings = mappingFiles.reduce(
            (pageElementConfigAcc, file) => {
                const key = file.replace('.json', '');
                const elementMappings = getJsonFromFile(`${env('PAGE_ELEMENTS_PATH')}${file}`);
                return { ...pageElementConfigAcc, [key]: elementMappings };
            },
            {}
        );
        await use({hostsConfig, pagesConfig, pageElementMappings})
    },
    globalVariables: async ({}, use) => {
        await use({currentScreen: ""})
    },
});


export const test = pageMapfixture



```

**Comment by RichardCariven** [comment]
if easier can maybe have a quick call at some point tomorrow and I can screen share the full codebase to you?

**Comment by vitalets** [comment]
I've cloned `RichardCariven/react-app-playwright-bdd` and runned it locally:
```
cd e2e && cucumber:dev
```
The output:
```
> npx cross-env-shell COMMON_CONFIG_FILE=env/common.env "npx bddgen --tags @smoke && npx playwright test"


Running 1 test using 1 worker
…expect to be able to navigate to the home page › As a user I expect to be able to see contacts
I am on the home page
the header logo should be displayed
{ currentScreen: 'home' }
[data-id='header-logo']
{ currentScreen: 'home' }
  1 passed (1.3s)
```
Test passed, so it looks like everything works. Could you clarify the exact problem?

**Comment by RichardCariven** [comment]
I have pushed the changes I made to the 2nd step ("the {string} should contain the text {string}") 

if you pull and run this now you should see the error I am seeing

**Comment by vitalets** [comment]
I found the issue: `getElementLocator()` accepts `globalVariables`, not the `currentScreen` itself. I've made the following change and now test pass:
```diff
--- a/e2e/src/step-definitions/assertions/verify-element-value.ts
+++ b/e2e/src/step-definitions/assertions/verify-element-value.ts
@@ -9,7 +9,7 @@ Then(
     async ({page, worldParameters, globalVariables }, elementKey: ElementKey, expectedElementText: string) => {
         const currentScreen = globalVariables.currentScreen
         console.log(currentScreen)
-        const elementIdentifier = getElementLocator(page, elementKey, currentScreen, worldParameters)
+        const elementIdentifier = getElementLocator(page, elementKey, globalVariables, worldParameters)
 
         await waitFor(async () => {
             const elementText = await page.textContent(elementIdentifier)
```

**Comment by magarwal19** [comment]
Hi
I am using this keyword to share data between multiple steps within same scenario

for e.g

Given("I logged in portal with {string} and {string}", async function({page}, username, password){
this.username = username
})

Then("I validate username is displayed on dashboard", async function ({page}){
console.log(this.username)

}_

**Comment by RichardCariven** [comment]
> I found the issue: `getElementLocator()` accepts `globalVariables`, not the `currentScreen` itself. I've made the following change and now test pass:
> 
> ```diff
> --- a/e2e/src/step-definitions/assertions/verify-element-value.ts
> +++ b/e2e/src/step-definitions/assertions/verify-element-value.ts
> @@ -9,7 +9,7 @@ Then(
>      async ({page, worldParameters, globalVariables }, elementKey: ElementKey, expectedElementText: string) => {
>          const currentScreen = globalVariables.currentScreen
>          console.log(currentScreen)
> -        const elementIdentifier = getElementLocator(page, elementKey, currentScreen, worldParameters)
> +        const elementIdentifier = getElementLocator(page, elementKey, globalVariables, worldParameters)
>  
>          await waitFor(async () => {
>              const elementText = await page.textContent(elementIdentifier)
> ```

Thankyou this is now working for me as well, was sure I had tried this approach but obv not :). Think a case of just needing a second pair of eyes. Will carry on with the refactoring work for the course I was doing but it should all run pretty smoothly now this is working. Thank you

**Comment by vitalets** [comment]
You are welcome! Feel free to report in case of any other issues
