### ISSUE TITLE
Question: How to implement browser depedencies.

### ISSUE THREAD

**Issue by despellhtb** [vitalets/playwright-bdd#128]
According to https://playwright.dev/docs/test-global-setup-teardown (Option 1) you can create 'depedencies' for each browser.
For this to work you should set the testDir of playwright.config.ts, but testDir is defined by defineBddConfig in this situation and cannot define another one.

Any other way to make this work ? Global setup does not fit in my situation, I want to use Playwright depedencies ideally.

Thank you.

**Comment by vitalets** [comment]
This should be possible. Could you share the `playwright.config.ts` that does not work?
