### ISSUE TITLE
Question: how to switch a tab in window, if I am using decorators style for writing code

### ISSUE THREAD

**Issue by poonam-effectiv** [vitalets/playwright-bdd#129]
I have started using playwright recently. I am aware on how to switch a page using context option. But how can I do it with playwright-bdd. On the Ui I see the page is open, but the focus is still on the old tab.

I have tried this.page.url(), which shows me the old tab url

**Comment by vitalets** [comment]
Basically, it is the same as in Playwright. You can pass `context` fixture into POM and utilize it for managing tabs. E.g.:
```ts
export const test = base.extend<{ todoPage: TodoPage }>({
  todoPage: ({ page, context }, use) => use(new TodoPage(page, context)),
});

export @Fixture('todoPage') class TodoPage {
  constructor(public page: Page, public context: BrowserContext) { }
  
  @When('I switch to tab {string}')
  async switchToTab(url: string) {
    const page = this.context.pages().find(page => page.url() === url);
    await page?.bringToFront();
  }

  // ...
}
```

**Comment by vitalets** [comment]
Please re-check on your side and re-open in case of any issues.
