### ISSUE TITLE
Question: Trying to organize new folder using the playwright-bdd sample proj

### ISSUE THREAD

**Issue by zmimi-lael** [vitalets/playwright-bdd#131]
When I run the test, new feature is not added in the  `.features-gen`

![image](https://github.com/vitalets/playwright-bdd/assets/148584709/8187eeb2-0854-4ea4-9151-f2ab94adb5a6)

Also,  my steps are written on another folder e.g. steps/customer/customer_steps

What will be the best practice, since  I want to make the structure for each test steps on a page like organization?

**Comment by vitalets** [comment]
Could you share the output of `npx bddgen --verbose`?

About steps - I've noticed that customer_steps are in TypeScript, but in config your target only `.js` steps: `require: ['steps/**/*.js']`. I think targeting both js/ts steps should help: `require: ['steps/**/*.{js,ts}']`

**Comment by zmimi-lael** [comment]
![image](https://github.com/vitalets/playwright-bdd/assets/148584709/0056aa18-7378-47c7-896f-021bfe84af17)

**Comment by vitalets** [comment]
I see the error there: 
```
Error: When using custom "test" function in createBdd() you should set "importTestFrom"...
```
Could you try to set "importTestFrom" in `defineBddConfig()` ?

**Comment by vitalets** [comment]
Closing as inactive. Feel free to re-open if needed.
