### ISSUE TITLE
Feature: CLI option to print version

### ISSUE THREAD

**Issue by jonyo** [vitalets/playwright-bdd#134]
**The problem**

In the CI logs, I can easily print the version of playwright, node, etc. so that we can make sure things are the versions we expect.

Since bddgen is tied into our playwright tests working, it would be nice if we could also easily print out the bddgen version.

**A solution**

Add a CLI option for `--version`, like:
```
npx bddgen --version
```

That would display the library version.

Not sure if this is possible with how libraries work, but if so it would make debugging just a little easier!  🙇

**Comment by jonyo** [comment]
TIL that `npm list <package-name>` is a thing!  Sorry, should have thought to check for options built into npm itself...

That said, since playwright has a way to print the version, it might still be useful. For instance, say we check the locally installed version `npm list playwright-bdd` but then somehow `bddgen` is run from a global installed version or something... Having the ability to run the same `bddgen ...` command but add `--version` to check the version would still be useful for this type of thing IMO.

**Comment by vitalets** [comment]
Released in **v6.2.0**
