### ISSUE TITLE
Bug:$step.title is giving eslint errors 

### ISSUE THREAD

**Issue by RichardCariven** [vitalets/playwright-bdd#137]
**Given**
```
The below step 
Then(
  'the {string} should( not) be displayed',
  async ({page,  $step, globalConfig}, elementKey: ElementKey) => {
    const negate = /should not/.test($step.title);
    const elementIdentifier = getElementLocator(page, elementKey, globalConfig)

        if (negate) {
          await expect(elementIdentifier).not.toBeVisible()
        } else if (negate == false) {
          await expect(elementIdentifier).toBeVisible()
        }
  }
)
```

**When**
I use `const negate = /should not/.test($step.title);`

**Then**
I get the following eslint error in IntelliJ 

`ESLint: Unsafe argument of type `any` assigned to a parameter of type `string`.(@typescript-eslint/no-unsafe-argument)`

![Screenshot 2024-04-16 at 16 54 17](https://github.com/vitalets/playwright-bdd/assets/145002906/e68a680f-85d1-4c28-a956-aebef58ed141)

**But I expect**

to not have to ignore every instance of using $step.title 

**Isolated demo**

**Environment**

```
Playwright-bdd environment info:

platform: darwin
node: v18.17.0
playwright-bdd: v6.2.0
@playwright/test: v1.41.1
@cucumber/cucumber: v10.3.1
Playwright config file: playwright.config.ts

```

**Comment by RichardCariven** [comment]
issue seems to have resolved itself.

**Comment by vitalets** [comment]
> issue seems to have resolved itself.

Maybe some cache issues
