### ISSUE TITLE
Feature: Add special tag @slow

### ISSUE THREAD

**Issue by jzaratei** [vitalets/playwright-bdd#138]
I miss one of the special tags from playwright `@slow` https://playwright.dev/docs/api/class-testinfo#test-info-slow-1
Would it be possible to add it as a cucumber special tag.
Thanks

**Comment by vitalets** [comment]
Added in **v6.3.0**. [Docs](https://vitalets.github.io/playwright-bdd/#/writing-features/special-tags?id=slow).
