### ISSUE TITLE
Bug: Can't seem to be able to launch playwright with cucumber because of SyntaxError: Error reading storage state from tests-config/storageState.json:

### ISSUE THREAD

**Issue by samixchoumi** [vitalets/playwright-bdd#140]
**Given**

I'm new at using Playwright (was using Cypress before) and I'm trying to implement cucumber using your project.
But actually, I'm a bit confused, I didn't see any good project to help me so I try to take some information everywhere but I think it's not the best way to understand how it should work as I can't actually run my project ...

<details>
> My setup : 
> Playwright config : 
> ```
> import { defineConfig, devices } from '@playwright/test';
> import dotenv from 'dotenv';
> import { cucumberReporter, defineBddConfig } from 'playwright-bdd';
> 
> dotenv.config();
> 
> const testDir = defineBddConfig({
>   tags: 'not @ignore',
>   paths: ['tests/*/*.feature'],
>   require: ['tests/*/*/*.ts']
> });
> 
> export default defineConfig({
>   testDir,
>   fullyParallel: true,
>   forbidOnly: !!process.env.CI,
>   retries: process.env.CI ? 2 : 0,
>   workers: process.env.CI ? 1 : undefined,
>   reporter: [cucumberReporter('html', { outputFile: 'cucumber-report/report.html' })],
>   use: {
>     trace: 'on-first-retry'
>   },
> 
>   /* Configure projects for major browsers */
>   projects: [{
>     name: 'chromium',
>     use: {
>       baseURL: 'myBaseUrl.com',
>       ...devices['Desktop Chrome']
>     }
>   }]
> });
> ```
> My feature file : 
> ```
> Feature: Test
> 
>   Scenario: Test first scenario
>     When I am in that section
>     Then I should see "Hello world"
> ```
> And my hooks step file : 
> ```
> import { AfterAll, Before, BeforeAll } from '@cucumber/cucumber';
> import { Browser, BrowserContext, chromium, expect, Page } from '@playwright/test';
> 
> let browser: Browser;
> let context: BrowserContext;
> let page: Page;
> 
> BeforeAll(async function () {
>   browser = await chromium.launch();
> });
> 
> Before(async function({pickle}) {
>   const scenarioName = pickle.name + '_' + pickle.id
>   context = await browser.newContext({
>     recordVideo: {
>       dir: "test-results/videos"
>     }
>   })
>   await context.tracing.start({
>     name: scenarioName,
>     title: pickle.name,
>     sources: true,
>     screenshots: true, snapshots: true
>   });
>   page = await context.newPage();
>   await page.goto('/authentication/loggedOut');
>   await page.getByRole('button', {name: 'Log back in'}).click();
>   await expect(page.locator('div').getByText(/hello/).first()).toBeVisible();
>   await page.fill('input-email', process.env.LOGIN as string);
>   await page.fill('input-password', process.env.PASSWORD as string);
>   await page.locator('form').evaluate((form) => form.submit());
>   await page.waitForResponse('/authorize*');
>   await page.context().storageState({ path: 'tests-config/storageState.json' as string });
> })
> 
> AfterAll(async function () {
>   await browser.close();
> })
> ```
> My directory structure : 
> project 
>  | - hooks 
>  |      | - hooks.ts
>  | - tests 
>  |      | - testSuite
>  |             | - test
>  |                    | - test.ts
>  |             | - test.feature
>  | - tests-config
>  |      | - storageState.json (empty, should be filled by the Before hook normally ?)
>  | - playwright.config.ts
>  | - package.json
>  | - .env
</details>

**When**
`npx bddgen && npx playwright test --ui`

**Then**
![image](https://github.com/vitalets/playwright-bdd/assets/22171928/9e2cc0e4-71df-487a-8721-c1df146ff090)

**But I expect**
No error as I see on every similar project ...

**Environment**
```
platform: darwin
node: v21.1.0
playwright-bdd: v6.2.0
@playwright/test: v1.43.1
@cucumber/cucumber: v10.4.0
Playwright config file: playwright.config.ts
```

Edit : I made my setup to work, I think it was linked to the fact that I've used multiple storageState on my config, one in my project config and one in the global config so there was a conflict, I removed the one in the global config and it started working !
But now I don't understand why my setup works fine but isn't used by the other tests.

**Comment by samixchoumi** [comment]
Hello, little update, I tried this https://playwright.dev/docs/auth 
So I'm not using the Before Hooks but I've created a auth.setup.ts file with a .auth folder.
So my config looks like that : 

```
projects: [
    { name: 'setup', testMatch: /.*\.setup\.ts/ },
    {
      name: 'chromium_pre-prod',
      use: {
        baseURL: 'myBaseUrl.com',
        ...devices['Desktop Chrome'],
        storageState: '.auth/storageState.json'
      },
      dependencies: ['setup']
    }
  ]
```

It's still the same problem, tried by deleting the storageState.json that I manually added, show me the error below : 
```
Error: Error reading storage state from .auth/storageState.json:
ENOENT: no such file or directory, open '.auth/storageState.json'
```
It seem understandable but I though it would create it but, still the same problem, the authentication setup isn't executed as it wasn't done on the Before hook.

What is wrong ?

**Comment by jzaratei** [comment]
Hello @samixchoumi , make sure your 'setup' project is executed and output the '.auth/storageState.json' with the session cookies.

**Comment by samixchoumi** [comment]
Hello @jzaratei, I've made some update, now my `setup` project is executed but when it goes to the test, it seem it don't load the setup as you can see here : 
![image](https://github.com/vitalets/playwright-bdd/assets/22171928/e513a530-3ebf-4eba-9fb6-a2fbc73a6fff)
It's like my setup worked fine but it's not loaded by the test

**Comment by jzaratei** [comment]
In your playwright config, you should set your projects like this:
Note: the main project(second one in the list) should use the storageState (generated in setup project)
```
projects: [
  { name: "setup", testMatch: /.*\.setup\.ts/, testDir: "./setup" },
  {
    name: "chromium_pre-prod",
    use: {
      baseURL: "myBaseUrl.com",
      ...devices["Desktop Chrome"],
    },
  },
  { name: "test", testMatch: /.*\.test\.ts/, testDir: "./test" },
  {
    name: "chromium_pre-prod",
    use: {
      baseURL: "myBaseUrl.com",
      ...devices["Desktop Chrome"],
      storageState: ".auth/storageState.json",
    },
    dependencies: ["setup"],
  },
];
  ]
```

**Comment by samixchoumi** [comment]
Humm can't it be easier to format the project like that : 
```
projects: [
    {
      name: 'setup',
      testMatch: /.*\.setup\.ts/,
      testDir: './setup',
    },
    {
      name: 'chromium_pre-prod',
      use: {
        ...devices['Desktop Chrome'],
        storageState: '.auth/storageState.json'
      },
      dependencies: ['setup']
    }
  ]
```
It seem to work like that, but i'm looking at why it didn't trigger the URL, I think I need to call it

**Comment by jzaratei** [comment]
I rather use fixtures instead of cucumber hooks, In my case, I am using a feature file to setup the session.

```
const STORAGE_STATE = path.join(__dirname, ".auth/user.json");

{
    name: "SETUP_CHROME",
    testDir: defineBddConfig({
      outputDir: ".features-gen/setup",
      importTestFrom: "page-objects/basePage.ts",
      paths: ["features/setup.feature"],
      require: ["steps/*.ts"],
    }),
    use: {
      ...devices["Desktop Chrome"],
    },

  },
  {
    name: "REGRESSION_CHROME",
    testDir: defineBddConfig({
          outputDir: ".features-gen/regression",
          importTestFrom: "page-objects/basePage.ts",
          paths: ["features/regression/*.feature"],
          require: ["steps/*.ts"],
          verbose: true,
})
    dependencies: ["SETUP_CHROME"],
    use: {
      storageState: STORAGE_STATE'
    },
  },
```

**Comment by jzaratei** [comment]
> I rather use fixtures instead of cucumber hooks, In my case, I am using a feature file to setup the session.
> 
> ```
> const STORAGE_STATE = path.join(__dirname, ".auth/user.json");
> 
> {
>     name: "SETUP_CHROME",
>     testDir: defineBddConfig({
>       outputDir: ".features-gen/setup",
>       importTestFrom: "page-objects/basePage.ts",
>       paths: ["features/setup.feature"],
>       require: ["steps/*.ts"],
>     }),
>     use: {
>       ...devices["Desktop Chrome"],
>     },
> 
>   },
>   {
>     name: "REGRESSION_CHROME",
>     testDir: defineBddConfig({
>           outputDir: ".features-gen/regression",
>           importTestFrom: "page-objects/basePage.ts",
>           paths: ["features/regression/*.feature"],
>           require: ["steps/*.ts"],
>           verbose: true,
> })
>     dependencies: ["SETUP_CHROME"],
>     use: {
>       storageState: STORAGE_STATE'
>     },
>   },
> ```

yeah of course you need to load your app  

@Given("I am login in my-app")
  async gotoApp() {
    await this.page.goto("/");
    await expect(this.pageTitle).toBeVisible();
  }

**Comment by samixchoumi** [comment]
Okey, it was the problem, I think the doc should be updated, I thought it was done automatically by the setup step ...
