### ISSUE TITLE
Bug:@fail tag is not working correctly with Example Tables 

### ISSUE THREAD

**Issue by RichardCariven** [vitalets/playwright-bdd#141]
**Given**
I have a scenario outline with 2 example tables, one set to @fail the other to run 

eg

```
Scenario Outline: Enter an Invalid Postcode <testcase>
        Given I am on the "Onboarding Location" Page
        And I fill in the "Postcode Entry" input with "<invalidpostcode>"
        Then I should see the error message "Postcode not recognised. Double-check and try again."
        When I click the "Continue" button
        Then I am kept on the "Onboarding Location" Page
        And I fill in the "Postcode Entry" input with "<validpostcode>"
        When I click the "Continue" button
        Then I am directed to the "Select Genres" Page

        Examples:
            | invalidpostcode | validpostcode | testcase       |
            | W1F             | W1F9DJ        | invalid format |

        @fail
        Examples:
            | invalidpostcode | validpostcode | testcase         |
            |                 | W1F9DJ        | missing postcode |
```

**When**
I run the test 

**Then**
the Example set as@fail is ignored, and the example table set to run is marked as expected to fail in the test report. 

**But I expect**
The same behaviour as @skip where the Example table tagged is skipped and the one not tagged is run, I would expect the Example table marked @fail to be marked as a failing test and the one not marked to be run as normal. 

![set to Fail](https://github.com/vitalets/playwright-bdd/assets/145002906/b5169020-82ba-442c-82a3-bdefa2ef940c)
![test marked to skip](https://github.com/vitalets/playwright-bdd/assets/145002906/53a55714-1cee-4976-b9bf-85a9f36b3893)
![test set to @fail result](https://github.com/vitalets/playwright-bdd/assets/145002906/b4483a49-611f-4d4c-b575-eb174cfb26b8)
![Test set to Skip Result](https://github.com/vitalets/playwright-bdd/assets/145002906/3404fd23-e087-4b8a-a650-aae3d456c403)
![incorrectly markedd test ](https://github.com/vitalets/playwright-bdd/assets/145002906/7bb5e567-1c13-46be-b7ea-ccbc724fe3c7)

**Isolated demo**

**Environment**

```
```

**Comment by vitalets** [comment]
This was bug in Playwright - https://github.com/microsoft/playwright/issues/29104
Which version of Playwright are you using? (in general please always provide environment info)

**Comment by RichardCariven** [comment]
platform: darwin
node: v18.17.0
playwright-bdd: v6.2.0
@playwright/test: v1.41.1
@cucumber/cucumber: v10.3.1
Playwright config file: playwright.config.ts

**Comment by RichardCariven** [comment]
upgrading playwright fixed it
