### ISSUE TITLE
Question:Tag specific examples of a Scenario Outline

### ISSUE THREAD

**Issue by andreasnovak** [vitalets/playwright-bdd#144]
I would like to add tags to specific examples of a Scenario Outline. Currently it only seems possible to add tags to the entire Scenario Outline so that all examples have the same set of tags. But if example 1 is supposed to have different tags than example 2 of the same Scenario Outline, I do not see a way to achieve this. Or is there a way?

Thank you!

**Comment by vitalets** [comment]
You can tag specific examples. Just note that by Gherkin syntax you need to write another `Examples` keyword and tag it:
```gherkin
  Scenario Outline: Scenario with examples
    Then step <value>

    @mobile
    Examples:
      | value |
      | 1     |
      | 2     |

    @desktop
    Examples:
      | value |
      | 3     |
```

**Comment by andreasnovak** [comment]
Ah great, thank you so much for the advice @vitalets !
