### ISSUE TITLE
Feature: Support Code Coverage Reports

### ISSUE THREAD

**Issue by cenfun** [vitalets/playwright-bdd#145]
**The problem**
Playwright does not officially support code coverage reports like other testing tools, see [here](https://github.com/microsoft/playwright/issues/9208#issuecomment-1991904440)
So, is it possible to support code coverage reports?

**A solution**
The tool I want to introduce is [monocart-coverage-reports](https://github.com/cenfun/monocart-coverage-reports), it can generate native [V8](https://v8.dev/blog/javascript-code-coverage) reports or [Istanbul](https://istanbul.js.org/) reports, 
see integration with playwright: https://github.com/cenfun/monocart-coverage-reports?tab=readme-ov-file#playwright

**Comment by synnksou** [comment]
Hi @cenfun ! I've tested it myself with [monocart-coverage-reports](https://github.com/cenfun/monocart-coverage-reports) , it already works very well with playwright bdd on my project

**Comment by synnksou** [comment]
@cenfun Sorry I made a mistake, I completely thought it was monocart-reporter and not monocart-coverage-reporter, I'm trying to set it to add my v8 coverage with my other tests.

**Comment by cenfun** [comment]
@synnksou  `monocart-reporter` is a playwright custom reporter, which is integrated `monocart-coverage-reports` too.

**Comment by vitalets** [comment]
@cenfun `monocart-coverage-reports` should work with playwright-bdd out-of-box. Did you get any errors?

**Comment by cenfun** [comment]
@vitalets I have created an example here: https://github.com/cenfun/playwright-bdd-coverage
It works well. Thanks.
