### ISSUE TITLE
Feature: Update to Playwright@1.43.1

### ISSUE THREAD

**Issue by synnksou** [vitalets/playwright-bdd#146]
**The problem**
Incompatibility between the Page type on Axebuilder and Playwight-bdd, Axe expects a Page type 1.43.1 whereas the step gives a 1.42.1 page.
![image](https://github.com/vitalets/playwright-bdd/assets/40544802/d04c6dc4-d53e-4dee-9f50-f8dfbeacfa86)

on this code 
```typescript

When("The user needs the page to be accessiblee", async ({ page }) => { // Page 1.42
  const accessibilityScanResults = await new AxeBuilder({ page }).analyze(); // Error on page want version 1.43
...});
```

**A solution**

Upgrade the PlaywrightType to 1.43.1 ?

I can open a pull request to handle the issue @vitalets  :)

**Comment by vitalets** [comment]
@synnksou steps should pass `Page` from the Playwright installed in the project. Could you check why there are two versions of Playwright? For example `npm ls playwright-core`.

**Comment by vitalets** [comment]
Closing as there is not reply from author.
