### ISSUE TITLE
Question: sample code how to use Hooks, Before, BeforeAll

### ISSUE THREAD

**Issue by QAPranav** [vitalets/playwright-bdd#149]
Is there a proper document or any sample code how to use Hooks, Before, BeforeAll thank you 
I tried this feature that not able to invoke beforeAll where I load all the cookies for the project, proper documents would be great

**Comment by vitalets** [comment]
Hi @QAPranav !
Are there something missing in the [Hooks docs](https://vitalets.github.io/playwright-bdd/#/writing-steps/hooks?id=beforeall-afterall)?

**Comment by QAPranav** [comment]
Hi @vitalets thank you for responding, I tried to use the beforeAll with fixture base on document, which is not allowing 
here is my code 
### This is Global.ts
`import { Page } from '@playwright/test';

const authFile = 'cookies.json';
export class Global{
    constructor(public page: Page){
        this.page = page
    }
    async setup(){
        await this.page.goto('');
        await this.page.getByRole('button', { name: 'I accept cookies' }).click();
        await this.page.context().storageState({ path: authFile });
    }
}`

### This is were I load my Fixtures
`import { test as base } from 'playwright-bdd';
import { Page } from '@playwright/test';
import * as Pages from '../pages/index';

const createTestFunction =
  <T extends new (page: Page) => InstanceType<T>>(PageClass: T) =>
  (
    { page }: { page: Page },
    use: (fixture: InstanceType<T>) => Promise<void>
  ) =>
    use(new PageClass(page));

type MyFixtures = {
  globalPage: Pages.Global
};

export const test = base.extend<MyFixtures>({
  globalPage: createTestFunction(Pages.Global)
});
`
### This is my hooks.ts

`import { createBdd } from 'playwright-bdd';
import { test } from '../fixtures/pagefixtures';

const { BeforeAll, AfterAll } = createBdd(test);

BeforeAll(async function ({ globalPage }) {
  await globalPage.setup();
});
`
This code I should aspect one cookies.json file generated on project level but it is not generating any cookies.json file 
Where I get error 
Property 'globalPage' does not exist on type 'PlaywrightWorkerArgs & PlaywrightWorkerOptions & BddFixturesWorker & { $workerInfo: WorkerInfo; }' this is type error I  am getting 

Even I tried using this keyword in hooks which is still not allowing me and playwright page fixture is also not invoking here 
It would be nice to have page fixture
BeforeAll(async function ({ page }) {
  await page.goto('')
});
please review this thank you for your help

**Comment by vitalets** [comment]
> Property 'globalPage' does not exist on type 'PlaywrightWorkerArgs & PlaywrightWorkerOptions & BddFixturesWorker & { $workerInfo: WorkerInfo; }

This is because BeforeAll runs once per worker, and fixture should be [worker-scoped](https://playwright.dev/docs/test-fixtures#worker-scoped-fixtures), not test-scoped. Fix can be like this:
```ts
export const test = base.extend<{}, MyFixtures>({
  globalPage: [createTestFunction(Pages.Global), { scope: 'worker' }]
});
```
Notice that in worker scoped fixtures there is no pre-created page (b/c each test has own page), so you should create page manually like it's shown in Playwright docs.
