### ISSUE TITLE
Question: Would you mind adding more extensive examples to this repo?

### ISSUE THREAD

**Issue by alexhvastovich** [vitalets/playwright-bdd#150]
I am looking into best practices with playwright-bdd pom with fxitures and there is not much online. 
Would  you mind expanding the example having:
- features
- pages
   -- with base_page
 - locators
 - config
- fixtures
- hooks 
with browser initialization and tier-down. 
it could be based on some login page like: https://the-internet.herokuapp.com/login

**Comment by vitalets** [comment]
Sure, will create such example.

**Comment by alexhvastovich** [comment]
Thank you! Also, I messaged you on FB, if you have time for a chat.

**Comment by QAPranav** [comment]
Following

**Comment by vitalets** [comment]
Examples were added in https://github.com/alexhvastovich/playwright-bdd-real-world.
Feel free to create new issue for more specific questions.
