### ISSUE TITLE
Question: Example code for writing custom locators

### ISSUE THREAD

**Issue by NikkTod** [vitalets/playwright-bdd#152]
Hi @vitalets, do you happen to have some example on how we write custom locators with decoratrs syntax.

In my fixture file I have the following:

![image](https://github.com/vitalets/playwright-bdd/assets/94455079/e54132d3-cee0-431a-ab7d-b366183315ca)

But how to call it from the my POM page file

![image](https://github.com/vitalets/playwright-bdd/assets/94455079/337fc41c-499d-40e9-b54c-711ee9d96a2c)

**Comment by vitalets** [comment]
This is because TypeScript does not know that you added `getByDataTestId` method to the page.
In general I'd suggest to not augment Playwright's built-in objects like page, etc.
I see two options:
1. Inherit your POMs from the BasePage that contains such common methods:
```ts
class BasePage {
  constructor(public page) {}

  getByDataTestId(id: string) {
    return the.page.locator(`[data-test="${id}"]`);
  }
}

class RealPage extends BasePage {
  getSubmitButton() {
    return this.getByDataTestId('submit');
  }
}

// ...
base.extend({
  realPage: ({ page }, use) => use(new RealPage(page))
});
```

2. Or create a separate helper fixture and pass it to POMs:
```ts
class Helper {
  constructor(public page) {}

   getByDataTestId(id: string) {
    return the.page.locator(`[data-test="${id}"]`);
  }
}

class RealPage {
  constructor(public helper: Helper) {}

  get page() {
    return this.helper.page;
  }

  getSubmitButton() {
    return this.helper.getByDataTestId('submit');
  }
}

// ...
base.extend({
  helper: ({ page }, use) => use(new Helper(page)),
  realPage: ({ helper }, use) => use(new RealPage(helper))
});
```

**Comment by NikkTod** [comment]
@vitalets thanks for confirming, will go with option 1, I already have such common class.
