### ISSUE TITLE
Question:  Allure report shows unnecessary hooks and random order number in the report

### ISSUE THREAD

**Issue by kashiMathura** [vitalets/playwright-bdd#154]
I have not added any hooks and the allure report shows a lot of reporting in before hooks and after hooks.
Is there any way that I show it in report only the implement which I have added?

Also the steps shows incorrect order number
Example:
#1 
#3 
#2 
#4

For example , I do not want these in the the reporting

sBefore Hooks
50msfixture: $cucumber
1msfixture: $workerHookFixtures
0msfixture: $beforeAll
1msfixture: $afterAll
0msfixture: $testMetaMap— src/features/login.feature.spec.js:31
0msfixture: $testMeta
1msfixture: $applySpecialTags
0msfixture: $scenarioHookFixtures
0msfixture: $tags
1msfixture: $test— src/features/login.feature.spec.js:31
1msfixture: $step
0msfixture: $bddWorldFixtures
1msfixture: $lang
0msfixture: $uri— src/features/demo.feature.spec.js:31
0msfixture: $bddWorld
1msfixture: $after
0msfixture: $before
0msfixture: Given
746msfixture: browser
30msfixture: context
418msfixture: page
1msfixture: When
1msfixture: Then
0msfixture: And
_______________________________________
After Hooks
1msfixture: And
0msfixture: Then
0msfixture: When
0msfixture: page
0msfixture: context
0msfixture: Given
0msfixture: $before
1msfixture: $after
0msfixture: $bddWorld
0msfixture: $uri— src/features/demo.feature.spec.js:31
0msfixture: $lang
0msfixture: $bddWorldFixtures
0msfixture: $step
0msfixture: $test— src/features/demo.feature.spec.js:31
1msfixture: $tags
0msfixture: $scenarioHookFixtures
0msfixture: $applySpecialTags
0msfixture: $testMeta
0msfixture: $testMetaMap— src/features/demo.feature.spec.js:31

**Comment by vitalets** [comment]
Could you share more details on that - show example of the report and code how do you generate it?
A full demo would be very helpful: https://github.com/vitalets/playwright-bdd-example

**Comment by vitalets** [comment]
Closing as outdate. Feel free to try on the latest version of playwright-bdd and re-open if needed.
