### ISSUE TITLE
Question: Is it possible to run a specific tag for a project ?

### ISSUE THREAD

**Issue by samixchoumi** [vitalets/playwright-bdd#155]
Hello, I'm migrating Cypress to Playwright with BDD, so I used your repository for some automation project, but I have a specific automation project that launch multiple tag : 

Actually, with Cypress, I launched specific project like that : 
```
// This one test all except @canary tag
"test": "npx cypress-cloud run"
// This one launch only Yop folder
"tests-yop": "npx cypress-cloud run --spec 'cypress/integration/Yop/*'",
// This one launch only Yep folder
"tests-supply": "npx cypress-cloud run --spec 'cypress/integration/Yep/**/*'",
// This one launch only @canary tag test
"tests-canary-supply": "npx cypress run --env TAGS=@canary",
```

How can I do a similar behavior with playwright project config feature and playwright bdd ?

As we actually define our path in the config with : 
```
const testDir = defineBddConfig({
  tags: 'not @ignore',
  paths: ['tests/*/*.feature'],
  require: ['tests/*/*/*.js']
});
```

Is it possible to override it for each project create in the playwright config ?

**Comment by samixchoumi** [comment]
Humm seem interesting, I will test it but how do you focus a specific folder than ?

**Comment by thulasipavankumar** [comment]
You can run particular spec files in playwright by using command `npx bddgen && npx playwright test .features-gen/features/LandingPage.feature.spec.js --headed`

In above example my feature file is `LandingPage.feature` and `npx bddgen` creates the spec files in the folder `./.features-gen/features/`

**Comment by samixchoumi** [comment]
I tried your first solution, it seem good and allow me to don't use the specific folder but now i'm encountering a problem with parallelisation on CI.

Actually I do something like that regarding your previous answer : 
```
"test": "npx bddgen --tags 'not @deal and not @ignore' && npx playwright test --shard=$CI_NODE_INDEX/$CI_NODE_TOTAL",
    "test-deal": "npx bddgen --tags '@deal and not @ignore' && npx playwright test --shard=$CI_NODE_INDEX/$CI_NODE_TOTAL --workers=1",
```
First I call `test-deal` then `test`.
But, for any reason, it seem that instead of running my feature file sequentially tagged with `@deal`, it divide it in all my CI shard (here 5) ...
