### ISSUE TITLE
Question: What is the CLI command to parallelize some test and not parallelize other tests ?

### ISSUE THREAD

**Issue by samixchoumi** [vitalets/playwright-bdd#156]
Hello, to be more precise.

I have a situation where I tag `@deal` on some `Feature`. My goal is to run sequentially all tests from these feature files.
Like : 
- Feature1 tagged @deal : - run sequentially on a 1st shard (in the CI)
- Feature2 tagged @deal : - run sequentially on a 2nd shard (in the CI)
- Feature3 tagged @deal : - run sequentially on a 3rd shard (in the CI)
- Feature4 not tagged : - run parallel on a 4th or 5th shard (in the CI)
- Feature5 not tagged : - run parallel on a 4th or 5th shard (in the CI)
- Feature6 not tagged : - run parallel on a 4th or 5th shard (in the CI)
- Feature7 not tagged : - run parallel on a 4th or 5th shard (in the CI)
Actually I've this command : 
```
"test-not-deal": "npx bddgen --tags 'not @deal and not @ignore' && npx playwright test --shard=$CI_NODE_INDEX/$CI_NODE_TOTAL",
"test-deal": "npx bddgen --tags '@deal and not @ignore' && npx playwright test --shard=$CI_NODE_INDEX/$CI_NODE_TOTAL --workers=1",
```
But it doesn't work as expected, their is 1 worker BUT it parallelize the feature tagged with `@deal` in multiple shard instead of running all the feature file sequentially.
I'm thinking of running a new CI stage to separate the deal part from the other test but I still need to understand how to avoid parallelization between shard when worker is set to 1.

> Useful information : 
> In a Feature it's possible I've multiple Scenario Outline and Examples.
> It's the Feature that is tagged with @deal, not the Scenario Outline.
> Maybe it's linked to why, feature file are parallelized in multiple shard instead of sequentially ?

Any idea ?

**Comment by vitalets** [comment]
Hi @samixchoumi 

Maybe I get it wrong, but if you want to run features 1,2,3 sequentially - you don't need sharding, just set workers = 1 as you did:
```
npx bddgen --tags '@deal and not @ignore' && npx playwright test --workers=1
```

**Comment by samixchoumi** [comment]
Hello, thanks for your answer, just to let you know, if you do it like
that, it will run my 5 scenario outline (separated in my 3 feature file) on
3 shards but it will not run them sequentially.
Like :
Feature 1 -> scenario outline 1 & 2
Feature 2 -> scenario outline 3 & 4
Feature 3 -> scenario outline 5
If I do your command it works like that :
Shard 1 run scenario outline 1 & 3 sequentially
Shard 2 run 2 & 4 sequentially
Shard 3 run 5 sequentially
But I want that shard 1 run scenario 1&2 sequentially,
Shard 2 run scenario 3&4 sequentially and finally Shard 3 run scenario 5
sequantially.

But FYI I’ve made a script that allow multi sharding properly

**Comment by vitalets** [comment]
Ok, great! 
Anyway you can create a repro via [playwright-bdd-example](https://github.com/vitalets/playwright-bdd-example) showing the feature files and actual run order.
