### ISSUE TITLE
Feature: specify different parallelization mode for a specific feature file

### ISSUE THREAD

**Issue by nicopado** [vitalets/playwright-bdd#159]
**The problem**
Currently I am working on a project with multiple feature files.
One of this feature include the download of a file. The tests runs ok in the default parallel mode but fail when run fully parallel.
All the other feature files can run in full parallel mode with no problem.
It would be nice to specify in the feature file the parallelization mode to use for those tests
**A solution**
Currently playwright allow us to do this with:
`test.describe.configure({ mode: 'parallel' });`
but since we generate the spec code with npx bddgen is not possible to do this in a "clean" way.
We can hack it around by manually adding this specification to the generated file before running it, but it would be way better to have this think picked up from the feature file / somewhere else

**Comment by vitalets** [comment]
Looks like [@mode tag](https://vitalets.github.io/playwright-bdd/#/writing-features/special-tags?id=modexxx) solves that. Could you try with your setup?

**Comment by nicopado** [comment]
> Looks like [@mode tag](https://vitalets.github.io/playwright-bdd/#/writing-features/special-tags?id=modexxx) solves that. Could you try with your setup?

Oh I missed that! Yeah that looks like EXACTLY what I was looking for. Thanks!

**Comment by vitalets** [comment]
No problem!
