### ISSUE TITLE
[Question] Data tables typescript

### ISSUE THREAD

**Issue by NikkTod** [vitalets/playwright-bdd#16]
Hello @vitalets , great work with playwright-bdd 💯 

One question concering datatables, as we are using a lot of parameters in our scenarious. 

Do we have some examples on data tables?

E.g. 
```
Given I am in registration page
And I provide below information during registeration
  | Fields        | Inputs                                  |
  | firstName     | Tom                                    |
  | lastName      | Jerry                                   |
  |  phone        | 123456789                           |
  |  email        | tomandjerry@cartoon.com  | 
```
  
```
  Scenario Outline: Create <NAME>
    Given a user called "<NAME>"  with email address "<EMAIL>" who lives in "<CITY>" and was born "<DOB>"

    Examples: 
      | NAME            | EMAIL           | CITY          | DOB        |
      | Vivienne Senger | vs@example.com  | Everett       | 1965-11-09 |
      | Mallory Wisoky  | mw@example.com  | Boynton Beach | 1927-12-09 |
```

**Comment by vitalets** [comment]
Hi @NikkTod , yes both DataTables and DocStrings are supported. Here are example step definitions:
* [DataTables](https://github.com/vitalets/playwright-bdd/blob/fb19db45699084e80fbfa92bc97333fd50bda9d5/test/steps.ts#L36)
* [DocStrings](https://github.com/vitalets/playwright-bdd/blob/fb19db45699084e80fbfa92bc97333fd50bda9d5/test/steps.ts#L32)
