### ISSUE TITLE
Feature: Access Scenario Name inside Test

### ISSUE THREAD

**Issue by LarsFischer97** [vitalets/playwright-bdd#165]
**The problem**
I want to create a generative fixture based on every scenario I am in, but i can not access that information.
Accessing the scenario name inside the test can be usefull for Background steps.

**A solution**
Something like this?
https://stackoverflow.com/questions/23602953/how-to-get-name-of-scenario-in-cucumber-java

**Comment by vitalets** [comment]
Yes, it's possible. Scenario name is actually test title, that is available via `$testInfo`:
```ts
Given('step', async ({ $testInfo }) => {
  console.log($testInfo.title);
});

**Comment by LarsFischer97** [comment]
Thank you for the fast response, love your progess and work here btw!
