### ISSUE TITLE
Update Playwright version to v1.45.0

### ISSUE THREAD

**Issue by bandriychuk** [vitalets/playwright-bdd#167]
Upgrade the Playwright version to v1.45.0

[](https://github.com/microsoft/playwright/releases/tag/v1.45.0)

**Comment by vitalets** [comment]
Our tests are [passing](https://github.com/vitalets/playwright-bdd/actions/runs/9689023467) over Playwright 1.45.
Do you have any issues with it?

**Comment by vitalets** [comment]
Closing as there is no reply from author.
