### ISSUE TITLE
Question: migration-v7 - cucumber-style/playwright.config.ts incorrect

### ISSUE THREAD

**Issue by Deepa-Mahesh-P** [vitalets/playwright-bdd#173]
https://github.com/vitalets/playwright-bdd/blob/main/examples/cucumber-style/playwright.config.ts

Hi According to V7, the config should be different above from 

https://vitalets.github.io/playwright-bdd/#/guides/migration-v7?id=new-steps-option

Can u suggest if changes are dual? old and new works ?

**Comment by vitalets** [comment]
@Deepa-Mahesh-P good point! I will update config in docs, thank you.

> Can u suggest if changes are dual? old and new works ?
Old config works as well. That's why example tests didn't catch it :)

**Comment by Deepa-Mahesh-P** [comment]
Can we have 2  config files then and scripts pointing to these then

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Deepa-Mahesh-P** [comment]
Similarly Vitaly, if you suggest its ok. I can create sample projects with Cucumber-BDD/Saucelabs/Lambdatest/[Additional Appium driver i can add], Page objects pattern etc .. can we add it as a Git submodule instead. w can keep adding samples and ask others top contribute

**Comment by vitalets** [comment]
> Can we have 2  config files then and scripts pointing to these then .. i can Do a PR then?

I've made it [this way](https://github.com/vitalets/playwright-bdd/blob/main/examples/cucumber-style/playwright.config.ts) - let's keep examples as simple as possible, I think two configs can be confusing:
```ts
// before playwright-bdd v7
const testDir = defineBddConfig({
  paths: ['features'],
  require: ['steps/*.ts'],
  importTestFrom: 'steps/fixtures.ts',
});

// since playwright-bdd v7
/*
const testDir = defineBddConfig({
  features: './features',
  steps: './steps',
});
*/
```

**Comment by vitalets** [comment]
> Similarly Vitaly, if you suggest its ok. I can create sample projects with Cucumber-BDD/Saucelabs/Lambdatest/

I like it. I suggest to put such examples into separate GitHub repos, I can add links to readme.

**Comment by Deepa-Mahesh-P** [comment]
ok ..
