### ISSUE TITLE
Limitations

### ISSUE THREAD

**Issue by viktor-silakov** [vitalets/playwright-bdd#174]
Hello, I'm interested in using the playwright-bdd library for my project. Before I start, could you please tell me if there are any significant limitations or restrictions I should be aware of? Thank you!

**Comment by vitalets** [comment]
Hi @viktor-silakov 

General points to be considered:
* supported Playwright versions (>= 1.35 at the time of writing)
* usage of custom Cucumber formatters/reporters, they may be not compatible with playwright-bdd (although we try to follow cucumber/messages spec)
* if there are existing tests, migration may require some refactoring
    - If there are existing Cucumber tests, you will need some refactoring of your code. If you use custom Cucumber formatter, it may be not compatible.
    - If there are existing Playwright tests, it's easier -> just create separate project in Playwright config and check how it goes.

If possible, share more info about current stack of your project.

**Comment by viktor-silakov** [comment]
Hi @vitalets 

> supported Playwright versions (>= 1.35 at the time of writing)

OK

> usage of custom Cucumber formatters/reporters, they may be not compatible with playwright-bdd (although we try to follow cucumber/messages spec)

Is it possible to create some adapter which translate from Cucumber format to Playwright

>If there are existing Playwright tests, it's easier -> just create separate project in Playwright config and check how it goes.

Plan migration WDIO -> PW, want BDD layer

> If possible, share more info about current stack of your project.

Yeah, this is my [Visual Testing Tool - Syngrisi](https://github.com/syngrisi/syngrisi/tree/main/packages/syngrisi), if you are interested you can try this using Пitpod the button is on the project page. I want to rewrite my whole test solution, it's a mess now.

**Comment by viktor-silakov** [comment]
by the way, do you plan to add test recording via VSCode extension or something?

**Comment by vitalets** [comment]
> Is it possible to create some adapter which translate from Cucumber format to Playwright

Currently we do the opposite: translate Playwright's reporter output to Cucumber compatible json/messages. It works for all Cucumber built-in formatters. But for custom Cucumber formatters there potentially can be issues.

> Yeah, this is my [Visual Testing Tool - Syngrisi](https://github.com/syngrisi/syngrisi/tree/main/packages/syngrisi)

Looks interesting! 

> by the way, do you plan to add test recording via VSCode extension or something?

Do you mean generating tests code while you perform actions in the browser? This ticket can be relevant: https://github.com/vitalets/playwright-bdd/issues/30.

**Comment by vitalets** [comment]
Closing as all points were discussed.
Feel free to reopen if needed.
