### ISSUE TITLE
Question: bddgen package is not recognized

### ISSUE THREAD

**Issue by dpjp** [vitalets/playwright-bdd#177]
Hi @vitalets  @VitaliyPotapov  - 

Am trying to execute my playwright tests in github actions using playwright-bdd
Below is the versions I use, 

@playwright/test: 1.45.1
@cucumber/cucumber : 10.8.0
playwright-bdd: 6.6.0

**The test works successfully in my local**. 

But when the same tests executed in github actions, its failing in the below step. I see that the packages were successfully installed. When I execute my test "npx bddgen && npx playwright test" am getting "To get "bddgen" CLI please install "playwright-bdd" package:
npm install -D playwright-bdd"

Sharing the screenshots of yaml and workflow execution
![pw-bdd-github_issue](https://github.com/vitalets/playwright-bdd/assets/29004769/8546794f-75b6-4d5d-89aa-13fd282d38cc)
![pw-bdd-github_issue_yaml](https://github.com/vitalets/playwright-bdd/assets/29004769/60bab4f1-51e0-4f0e-bd12-3bdf63d308c9)

Can you please help us here..?

**Comment by vitalets** [comment]
Hey @dpjp 

Looks like `bddgen` package got installed. Although I've tried this scenario locally, playwright-bdd correctly overwrites `bddgen` executable.
Could you try to run locally `npm uninstall bddgen`, and if there are changes in package.json / package-lock.json - commit and re-run CI actions?

**Comment by dpjp** [comment]
Hey @vitalets  - After uninstalling bddgen, it worked. Thanks much.
