### ISSUE TITLE
Feature: Any solution that can decrease size of cucumber html report 

### ISSUE THREAD

**Issue by NikkTod** [vitalets/playwright-bdd#182]
**The problem**
We have a test suite with around 200 end-to-end tests. After execution of all tests the size of the generated cucumber report is enormous (181.6 MB). Some CI platforms have size limit and in our case TeamCity has 300 MB for artifacts. This means that when we have certain amound of tests failed it will block the upload of the report.

Here is a screenshow of our last test run, just for comparison the playwright html report is just 1.06 MB. 

![image](https://github.com/user-attachments/assets/623abd52-9597-4d7f-b845-7c521c298222)

**Comment by vitalets** [comment]
Hi @NikkTod ! Waiting for externalize attachments in Cucumber reporter https://github.com/cucumber/cucumber-js/pull/2413.
Until that, could you check what is the main reason of file size - screenshots?

**Comment by NikkTod** [comment]
Hi @vitalets, seems to be the traces/screenshots yes.

I tried to open it in notepad++ , I saw that line 43 is very long as you can see the scrollbar to the right

![image](https://github.com/user-attachments/assets/fa0f8bf5-c0e4-4f3d-85ea-2381298f7044)

**Comment by vitalets** [comment]
Could you also share your config? I think the following setup should skip unneeded items:
```
use: {
  screenshot: '',
  video: 'on-first-retry',
  trace: 'retain-on-failure'
},
```

**Comment by NikkTod** [comment]
I just have the trace option in the config file

use: {
  trace: 'retain-on-failure'
},

**Comment by NikkTod** [comment]
Hi @vitalets , nice to see that https://github.com/cucumber/cucumber-js/pull/2413 is merged :)

**Comment by vitalets** [comment]
Hi @NikkTod , yes also following this activity. Will try to add in the nearest release of pw-bdd!

**Comment by NikkTod** [comment]
@vitalets thanks for the info, I tried with the json report and without attachments is way less as size compared to the cucumber report. 

![image](https://github.com/user-attachments/assets/510b4208-0f21-4557-9564-91a85c30a3b2)

It`s not the best test, as we did not have so much test fails and that is why the cucumber report is just 18MB, but its like 18 times bigger than the json report, which is without the trace attachments.

![image](https://github.com/user-attachments/assets/52d59c0f-8710-4424-8ff2-9e4d812332c1)

**Comment by NikkTod** [comment]
Hi @vitalets, report size is great now, `externalAttachments:true` helped. Thank you for that!

There is an issue for the traceviewer link, will open a ticket for it.
