### ISSUE TITLE
Question: Handling multiple StorageStates

### ISSUE THREAD

**Issue by matiasleandronunez** [vitalets/playwright-bdd#184]
Hey guys! I've the following situation, I've a solution that needs to run scenarios with different Storage States, let's say for the sake of simplicity we have 'No Auth', 'User' and 'Admin'. I generate the json files without trouble in a setup project, but then when it comes to use them I can only reference one Storage State per project. 

To solve similar issues in Selenium + cucumber I would use with per-scenario hooks, In not-BDD playwright a possible solution is doing something like _**test.use({ storageState: "some.json" });**_ to set each test. 

I'm using POM and instantiating pages in a fixture. This will instantiate pages with the 'page' object which has the context having the same storageState for the whole project.
I've explored solutions, one possibility is instantiating lots of fixtures, but this causes a lot of code repetition and would have to resort to slight variations in steps doing the very same but with differently instantiated page objects, on top of being possible not very performant. Other way could be setting projects per state and filtering features smartly but I'd scramble the suite, the reports would look clumsy, and I may end up with maybe 7 or 8 projects * cross-browser. I'd be difficult to follow up.
I've tried some hacky ways because pw doesn't expose an API to manage storageState in runtime, I can clear the storageState but writing it proves more difficult. Regardless I feel like there has to be a better way.

Is there a way around this issue in playwright-bdd ?

**Comment by vitalets** [comment]
Hey @matiasleandronunez !
In general, the approach should be the same as for non-bdd Playwright projects. So you said, you apply `test.use({ storageState: "some.json" });` for each test. Could you provide an example, how do you do this? I assume, you don't wrap each test with `describe` and apply `test.use`. I think you apply it on the file level or have any other structure, e.g. no-auth tests, user tests, admin tests. Having that structure, you can rely on it to use correct storageState.
For example, if your follow directories structure:
```
tests/
  noauth/
  user/
  admin/
```
then you can apply state dynamically based on the current test-file path:
```ts
export const test = base.extend({
  storageState: async ({ }, use, testInfo) => {
    if (testInfo.file.includes('/user/')) {
       await use('user-state.json');
    } else if (testInfo.file.includes('/admin/')) {
       await use('admin-state.json');
    } else {
       await use({ cookies: [], origins: [] });
    }
  },
});
```
Or you can apply state by bdd tags:
```gherkin
@admin
Feature: admin dashboard
    
    Scenario: show admin dashboard
```

Fixture:
```ts
export const test = base.extend({
  storageState: async ({ $tags }, use, testInfo) => {
    if ($tags.file.includes('@user')) {
       await use('user-state.json');
    } else if ($tags.file.includes('@admin')) {
       await use('admin-state.json');
    } else {
       await use({ cookies: [], origins: [] });
    }
  },
});
```

**Another approach** is to have special step that instantiates page with needed storageState. E.g.
```gherkin
Feature: admin dashboard
    
    Scenario: show admin dashboard
    Given I'm logged-in as admin
    # ...
```
It requires more code, here is the [example](https://github.com/MaxEinEp/playwright-bdd-example/blob/main/test/steps/genericSteps.ts#L16).

**Comment by matiasleandronunez** [comment]
Thanks for your answer! I'll try the first approach as it is cleaner and let you know if it worked.

**Comment by matiasleandronunez** [comment]
Used the tag approach, worked like a charm! Thanks. Leaving the change here in case it can help someone else:
https://github.com/matiasleandronunez/playwright_ts_with_bdd/pull/5/files

**Comment by vitalets** [comment]
You are welcome. Thanks for sharing!

**Comment by helmutchecker** [comment]
I also implemented the approach using tags, which caused an issue unfortunately, and stumbled across this question.
In my current setup, as mentioned in another thread, I am using a project for BDD test cases and another project using "plain" playwright tests: https://github.com/vitalets/playwright-bdd/issues/166.
The issue arises when executing the non-BDD tests and is related to following storageState fixture:

```
storageState: async ({ storageState, $tags, loggingService }, use) => {
    for (const tag of $tags) {
      if (tag.includes("@user:")) {
        const user = tag.split(":")[1];
        loggingService.logMessage(`detected annotation ${tag} => using storage state ${user}`);
        storageState = `${process.env["AUTH_FILE_DIR"]}/${user}.json`;
      }
    }
    await use(storageState);
  },
```

The error message then is similar to one already seen in the other context with parallel execution of BDD and non-BDD: 
`Error: Can't find testMeta for key ""`

Is there an issue in initialization of the $tags fixture when not using BDD style, or are there some expected limitations known.

**Comment by vitalets** [comment]
@helmutchecker I confirm that's a bug, thanks for raising. 
Created an issue for that https://github.com/vitalets/playwright-bdd/issues/189
Will fix in the nearest release.

**Comment by Mvd-pe** [comment]
Hi @vitalets, I see that in the https://github.com/MaxEinEp/playwright-bdd-example/blob/main/test/steps/genericSteps.ts#L16 there is a comment //not used anymore. Do you still recommend this resolution?

**Comment by luchianneos** [comment]
> Hi [@Mvd-pe](https://github.com/Mvd-pe), the recommended solution for multi-user scenario with dynamic auth: https://github.com/vitalets/playwright-bdd/tree/main/examples/auth-in-steps
> 
> Pls, let me know if something is unclear there. As it looks like a very common scenario.

Hi @vitalets. This approach is working nicely, the only missing thing in this example is using page objects with the correct context page.

For example my setup was the following:
```ts
interface CustomFixtures {
  ctx: Ctx;
  dashboardPage: DashboardPage;
  projectPage: ProjectPage;
}

export const test = base.extend<CustomFixtures>({
 ctx: async ({}, use) => {
    const ctx = {} as Ctx;
    await use(ctx);
    await ctx.page?.context().close();
  },
  dashboardPage: async ({ page }, use) => {
    const dashboardPage = new DashboardPage(page);
    await use(dashboardPage);
  },
  projectPage: async ({ page }, use) => {
    const projectDetailsPage = new ProjectPage(page);
    await use(projectDetailsPage);
  },
});
```

The issue here is that the page objects are being created with the wrong page because the correct one is being set inside the auth step.

It could be solved by creating a new object **pages** and creating them inside the auth step after providing new context.

I was also able to solve this issue by keeping things as they are and using a proxy to lazily read the page objects

**Comment by vitalets** [comment]
@luchianneos yes, this is a good point.
There can be different approaches to make POMs with dynamic page instance.
Besides the mentioned options, I thought about two:
1. write POM classes with getters, so that you can dynamically re-set the `page` property:
    ```ts
    class DashboardPage {
      constructor(public page:Page) {}
      
      get loginButton() {
      return this.page.getByText('Login');
    }
    ```

Btw, could you share the code of `createPageProxy` helper?

**Comment by luchianneos** [comment]
@vitalets sure, maybe it can help someone:

```
import { Page } from '@playwright/test';

import { Ctx } from '../models/context.model';

/**
 * Creates a proxy for a page object that lazily initializes the real page object
 * when any of its methods are accessed.
 *
 * @param ctx The context object containing the Playwright page
 * @param PageClass The page class constructor
 * @returns A proxy object that behaves like an instance of PageClass
 */
export function createPageProxy<T>(ctx: Ctx, PageClass: new (page: Page) => T): T {
  let realPageInstance: T | null = null;

  // Create a proxy with an empty target object
  return new Proxy(Object.create(null), {
    get: (target, prop: string | symbol) => {
      if (!ctx.page) {
        throw new Error('Page is not initialized. Make sure to call "I am logged in as" step first.');
      }

      // Initialize the real page instance on first access and cache it
      if (!realPageInstance) {
        realPageInstance = new PageClass(ctx.page);
      }

      // Get the property or method from the real instance
      const value = realPageInstance[prop as keyof T];

      // If it's a method, bind it to the real instance to preserve 'this' context
      if (typeof value === 'function') {
        return function (...args: any[]) {
          // Use a properly typed function call instead of Function type
          return (value as (...args: any[]) => any).apply(realPageInstance, args);
        };
      }

      return value;
    },
  }) as T;
}
```

**Comment by vitalets** [comment]
Thank you!

**Comment by vitalets** [comment]
One question: if during the test `ctx.page` will be re-assigned, the POM will refer to the old one as `realPageInstance` is not updated?
