### ISSUE TITLE
Question: Adding Cucumber provided config options in playwright-bdd's config

### ISSUE THREAD

**Issue by rraffi** [vitalets/playwright-bdd#186]
According to the `v7` documentation on Cucumber configs: https://vitalets.github.io/playwright-bdd/#/guides/migration-v7?id=cucumber-config
> Now cucumber.js is not loaded anymore. You can provide all BDD options in playwright.config.ts explicitly.

**Q.** How do I add Cucumber provided configs like `dryRun` (or config options from this list: https://github.com/cucumber/cucumber-js/blob/main/docs/configuration.md#options) to `playwright.config.ts` file, explictly?

I tried including the config options in the `defineBddConfig()` call and it didn't seem to work:

```
import { defineConfig }from '@playwright/test';
import { cucumberReporter, defineBddConfig } from 'playwright-bdd';

const testDir = defineBddConfig({
    features: 'features/*.feature',
    steps: [
        'steps/*.ts',
        'support/fixtures.ts',
    ],
    verbose: true,
    dryRun: true // config not recognized
});

export default defineConfig({
    testDir,
    reporter: [cucumberReporter('html', { outputFile: 'cucumber-report.html'})],
    fullyParallel: true,
    // workers: process.env.CI ? 2 : 4,
    use : { ...
    },

    projects: [ ...
      ],
});
```
_P.S. Thank you for `playwright-bdd`. I am really enjoying working on the `v7` version._

**Comment by vitalets** [comment]
Hey @rraffi !
Many Cucumber options are related to Cucumber runner, that's why they are excluded.
If there are some options needed for Playwright-bdd, I'm ready to add them.
Could you share your expectations from `dryRun` option for Playwright with BDD?
It seems that running only `npx bddgen` will produce similar result as Cucumber's `dryRun` - check scenarios without actually executing them.

_P.S. You are welcome :)_

**Comment by rraffi** [comment]
> Hey @rraffi ! Many Cucumber options are related to Cucumber runner, that's why they are excluded. If there are some options needed for Playwright-bdd, I'm ready to add them. Could you share your expectations from `dryRun` option for Playwright with BDD? It seems that running only `npx bddgen` will produce similar result as Cucumber's `dryRun` - check scenarios without actually executing them.
> 
> _P.S. You are welcome :)_

Thanks, @vitalets. That makes sense -- using `npx bddgen` does the job of `dryRun` as well 🙌 . 

I was a bit confused by the wording in the documentation "...You can provide all BDD options in playwright.config.ts explicitly." I mistakenly thought that **any** Cucumber bdd options (provided by Cucumber) could be explicitly included in the Playwright config file, which I now realize is not the case.

**Comment by vitalets** [comment]
> I was a bit confused by the wording in the documentation "...You can provide all BDD options in playwright.config.ts explicitly." I mistakenly thought that **any** Cucumber bdd options (provided by Cucumber) could be explicitly included in the Playwright config file, which I now realize is not the case.

That's good point. I've updated docs on that.
https://vitalets.github.io/playwright-bdd/#/guides/migration-v7?id=cucumber-config
