### ISSUE TITLE
Is there an example of how to handle projects using POM pattern  

### ISSUE THREAD

**Issue by odeatomas** [vitalets/playwright-bdd#19]
Hi 
I have followed the steps and trying to figure out if the is a config I need to change to generate PW tests for a project that is using Page Object Model Pattern.

when I run playwright-bdd 

I get the following spec.js format

```
/** Generated from: features\tools\DataExport.feature */
import {test} from "playwright-bdd";

test.describe("Data Export", () => {

    test("Create Data Export", async ({Given, When, Then}) => {
        await Given("Go to login page");
        await When("User logs in user name \"User1\" and password \"Passw0rd1\", \"\"");
        await Then("I select \"Tools\" \"Data Export\" view");
        await Then("I create an Data Export");
    });

});
```

Which is missing any page object references - for example this how the original step file looks  

```
Then('I create Data Export', async()=>{
    const dataexport = new DataExportPage();
    await dataexport.createDataExport();

});
```

I have tried including the page classes in the cucumber config

**Comment by vitalets** [comment]
Current approach is to create all POMs in CustomWorld. 
For example:
```ts
export class CustomWorld extends World {
  private dataexport?: DataExportPage;

  async getDataExportPage() {
    if (!this.dataexport) {
       this.dataexport = new DataExportPage(this.page);
       await this.dataexport.createDataExport();
    }
    return this.dataexport;
  }
}
```

And then in steps:
```ts
Then('I create Data Export', async function () {
   const dataexport = await this.world.getDataExport();
});
```

In the future the intention is to add full support of Playwright fixtures, see https://github.com/vitalets/playwright-bdd/issues/11.

Feel free to reopen this issue if needed.
