### ISSUE TITLE
The npx bddgen is not generating steps after adding the feature file

### ISSUE THREAD

**Issue by ChannakeshavaP** [vitalets/playwright-bdd#190]
Steps:
- Installed the required setup for playwright-bdd
- Added a sample feature file

Then ran the cli npx bddgen to generate test steps in terminal

**Comment by vitalets** [comment]
Hello! Could you please try with https://github.com/vitalets/playwright-bdd-example ?

**Comment by ChannakeshavaP** [comment]
Hello! Thanks for sharing repo.. now it's working.

![image](https://github.com/user-attachments/assets/c4107cf0-7bef-4dab-9b56-4a2dee6319c6)

**Comment by vitalets** [comment]
You are welcome :)

**Comment by ChannakeshavaP** [comment]
Even though I implemented the steps, I can see the yellow underline's in feature file. I hope these lines should go off when relative steps are implemented, right. How to fix this?

![image](https://github.com/user-attachments/assets/46bee979-c3bc-4f6d-8545-b448ced45a24)

![image](https://github.com/user-attachments/assets/26cbdba0-4754-4745-b510-1b074616191d)

Thanks you,
Channakeshava
