### ISSUE TITLE
Yellow reference line feature files

### ISSUE THREAD

**Issue by ChannakeshavaP** [vitalets/playwright-bdd#191]
Hi,

Even though I implemented the steps, I can see the yellow underline's in feature file. I hope these lines should go off when relative steps are implemented, right. How to fix this?

![image](https://github.com/user-attachments/assets/cda9c3e3-b66d-40f4-83ec-5db8ee0ea891)

![image](https://github.com/user-attachments/assets/1ecb2bd3-1967-4ed5-8c33-9cd4c6df399e)

Many thanks,
Channakeshava

**Comment by vitalets** [comment]
Hello! Yes, yellow underline should go off. 
Could you share which VSCode extension do you use for bdd?

**Comment by ChannakeshavaP** [comment]
Thanks for your response. I am sharing the VSCode bdd extensions with you..

![image](https://github.com/user-attachments/assets/0ed19318-d74f-4603-a8b0-653115408e74)

**Comment by vitalets** [comment]
There are both **Cucumber** and **Cucumber (Gherkin) Full Support** extensions that do not work properly together. Please try to disable one of them and re-check.

**Comment by ChannakeshavaP** [comment]
Yes! it works. Thanks a lot! and Many thanks.

**Comment by vitalets** [comment]
You are welcome!
