### ISSUE TITLE
Is it possible to generate cucumber-report.html using "playwright-bdd" 

### ISSUE THREAD

**Issue by ChannakeshavaP** [vitalets/playwright-bdd#192]
Can we generate cucumber-report html file in "playwright-bdd"

{
    "default": {
        "format": [
            "html:test-results/cucumber-report.html"
        ]
}
}

![image](https://github.com/user-attachments/assets/ae6bf286-3157-4fbe-8a17-e9751cf8a210)

Thanks
Channakeshava

**Comment by vitalets** [comment]
Yes. Please check out the correct syntax in docs: https://vitalets.github.io/playwright-bdd/#/reporters/cucumber?id=html

**Comment by ChannakeshavaP** [comment]
I followed the docs steps, still cucumber report html file is not generated after execution completed.

![image](https://github.com/user-attachments/assets/11a4ff36-c496-465b-a32e-9fc67102ee82)

Thanks.
