### ISSUE TITLE
What other reporters are supported by Playwright-bdd besides the Playwright HTML report?

### ISSUE THREAD

**Issue by ChannakeshavaP** [vitalets/playwright-bdd#193]
What other reporters are supported by Playwright-bdd besides the Playwright HTML report?

Thanks
Channakeshava

**Comment by vitalets** [comment]
All Playwright built-in reporters are supported. But they are not designed for BDD tests specifically.
That's why we also support Cucumber reporters, please have a look on the list of supported reporters [here](https://vitalets.github.io/playwright-bdd/#/reporters/cucumber).
