### ISSUE TITLE
I followed the docs steps, still cucumber report html file is not generated after execution completed.

### ISSUE THREAD

**Issue by ChannakeshavaP** [vitalets/playwright-bdd#195]
Yes. Please check out the correct syntax in docs: https://vitalets.github.io/playwright-bdd/#/reporters/cucumber?id=html

_Originally posted by @vitalets in https://github.com/vitalets/playwright-bdd/issues/192#issuecomment-2256272980_
            

![image](https://user-images.githubusercontent.com/162094409/353188325-3aef3c52-955d-421e-9f29-87cfa1e02ac0.png)

**Comment by vitalets** [comment]
Could you try to reproduce it on working example: https://github.com/vitalets/playwright-bdd-example

**Comment by vitalets** [comment]
Closing as there is no response from author.
Feel free to re-open if needed.
