### ISSUE TITLE
Bug: test not detected from steps, as expected

### ISSUE THREAD

**Issue by bmulholland** [vitalets/playwright-bdd#196]
**Given**
```
const testDir = defineBddConfig({
  features: "playwright/**/*.feature",
  steps: ["playwright/**/*.steps.ts", "playwright/support/**/*.ts"],
})
```

**When**

npx bddgen && npx playwright test

**Then**

Error: Can't guess test instance for: playwright/Test.feature. Did you include all fixture files in BDD configuration "steps"?

**Given**
```
const testDir = defineBddConfig({
  features: "playwright/**/*.feature",
  steps: ["playwright/**/*.steps.ts", "playwright/support/**/*.ts"],
  importTestFrom: "playwright/support/fixtures.ts", // ADDED ONLY THIS
})
```

**When**

npx bddgen && npx playwright test

**Then**

WARNING: Option "importTestFrom" in defineBddConfig() is not needed anymore. Try to remove it and include that file into "require" / "steps" pattern.

This warning can be disabled by setting in BDD config:
disableWarnings: { importTestFrom: true }
Feel free to report any bugs: https://github.com/vitalets/playwright-bdd/issues

**... runs test**

**Isolated demo**

**Environment**

```
Playwright-bdd environment info:

platform: darwin
node: v20.8.1
playwright-bdd: v7.1.0
@playwright/test: v1.45.3
node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module '@cucumber/cucumber/package.json'
```

**Comment by bmulholland** [comment]
Okay, the problem was that I didn't export `test`:
`const test = baseTest.extend({`

I had to do `export const test = baseTest.extend({`

This wasn't obvious from the error, though. Even when I used the manual `import` setting, the error was just `Test has unknown parameter "Given"` -- which really doesn't point me in the right direction.

So:
1. If `importTestFrom` is set, and step isn't exported, I recommend throwing an error that this is required.
2. If inferring from `steps`, then I guess `export step` is the way it's detecting the file, so a custom error can't be emitted. I suggest a note of "make sure your fixture exports test" in the error.

**Comment by vitalets** [comment]
These are very good points, thank you. Will definitely add them to error messages.

**Comment by vitalets** [comment]
Updated docs and error messages. Now the output is following:
```
Error: Can't guess test instance for: features/homepage.feature. Your tests use custom test instance, produced by base.extend(). Please check that:
 - fixtures file exports "test" variable
 - fixtures file is included in BDD configuration "steps" option
 If it does not help, try to set "importTestFrom" option manually.
```

For manual `importTestFrom` that does not export `test` variable:
```
Error: File "steps/fixtures.ts" pointed by "importTestFrom" should export "test" variable.
```
Released in 7.1.2.

**Comment by bmulholland** [comment]
Love it -- would have saved me a lot of time. Thanks!

**Comment by vitalets** [comment]
You are welcome :)
