### ISSUE TITLE
Question: No sure its me but version 7 is not giving me step definition snippet ? 

### ISSUE THREAD

**Issue by QAPranav** [vitalets/playwright-bdd#201]
I open a new project and add feature file and gave logic to playwright config under define config
const testDir = defineBddConfig({
  features: ['sample.feature']
});
And run npx bddgen but this is not giving me snippet, as it was giving before.

**Comment by vitalets** [comment]
I confirm the bug, will fix.

**Comment by vitalets** [comment]
Fixed in **v7.2.1**.
Could you re-check?

**Comment by QAPranav** [comment]
Thank you @vitalets  bug is fixed its working fine its retrieving step now, happy to close this issue
