### ISSUE TITLE
Question: How can I link the feature and step by press f12 ?

### ISSUE THREAD

**Issue by QAPranav** [vitalets/playwright-bdd#202]
This is nice to have a feature right now feature and steps are connected but if I have a long feature file, I would like to jump in steps file by click on feature file, eg. in Java Cucumber BDD when I click f12 on feature file that jump directly to the step which would be easy to debug I tired same with Playwright-bdd feature its says no reference found 
![Screenshot (1)](https://github.com/user-attachments/assets/08383468-c117-49d0-81b5-ee97400a9241)

**Comment by magarwal19** [comment]
You can use Cucumber (Gherkin) Full Support plugin in Vs code and add details in settings.json under .vscode folder..
with this you can directly navigate from feature file to step file

**Comment by vitalets** [comment]
Recently I've updated the docs on VSCode integration, there is sample settings for that as mentioned by @magarwal19 
https://vitalets.github.io/playwright-bdd/#/guides/ide-integration?id=cucumber-gherkin-full-support
