### ISSUE TITLE
Question: Is there any way to get code coverage using playwright BDD

### ISSUE THREAD

**Issue by magarwal19** [vitalets/playwright-bdd#203]
I was looking to get the code coverage report using playwright BDD

i found one package which is for mocha version of playwright
https://www.npmjs.com/package/playwright-test-coverage

want to check if we have something similar for playwright BDD or someone has implemented it yet.

**Comment by vitalets** [comment]
Please also have a look on previous discussion in #145.
In general, all coverage methods for Playwright should work for playwright-bdd as well.
There are some other solutions mentioned in the Playwright issue for out-of-box coverage support: https://github.com/microsoft/playwright/issues/9208
