### ISSUE TITLE
Question:how to navigate from feature file to step

### ISSUE THREAD

**Issue by sonesnema** [vitalets/playwright-bdd#204]
I am using this code on vs code ,as of bow when i click on particular step on feature file it is not navigating me to the step definition of that step ,can you tell me how can i do this.
Thanks in advance

**Comment by vitalets** [comment]
Do you have some Cucumber VSCode extensions installed? For example, [this one](https://vitalets.github.io/playwright-bdd/#/guides/ide-integration?id=cucumber-gherkin-full-support).
