### ISSUE TITLE
Feature: support gherkin localization

### ISSUE THREAD

**Issue by Grummfy** [vitalets/playwright-bdd#207]
**The problem**
When you want to use gherkin synthax in a other language than english it fails

**A solution**
Allow the parser (I know it's kind a lot of work) to play with the language like defined there https://cucumber.io/docs/gherkin/languages/

**Comment by vitalets** [comment]
Localization [should work](https://github.com/vitalets/playwright-bdd/tree/main/test/i18n). Could you provide an example code and error message?

**Comment by Grummfy** [comment]
Arf, I miss this example. Sorry.

It's working well. Thanks to show it.

I would suggest to add it in the documentation.

**Comment by vitalets** [comment]
Added to docs: https://vitalets.github.io/playwright-bdd/#/writing-features/i18n
And a config field `language` that was also missing: https://vitalets.github.io/playwright-bdd/#/configuration/options?id=language

thank you!
