### ISSUE TITLE
Question - Feature Syntax Highlight and Autocomplete in VS Code

### ISSUE THREAD

**Issue by NikkTod** [vitalets/playwright-bdd#21]
Hello, I am new to VS Code and BDD in JS/TS.

Do we have to use vs code extentions (and which one would you suggest), so that we see the syntax highlight and the steps autocompletion?

**Comment by bacarybruno** [comment]
Hello @NikkTod! I'm using [Cucumber (Gherkin) Full Support](https://marketplace.visualstudio.com/items?itemName=alexkrechik.cucumberautocomplete) plugin and it works so far. It provides syntax highlight and autocompletion.

Hope it helps.

**Comment by NikkTod** [comment]
Hi @bacarybruno, thanks for the suggestion.

I have tried it and it highlight correctlly, but I am not able to get the autocomplete working.

I am starting to type the first letter, but it is not showing me the already available step:

```
Feature: Playwright site

    Scenario: Check title
        Given I open url "https://playwright.dev"
        When I click link "Get started"
        Then I see in title "Playwright"

    Scenario: Check title 2
        Given I
```

**Comment by vitalets** [comment]
You are welcome!
