### ISSUE TITLE
Wrap each cucumber step in `test.step`

### ISSUE THREAD

**Issue by brzezinskimarcin** [vitalets/playwright-bdd#22]
Hello,

I would like to combine using playwright-bdd with [allure-playwright](https://github.com/allure-framework/allure-js/blob/master/packages/allure-playwright/README.md). The latter one allows to generate rich HTML reports of test runs. However, instead of showing details of execution with low-level playwright API steps, I would like it to show details in the form cucumber feature steps. 

Right now, if I set `details: false` in allure-playwright, nothing is shown.
![image](https://github.com/vitalets/playwright-bdd/assets/33814584/35ea9a44-6027-4438-b0a5-b702e1cbd415)

It's caused by the fact, that with `details: false` it only shows steps defined with [test.step](https://playwright.dev/docs/api/class-test#test-step) function.

Generated test file:

```js
/** Generated from: features\example.feature */
import { test } from "playwright-bdd";

test.describe("Playwright site", () => {

  test("Check title", async ({ Given, When, Then }) => {
    await Given("I open url \"https://playwright.dev\"");
    await When("I click link \"Get started\"");
    await Then("I see in title \"Playwright\"");
  });

});
```

And if I wrap each cucumber step with `test.step`

```js
/** Generated from: features\example.feature */
import { test } from "playwright-bdd";

test.describe("Playwright site", () => {

  test("Check title", async ({ Given, When, Then }) => {
    await test.step("Given I open url \"https://playwright.dev\"", () => Given("I open url \"https://playwright.dev\""));
    await test.step("When I click link \"Get started\"", () => When("I click link \"Get started\""));
    await test.step("Then I see in title \"Playwright\"", () => Then("I see in title \"Playwright\""));
  });

});
```
everything looks great in allure report:
![image](https://github.com/vitalets/playwright-bdd/assets/33814584/556f8d8f-7da4-4f8e-8ff6-de5782454ef3)

So my questions are:
1. Would it be possible to wrap each cucumber step with playwright's `test.step` during test generation?
2. If not, is there a possibility to hook into to test generation process and make slight modifications? I think this could be useful not only in this case, but also in different scenarios as well.

Actually, if I understand the source code correctly and if it makes sense to always define playwright step, then maybe it could be changed directly on fixture level, somwhere inside [src/run/invoke.ts:L6-L14](https://github.com/vitalets/playwright-bdd/blob/main/src/run/invoke.ts#L6-L14)

**Comment by vitalets** [comment]
I like this suggestion! Will check. 
Also it would be useful to show bdd steps in built-in `html` report, currently it shows the following:
<img width="80%" src="https://github.com/vitalets/playwright-bdd/assets/1473072/87d84777-b7b1-4977-9c6a-f52aba24d9c2"/>

Answering your questions:
1. Yes, we can wrap cucumber steps with playwright `test.step`. I'm just thinking, will it show correct sources when expanding steps in `html` report
2. Hooking into test-generation process is interesting idea. Could you create separate issue for that and share more thoughts and usecases?

Relates to #9

**Comment by vitalets** [comment]
Playwright's html report when wrapping with `test.step` in generated test files:

```js
test.describe("Playwright site", () => {

  test("Check title", async ({ Given, When, Then }) => {
    await test.step("Given I open url \"https://playwright.dev\"", () => Given("I open url \"https://playwright.dev\""));
    await test.step("When I click link \"Get started\"", () => When("I click link \"Get started\""));
    await test.step("Then I see in title \"Playwright\"", () => Then("I see in title \"Playwright\""));
  });

});
```
Report:
![image](https://github.com/vitalets/playwright-bdd/assets/1473072/27da00b5-d277-4052-b951-09000090b192)

**Comment by NikkTod** [comment]
Sorry to rush, but any chance to push/merge that one 🙏 

Will have a demo in a week and wanted to show some nice bdd reporting📈

**Comment by vitalets** [comment]
> Sorry to rush, but any chance to push/merge that one 🙏
> 
> Will have a demo in a week and wanted to show some nice bdd reporting📈

Yes, you will show it. Hoping to release v3 until end of this week.
