### ISSUE TITLE
Feature: AND support

### ISSUE THREAD

**Issue by J7mbo** [vitalets/playwright-bdd#220]
**The problem**
It would be very useful to have `AND` support in features instead of using multiple `Given`s or `When`s:

```
Given one thing
And another thing
```

instead of:

```
Given one thing
Given another thing
```

[cucumber reference](https://cucumber.io/docs/gherkin/reference/#and-but)

**Comment by J7mbo** [comment]
I just saw that we CAN use `AND` in the feature file itself. It's just that in the step file we have to use the `Step` function. Although it would be nice to have an `And()` call instead of a `Step` call just to reduce the cognitive overhead due to the difference, I'm closing as it's unlikely to make it in.

**Comment by vitalets** [comment]
Hi @J7mbo 
Yes, you can use AND in feature files and it is not required to define such steps with `Step` function. You can use any of `Given`, `When`, `Then`. I will highlight it in docs, that Cucumber treats all these functions as [aliases](https://cucumber.io/docs/gherkin/reference/#steps) and matches step only by pattern, not by keyword. Here are a few issues with some explanation: 
* https://github.com/cucumber/cucumber-js/issues/453
* https://github.com/cucumber/cucumber-js/issues/134

So thanks for raising that!

Concerning `And()` function - I think the same step can be often used with both full keyword and `AND / BUT`, step definition should not know about that context. Such functions were [deprecated](https://github.com/badeball/cypress-cucumber-preprocessor/issues/821) in Cucumber for Cypress, for the same reason.

While investigating this issue, I found that there were several discussions on enforcing strict keyword matching:
- https://github.com/cucumber/cucumber-js/issues/2043
- https://github.com/cucumber/common/issues/768
- https://github.com/cucumber/common/issues/1392

I think it's a good option to let users of playwright-bdd enable such mode in config. Will create a separate ticket for that.
