### ISSUE TITLE
Question: How to disable parallelism for a single feature file?

### ISSUE THREAD

**Issue by marek-siemieniuk-morawski** [vitalets/playwright-bdd#224]
Hey, I have a case when the scenarios in one of the feature files depend on the same external resource that I can't stub or mock. In a plain Playwright we can disable parallel mode for a single spec file https://playwright.dev/docs/test-parallel#parallelize-tests-in-a-single-file , but couldn't figure out whether it's possible with playwright-bdd as well. Is it?

**Comment by marek-siemieniuk-morawski** [comment]
False alarm, found it: https://vitalets.github.io/playwright-bdd/#/writing-features/special-tags?id=modexxx

Many thanks for your work, great job!

**Comment by vitalets** [comment]
You are welcome!
