### ISSUE TITLE
Feature:Extend keywords aliases

### ISSUE THREAD

**Issue by sergegraykiv** [vitalets/playwright-bdd#225]
**The problem**
If you have successive `Given`’s or `Then`’s, you could write:

Example: Multiple Givens
  `Given` one thing
  `Given` another thing
  `Given` yet another thing
  `When` I open my eyes
  `Then` I should see something
  `Then` I shouldn't see something else

**A solution**
Or, you could make the example more fluidly structured by replacing the successive `Given`’s or `Then`’s with `And`’s and `But`’s:

Example: Multiple Givens
  `Given` one thing
  `And` another thing
  `And` yet another thing
  `When` I open my eyes
  `Then` I should see something
  `But` I shouldn't see something else

**Comment by sergegraykiv** [comment]
@vitalets, the idea was taken from here: [Cucumber Docs](https://cucumber.io/docs/gherkin/reference/#and-but)

**Comment by vitalets** [comment]
`And / But` are supported. Did you try it with playwright-bdd?

**Comment by sergegraykiv** [comment]
@vitalets ah I see what you mean. So if I just put `And`/`But` in the feature file it won't throw an error. That is great. I was confused because it wasn't generating tests when I tried to add `And`/`But` in the `.steps` file. But it is ok, as long as it is possible to use these keywords inside a feature file.
