### ISSUE TITLE
Not able to run visual comparison tests - toHaveScreenshot() is not working

### ISSUE THREAD

**Issue by NikkTod** [vitalets/playwright-bdd#23]
Hello @vitalets I am trying to run a test that should compare screenshots. -> https://playwright.dev/docs/test-snapshots

When I use await expect(page).toHaveScreenshot(); and I do not have a master/golden file, this should generate for me a .png file in a specific directory 
![image](https://github.com/vitalets/playwright-bdd/assets/94455079/12fbe750-e3d7-432a-aa0a-e615aab1c0b8)

Unfortunatelly when I run the test this snapshot directory is not created automatically and get some internal error

![image](https://github.com/vitalets/playwright-bdd/assets/94455079/2b4cf7e6-3039-454a-975a-6d299f5c9f1d)

Could you please try to run some visual comparison test in your end to see it is working.

**Comment by NikkTod** [comment]
@vitalets after reading the playwright doc page and below line:
![image](https://github.com/vitalets/playwright-bdd/assets/94455079/1e889131-960c-4316-bc4b-3ffb56ff33f5)

 I have created manually in my project a snapshots folder and a dummy .png file in it under features.-gen\features (because this is where the test files are generated), so that it can work and playwright is able to check if such master file exists or create a new .png master file if it does not exist.
 
 So there are two problems:
 1. Usually Playwright creates that folder and master file automatically when you run the test if that folder and png file does not exist. It should give you this: "Error: A snapshot doesn't exist at example.spec.ts-snapshots/example-test-1-chromium-darwin.png, writing actual. "  -> So no need to manually create a anapshots folder and a dummy png file, next to your test file.
 
 
 2. If you run "npx bddgen" this will delete that snapshot folder and the files in it, so you need to create it again and again.

**Comment by vitalets** [comment]
Hi @NikkTod ! thanks for the case. 
`npx bddgen` should make more "clever" cleanup and remove only `js` files from `.features-gen` keeping all the other stuff.
I will update it.

**Comment by NikkTod** [comment]
@vitalets sounds perfect, waiting for the fix :)

**Comment by vitalets** [comment]
@NikkTod implemented in v3.0.1.
Please check out and let me know if there are any issues.
