### ISSUE TITLE
Question: Cucumber AutoComplete issue for steps with multiple variants.

### ISSUE THREAD

**Issue by gitToSantosh** [vitalets/playwright-bdd#230]
**Problem**
When I have steps like below:

```
Then I see link with text "How to install Playwright" should be displayed
Then I see link with text "How to install Playwright" should not be displayed
```

and step as below

```
Then( 'I see link with text {string} should( not) be displayed', async ( { page, $step }, text: string ) => {
	const negate = /should not/.test( $step.title );
	if ( negate ) {
		await expect( page.getByRole( 'link', { name: text } ) ).toBeHidden();
	} else {
		await expect( page.getByRole( 'link', { name: text } ) ).toBeVisible();
	}
} );
```

Cucumber autocomplete only identifies the negation step and fails to identify the positive step and shows as warning

Alternatively, when i use below step

```
Then( 'I see link with text {string} should(| not) be displayed', async ( { page, $step }, text: string ) => {
	const negate = /should not/.test( $step.title );
	if ( negate ) {
		await expect( page.getByRole( 'link', { name: text } ) ).toBeHidden();
	} else {
		await expect( page.getByRole( 'link', { name: text } ) ).toBeVisible();
	}
} );
```

Cucumber autocomplete identifies both positive and negative steps, but here bddgen fails to identify one of the steps

Please provide some solutions

**Comment by vitalets** [comment]
It's a bug in CucumberAutocomplete: https://github.com/alexkrechik/VSCucumberAutoComplete/issues/292
I've tried with [official Cucumber extension](https://marketplace.visualstudio.com/items?itemName=CucumberOpen.cucumber-official), it handles optional part correctly and navigates to the definition from both steps.

Lets keep this issue open to track the progress. Hopefully, CucumberAutocomplete will fix it.

**Comment by vitalets** [comment]
You are welcome!
