### ISSUE TITLE
Feature: Can we generate multiple test.describe() in feature-gen for a specific feature file

### ISSUE THREAD

**Issue by shashankkvs309668** [vitalets/playwright-bdd#232]
**The problem**
i wanted to group few scenarios like sets of test.describe() from the feature file so that it can support running scenarios in parallel workers. Currently if i have 20 in one feature file and run in parallel mode it is taking one worker for all 20 scenarios which will delay the execution

**A solution**
Need support to generate multiple test.describe() in feature-gen for a specific feature file

**Comment by vitalets** [comment]
There are some options:
- use [`Rule`](https://cucumber.io/docs/gherkin/reference/#rule) inside feature file, each rule will be wrapped into own test.describe
- set [`fullyParallel`](https://playwright.dev/docs/api/class-testconfig#test-config-fully-parallel) to true. In that case 20 scenarios from one feature will be shared across all available workers. Does it solve your case?

**Comment by shashankkvs309668** [comment]
Hey I missed that option. Thanks for clarifying it. This makes sense

**Comment by shashankkvs309668** [comment]
Working good as per the comments
