### ISSUE TITLE
Feature: Is there a way to integrate with @chromatic-com/playwright

### ISSUE THREAD

**Issue by fschwalm** [vitalets/playwright-bdd#235]
**The problem**

I am trying to use @chromatic-com/playwright, but I can't pass a test from @chromatic-com/playwright to the createBdd function.
Is there a way to achieve this?

**A solution**

```
import { test as chromaticTest } from '@chromatic-com/playwright'
import { test as base, createBdd } from 'playwright-bdd'
const FIXTURES = {
  explorepage: 'http://localhost:3000/explore',
} as const

export const test = base.extend<typeof FIXTURES>(FIXTURES)

export const { Given, When, Then } = createBdd(chromaticTest)
```

Thank you!!

**Comment by vitalets** [comment]
Could you try [mergeTests](https://playwright.dev/docs/release-notes#merge-test-fixtures) to get composed test instance:
```ts
import { mergeTests } from '@playwright/test';
// ...

export const test = mergeTests(chromaticTest, base).extend<typeof FIXTURES>(FIXTURES)
```

**Comment by fschwalm** [comment]
It worked like a charm.

Thank you so much!!!

**Comment by jonniebigodes** [comment]
I stumbled upon this issue while testing this package, and I was able to get it running as well. However, could you provide guidance on some items related to Chromatic and this package? Specifically, how to configure some of the configuration options for Chromatic listed [here](https://www.chromatic.com/docs/playwright/configure/) and, if it's possible, set up [targeted snapshots](https://www.chromatic.com/docs/playwright/targeted-snapshots/) at a specific point in the test.

@vitalets If you provide any guidance on this, I would appreciate it.

Thanks for maintaining this package, it's been great to work with.

Hope you have a great day!

**Comment by vitalets** [comment]
> Specifically, how to setup some of the configuration options for Chromatic listed [here](https://www.chromatic.com/docs/playwright/configure/) within the tests themselves

If options should be in `playwright.config.ts`, just put them there.
If options are required for a particular test, then follow these steps:
For example, you need to disable auto snapshots only for HomePage feature:
```js
test.describe("HomePage", () => {
  // 👇 Overrides the option in the test.
  test.use({ disableAutoSnapshot: true });

  test("Loads the page with auto snapshotting disabled", async ({ page }) => {
    await page.goto("/");
  });
});
```
In Playwright-BDD you can't manually write into spec files (as they are generated from feature files). But there are several ways to achieve it. You can add a tag `@noSnapshots` to the HomePage feature:
```feature
@noSnapshots
Feature: HomePage
```
and then overwrite `disableAutoSnapshot` fixture depending on tags:
```js
export const test = mergeTests(chromaticTest, base).extend({
  disableAutoSnapshot: async ({ $tags }, use) => {
    await use($tags.includes('@noSnapshots'));
  }
});
```

> if it's possible, set up [targeted snapshots](https://www.chromatic.com/docs/playwright/targeted-snapshots/) at a specific point in the test.

Should be possible. The only difference is the test info is available in step definitions as a `$testInfo` fixture:
```ts
import { takeSnapshot } from "@chromatic-com/playwright";

Given('a step', async ({ page, $testInfo }) => {
   await takeSnapshot(page, $testInfo); 
});
```

**Comment by jonniebigodes** [comment]
@vitalets appreciate the follow-up. Indeed, it worked; I was able to set up the options and targeted snapshots without any issues 🙏

**Comment by rasinbo** [comment]
Right now im using that:
import { mergeTests } from '@playwright/test';
// ...

export const test = mergeTests(chromaticTest, base).extend<typeof FIXTURES>(FIXTURES)

It seems to work, but when I try to send my results to Chromatic (npx chromatic --palywright --project-token=...), it fails at the "Building your test suite" step. I don't know why, but it doesn't generate the test results in "chromatic-archives" as usual, and I just don't know why. Can someone help me?

![Image](https://github.com/user-attachments/assets/eab43b20-fdb7-45b6-8915-a426b0f1dbb2)
