### ISSUE TITLE
Question: On the new version 7, is it still supported to have context with World?

### ISSUE THREAD

**Issue by zmimi-lael** [vitalets/playwright-bdd#236]
I do have this before and able to utilize the CustomWorld that I have created.

- world.js
```const { setWorldConstructor } = require('playwright-bdd');
const { BddWorld } = require('playwright-bdd');

class CustomWorld extends BddWorld {
  constructor(options, page) {
    super(options);
    this._context = {};
  }


}

setWorldConstructor(CustomWorld);
```

- Then in my steps, I can set and share the `_context` values  `this._context = {};`

```
When(
  "a valid search request",
  async function ({ page, request }) {
    const tests = new SearchText(page);
    this._context["order_search_response"] =
      await tests.searchAPI.callSearchRequest(
        request,
        this._context["valid_token"],
      );
  }
);

Then(
  "the API  returned all  the search criteria",
  async function ({ page }) {
     const tests = new SearchText(page);

    tests.cartSearchAsserts.assertValidResponseWithSchema(
      this._context["order_search_response"]
    );
  }
);
```

With the use of context, for each worker that I used, they are unique during run time.

**Comment by vitalets** [comment]
I've noticed that you use mixed steps style: rely on `this` and pass fixtures as a first argument to step functions. In general, it's better to follow pure Playwright-style or pure Cucumber-style steps. There are more details here https://github.com/vitalets/playwright-bdd/issues/208#issuecomment-2275374050.

If using playwright-style, you can share `context` between steps by defining `_context` as a fixture:
```js
import { test as base } from 'playwright-bdd';

export const test = base.extend({
  _context: async ({}, use) => {
    await use({}); // <- _context initialized with empty object
  }
});
```
Then in steps:
```js
When(
  "a valid search request",
  async function ({ page, request, _context }) { // _context passed as argument
    const tests = new SearchText(page);
    _context["order_search_response"] =
      await tests.searchAPI.callSearchRequest(
        request,
        _context["valid_token"],
      );
  }
);
```

Or, you can set up full world via fixture, check out [this guide](https://vitalets.github.io/playwright-bdd/#/writing-steps/cucumber-style).

Alternatively, you can use existing approach. Playwright-bdd provides a fallback for mixed steps style: it always initializes `this` as empty object, so you can attach `_context` to it:
```js
When(
  "a valid search request",
  async function ({ page, request }) {
    const tests = new SearchText(page);
    this._context = this._context || {}; // ensure this._context is initialized, because by default `this` is empty object
    this._context["order_search_response"] =
      await tests.searchAPI.callSearchRequest(
        request,
        this._context["valid_token"],
      );
  }
);
```
In that case, you don't need to define CustomWorld at all.

**Comment by zmimi-lael** [comment]
Thank you @vitalets , I will try all these options. I am keen to have one entry, and initialize this._context = this._context || {}; this once.
