### ISSUE TITLE
Question:Re useable of step defination method

### ISSUE THREAD

**Issue by prasadroks** [vitalets/playwright-bdd#237]
Is there any way where we can use the already defined step defination method in any other step defination, like the same way we can do in cucumber java bdd framework.

**cucumber java bdd example:**
![image](https://github.com/user-attachments/assets/f61d978a-5895-48c2-95f8-713818b9917f)

There are 2 different steps but I am able to use that step defination in another step defination. 
Can i achieve this in playwright-bdd, without creating any seperate function.

**Comment by gitToSantosh** [comment]
You can save the entire step into a const and export it and then call the const into the step where you want to re-use

```
const GO_TO_PLAYWRIGHT_HOME = Given( 'I am on Playwright home page', async ( { commonPage } ) => {
	await commonPage.navigateToUrl( 'https://playwright.dev' );
} );

When( 'I click link {string}', async ( { commonPage }, linkname: string ) => {
	await GO_TO_PLAYWRIGHT_HOME( { commonPage } );
	await commonPage.clickOnLink( linkname );
} );
```

**Comment by prasadroks** [comment]
> You can save the entire step into a const and export it and then call the const into the step where you want to re-use
> 
> ```
> const GO_TO_PLAYWRIGHT_HOME = Given( 'I am on Playwright home page', async ( { commonPage } ) => {
> 	await commonPage.navigateToUrl( 'https://playwright.dev' );
> } );
> 
> When( 'I click link {string}', async ( { commonPage }, linkname: string ) => {
> 	await GO_TO_PLAYWRIGHT_HOME( { commonPage } );
> 	await commonPage.clickOnLink( linkname );
> } );
> ```




> You can save the entire step into a const and export it and then call the const into the step where you want to re-use
> 
> ```
> const GO_TO_PLAYWRIGHT_HOME = Given( 'I am on Playwright home page', async ( { commonPage } ) => {
> 	await commonPage.navigateToUrl( 'https://playwright.dev' );
> } );
> 
> When( 'I click link {string}', async ( { commonPage }, linkname: string ) => {
> 	await GO_TO_PLAYWRIGHT_HOME( { commonPage } );
> 	await commonPage.clickOnLink( linkname );
> } );
> ```

test

> You can save the entire step into a const and export it and then call the const into the step where you want to re-use
> 
> ```
> const GO_TO_PLAYWRIGHT_HOME = Given( 'I am on Playwright home page', async ( { commonPage } ) => {
> 	await commonPage.navigateToUrl( 'https://playwright.dev' );
> } );
> 
> When( 'I click link {string}', async ( { commonPage }, linkname: string ) => {
> 	await GO_TO_PLAYWRIGHT_HOME( { commonPage } );
> 	await commonPage.clickOnLink( linkname );
> } );
> ```

user initiates a login flow - only clicks on login button
user initiates a login flow with valid username and password - only enters username  the username and password
user provides the verification code
user logs in to myQb - complete login process 


But here you have created a method in the commonPage, which was not my question, i am aware of this condition and also if i have to use that method the straight forward way would be directly calling it.

Assume I have some steps defined in 
Given( 'Open {string} in browser', async ( { page }, url:string ) => {
	await page.goto(url);
        await page.perform_display_page_name();
 } );

I have another method which would be doing the same
Given( 'navigate to {string}', async ( { page }, url:string ) => {
	Here i want to use the same steps that have been given in above methods, so instead of rewriting the same again i want to make of reusability just by calling that method and passing url as an argument
 } );

**Comment by gitToSantosh** [comment]
> > You can save the entire step into a const and export it and then call the const into the step where you want to re-use
> > ```
> > const GO_TO_PLAYWRIGHT_HOME = Given( 'I am on Playwright home page', async ( { commonPage } ) => {
> > 	await commonPage.navigateToUrl( 'https://playwright.dev' );
> > } );
> > 
> > When( 'I click link {string}', async ( { commonPage }, linkname: string ) => {
> > 	await GO_TO_PLAYWRIGHT_HOME( { commonPage } );
> > 	await commonPage.clickOnLink( linkname );
> > } );
> > ```
> 
> > You can save the entire step into a const and export it and then call the const into the step where you want to re-use
> > ```
> > const GO_TO_PLAYWRIGHT_HOME = Given( 'I am on Playwright home page', async ( { commonPage } ) => {
> > 	await commonPage.navigateToUrl( 'https://playwright.dev' );
> > } );
> > 
> > When( 'I click link {string}', async ( { commonPage }, linkname: string ) => {
> > 	await GO_TO_PLAYWRIGHT_HOME( { commonPage } );
> > 	await commonPage.clickOnLink( linkname );
> > } );
> > ```
> 
> test
> 
> > You can save the entire step into a const and export it and then call the const into the step where you want to re-use
> > ```
> > const GO_TO_PLAYWRIGHT_HOME = Given( 'I am on Playwright home page', async ( { commonPage } ) => {
> > 	await commonPage.navigateToUrl( 'https://playwright.dev' );
> > } );
> > 
> > When( 'I click link {string}', async ( { commonPage }, linkname: string ) => {
> > 	await GO_TO_PLAYWRIGHT_HOME( { commonPage } );
> > 	await commonPage.clickOnLink( linkname );
> > } );
> > ```
> 
> 30 Oct 2024 But here you have created a method in the commonPage, which was not my question, i am aware of this condition and also if i have to use that method the straight forward way would be directly calling it.
> 
> Assume I have some steps defined in Given( 'Open {string} in browser', async ( { page }, url:string ) => { await page.goto(url); await page.perform_display_page_name(); } );
> 
> I have another method which would be doing the same Given( 'navigate to {string}', async ( { page }, url:string ) => { Here i want to use the same steps that have been given in above methods, so instead of rewriting the same again i want to make of reusability just by calling that method and passing url as an argument } );


GO_TO_PLAYWRIGHT_HOME  is NOT a method in commonPage. Your Steps would look like this:

```
export const OPEN_URL = Given( 'Open {string} in browser', async ( { page }, url:string ) => {
await page.goto(url);
await page.perform_display_page_name();
} );

\\ I have another method which would be doing the same
Given( 'navigate to {string}', async ( { page }, url:string ) => {
\\Here i want to use the same steps that have been given in above methods, so instead of rewriting the same again i want to \\make of reusability just by calling that method and passing url as an argument
\\ call the const, pass the fixtures first then the remaining args
await OPEN_URL({page}, url);
} );
```

**Comment by vitalets** [comment]
> Is there any way where we can use the already defined step defination method in any other step defination, like the same way we can do in cucumber java bdd framework.
> 
> **cucumber java bdd example:** 
![image](https://private-user-images.githubusercontent.com/179507639/381081635-f61d978a-5895-48c2-95f8-713818b9917f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNDQwNTQsIm5iZiI6MTczNDM0Mzc1NCwicGF0aCI6Ii8xNzk1MDc2MzkvMzgxMDgxNjM1LWY2MWQ5NzhhLTU4OTUtNDhjMi05NWY4LTcxMzgxOGI5OTE3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQxMDA5MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGRiYmI4MGFhMzE4OTVjYmVmNmYzMjkwNWFkYjQ3MWFkYWUyMjY5YzRhZjQ1ZWIxYjhjMTE0YzhkMjg0NDc1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.pR3dt8Uv9nNGcO_cHyzPwpTpEgZBngmwDU6gqK3dgWE)
> 
> There are 2 different steps but I am able to use that step defination in another step defination. Can i achieve this in playwright-bdd, without creating any seperate function.

With decorator steps, you can do exactly the same in Playwright-BDD:
```ts
export @Fixture('todoPage') class TodoPage {
  constructor(public page: Page) { }

  @When('display a message {string}')
  async display(message: string) {
    // ...
  }

  @When('user should be able to display a message {string}')
  async user_display(message: string) {
    await this.display(message);
  }
