### ISSUE TITLE
Question: Playwright html report does not show steps which are skipped

### ISSUE THREAD

**Issue by gitToSantosh** [vitalets/playwright-bdd#238]
With Playwright html report, When a test fails, I am unable to see the steps which got skipped due to failure. 

For example, here the steps failed at background/hooks but the actual test body/steps are completely missing, but they do appear in cucumber html report

![image](https://github.com/user-attachments/assets/16fd5bab-1461-4caf-ad1f-2dab261987c3)

**Comment by vitalets** [comment]
> With Playwright html report, When a test fails, I am unable to see the steps which got skipped due to failure.

Could you check the behavior of Playwright itself in such case? I mean run pure playwright test, that has some steps and fails due to beforeEach. I suppose it does not show any steps in html reporter as well.
