### ISSUE TITLE
Support UI Mode

### ISSUE THREAD

**Issue by LarsFischer97** [vitalets/playwright-bdd#24]
Maybe I am wrong, but for me Playwright UI Mode is not finding my tests when using playwright-bdd.
https://playwright.dev/docs/test-ui-mode

I try to run it by using: `npx bddgen && npx playwright test --ui`

Supporting UI Mode would bring a lot of functions and productivity in my opinion.

Let me know what you think or if i initialize it wrong.

**Comment by vitalets** [comment]
It should work. Are you getting this error?
`When using several calls of defineBddConfig() please manually provide different "outputDir" option`

**Comment by LarsFischer97** [comment]
Yes, i get that error.

**Comment by LarsFischer97** [comment]
But i do not know what to do with this option. I filled it with an empty folder, but the error stays the same.

**Comment by NikkTod** [comment]
@vitalets , @LarsFischer97 

Yep I can also reproduce, same error on my side

**Comment by vitalets** [comment]
Releasing today 3.0.2 with fixed --ui mode.
Thanks for the feedback, will also improve docs.

**Comment by vitalets** [comment]
@LarsFischer97 @NikkTod Could you pls re-check on just released v3.0.2?

**Comment by NikkTod** [comment]
I am just running `playwright test --ui` and Ui mode is showning without errors

**Comment by NikkTod** [comment]
@LarsFischer97 are you on the v3.0.2 in the package.json file for the 'playwright-bdd'

**Comment by LarsFischer97** [comment]
Yes i was on v3.0.2. but i messed around with the generator as i had some trouble on windows with the parsing. Maybe i knocked over some things there. I just did a clean install and everything worked fine.
