### ISSUE TITLE
Question: Can I combine BDD with classic playwright tests? (e.g. reuse setup for api testing)

### ISSUE THREAD

**Issue by LarsFischer97** [vitalets/playwright-bdd#242]
I really like this playwright-bdd approach and it scales so good with frontend e2e tests.

I was wondering, if it is possible to also write "normal" playwright tests alongside the bdd tests?

We want to write frontend e2e tests in feature files but also want to use the [api testing functionality](https://playwright.dev/docs/api-testing) from playwright. We do not think that this suites gherkin well. Still it would be nice to reuse the config and setup from the playwright-bdd test suite.

At the moment we struggle to set the directory for the tests that dont need to run throught bdd conversion.

--- More context ---

playwright.config.ts
```
...
projects: [
        {
            name: "API",
        },
        {
            name: "Chrome",
            use: {
                ...devices["Desktop Chrome"]
            }
        },
]
...
```

For example project "Chrome" would run all tests from feature files and "API" would run classic playwright api tests. But both tests can reuse the overall playwright.config.ts settings.

**Comment by vitalets** [comment]
Hey @LarsFischer97 
Your approach is correct, passing `testDir` to each project should work:
```js
export default defineConfig({
  projects: [
        {
            name: "API",
            testDir: './src/api'
        },
        {
            name: "Chrome",
            testDir: defineBddConfig({ ... }),
        },
 ]
});
```
Could you try to reproduce the issue on https://github.com/vitalets/playwright-bdd-example ?

**Comment by LarsFischer97** [comment]
I found the mistake.
The api test folder that contained classic playwright tests was within the folder that was allocated for the bdd test generation.

defineBddConfig searched for everything in ./scr and it struggles if it finds normal tests

```
const testDir = defineBddConfig({
    features: "src/features/*.feature",
    steps: "src/**/*.ts", // <-- Same folder
    outputDir: "generated",
});
```

```
projects: [
        {
            name: "API",
            testDir: './src/api' // <-- Same folder
        },
        {
            name: "Chrome",
            use: {
                ...devices["Desktop Chrome"]
            }
        },
]
```

**Comment by vitalets** [comment]
That's good point 👍
Will add to docs.
