### ISSUE TITLE
Feature: preserve arg types in call-step-from-step functions

### ISSUE THREAD

**Issue by jcamden** [vitalets/playwright-bdd#243]
Hey, thanks for this awesome package. It has been a game-changer for our testing strategy. Anyway,

**The problem**
We regularly [call step from step](https://vitalets.github.io/playwright-bdd/#/writing-steps/playwright-style?id=call-step-from-step). However, we recently had a type error slip through on account of the fact that the keyword functions (from createBDD) do not preserve the arg types of the function which they receive. For instance, here is the type for the example from the docs:

![Screenshot 2024-11-13 at 9 44 03 AM](https://github.com/user-attachments/assets/6ad78f98-9270-44a3-8fd1-105ee5072a2b)

We are hoping that the `...args: any[]` could be improved.

**A solution**
We can work around it by extracting that function out to a separate assignment, but this is not ideal. There may also be better ways to work around it; but I thought I'd inquire about whether it might be possible to preserve those types from playwright-bdd's side.  Any chance you'd check it out? We really appreciate you!

**Comment by vitalets** [comment]
Hey @jcamden 
Yes, it definitely should keep step function signature. I will take a look.

**Comment by vitalets** [comment]
Released in Playwright-BDD v8.
Please, check on your side and re-open in case of any problems.
