### ISSUE TITLE
Question: [before/After]Step Hook or Workaround

### ISSUE THREAD

**Issue by viktor-silakov** [vitalets/playwright-bdd#247]
I need to log the start and end of a step, providing information about the step (name or pattern), to a remote server using the WebSocket API. How can I achieve this using Playwright BDD?

**Comment by vitalets** [comment]
I think custom reporter can do that:
```ts
class MyReporter implements Reporter {
  onStepBegin(test, result, step) {
    // report step start
  }

  onStepEnd(test, result, step) {
    // report step end
  }
}
```
I thought about adding beforeStep/afterStep hooks like in CucumberJS. But decided to check how it goes with existing options, without extra hooks.
Could you try with the reporter - does it provide enough data for your task?

**Comment by viktor-silakov** [comment]
@vitalets thank you for a workaround, will use it.
