### ISSUE TITLE
Question:How do we get file downloaded path

### ISSUE THREAD

**Issue by prasadroks** [vitalets/playwright-bdd#248]
Hello Team,
I am trying to find the file which is downloaded from browser using a download link. how do i get that file and save it in some other folder?
or
How do i set a path to download a file to particular folder present under src.

File type is .csv

**Comment by vitalets** [comment]
Hello!

You can use `download.saveAs()` with custom location. Please check out an example [here](https://playwright.dev/docs/downloads).

This is not something related to playwright-bdd, you can follow common approach for Playwright.
