### ISSUE TITLE
Docs to be updated in section "Custom fixtures"

### ISSUE THREAD

**Issue by NikkTod** [vitalets/playwright-bdd#25]
Hi @vitalets,

I spotted one thing under the "Custom fixtures" document section:

![image](https://github.com/vitalets/playwright-bdd/assets/94455079/87182db1-e2f4-4a05-ab5f-8e96541a2749)

Correct me if I am wroing, but I think it shoult be `base.extend `

**Comment by vitalets** [comment]
Good catch! Thank you

**Comment by vitalets** [comment]
Corrected in 3.0.2
