### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by isherkhan** [vitalets/playwright-bdd#254]
Hi

Iam trying to implement playwright-bdd in to an existing framework which was using playwright and cucumber as the test runner using commons as the module.Iam seeing compilation errors when tried to run bdd gen command.Do we have any examples or sample frameworks running on commonjs?

**Comment by vitalets** [comment]
Hi! Yes, here is an example of using playwright-bdd with common js: https://github.com/vitalets/playwright-bdd-example

**Comment by isherkhan** [comment]
> Hi! Yes, here is an example of using playwright-bdd with common js: https://github.com/vitalets/playwright-bdd-example

Thanks for quick reply. Also have another question do playwright-bdd has the support for other cucumber features like generation of the rerun files and the json report generator.

**Comment by vitalets** [comment]
> Also have another question do playwright-bdd has the support for other cucumber features like generation of the rerun files and the json report generator.

Yes for both:
- you can rerun last failed tests with Playwright's [--last-failed](https://playwright.dev/docs/running-tests#run-last-failed-tests) option:
   ```
   npx bddgen && npx playwright test --last-failed
   ```
- Cucumber JSON reporter [is supported](https://vitalets.github.io/playwright-bdd/#/reporters/cucumber?id=json).

**Comment by isherkhan** [comment]
> > Also have another question do playwright-bdd has the support for other cucumber features like generation of the rerun files and the json report generator.
> 
> 
> 
> Yes for both:
> 
> - you can rerun last failed tests with Playwright's [--last-failed](https://playwright.dev/docs/running-tests#run-last-failed-tests) option:
> 
>    ```
> 
>    npx bddgen && npx playwright test --last-failed
> 
>    ```
> 
> - Cucumber JSON reporter [is supported](https://vitalets.github.io/playwright-bdd/#/reporters/cucumber?id=json).

Thanks for the quick reply.

One more question i have is. Do we have an equivalent of "scenario.result.status, scenario.pickle.name"

This is really helping me 

Thanks in Advance

**Comment by vitalets** [comment]
> One more question i have is. Do we have an equivalent of "scenario.result.status, scenario.pickle.name"

Cucumber scenario = Playwright test.
So, `scenario.result.status` is actually [test status](https://playwright.dev/docs/api/class-testinfo#test-info-status) and `scenario.pickle.name` = `scenario.name` = [test.title](https://playwright.dev/docs/api/class-testinfo#test-info-title).
