### ISSUE TITLE
Feature: support for automatically generating `steps` from `feature` files in accordance with the package format.

### ISSUE THREAD

**Issue by fufuShih** [vitalets/playwright-bdd#256]
Hi, thanks for providing such a practical tool! It’s been working very smoothly so far.

could we enable the direct generation of a `.steps.ts` template from a `.feature` file, formatted according to this tool’s requirements?

The current workflow is:

1. Write the feature file
2. Manually create or use another tool to generate steps (and then adjust the format)
3. Finally, use this tool to generate tests

Although using other tools to generate steps isn’t too complicated, it still requires extra formatting steps.

If we could directly extract all the Given, When, and Then `steps` from the feature file and immediately produce an empty `steps` template file that fits the requirements of this tool, 

it would greatly simplify the process and improve convenience. I hope the development team will consider adding this feature. Thank you!

**Comment by vitalets** [comment]
Hi @fufuShih 

Isn't [snippets](https://vitalets.github.io/playwright-bdd/#/writing-steps/snippets) what you are looking for?

**Comment by fufuShih** [comment]
Thank you for your reply,

Yes, this is exactly what I was looking for.
