### ISSUE TITLE
Question: How automatically run Bddgen after updating feature file on VS code ? at the moment after every change we have execute bddgen 

### ISSUE THREAD

**Issue by maheshjoshiFMG** [vitalets/playwright-bdd#258]

**Comment by vitalets** [comment]
Please, try [watch mode](https://vitalets.github.io/playwright-bdd/#/guides/watch-mode).

**Comment by vitalets** [comment]
> The linked watch mode guide no longer exists. How do we achieve this now?

Updated [the link](https://vitalets.github.io/playwright-bdd/#/guides/ui-mode) in my previous message. Thank you!
