### ISSUE TITLE
Wrong slash in the generated import statement

### ISSUE THREAD

**Issue by NikkTod** [vitalets/playwright-bdd#26]
Hi @vitalets,
when I am generating the test files, the import statements are having the wrong slash, see below example:

![image](https://github.com/vitalets/playwright-bdd/assets/94455079/f3a24da2-2cb6-473c-b1b7-2635962e8a1e)

**Comment by vitalets** [comment]
Are you on Windows?

**Comment by NikkTod** [comment]
Yes, on Windows :)

**Comment by vitalets** [comment]
Btw, how do you define `importTestFrom` option in config?

**Comment by NikkTod** [comment]
![image](https://github.com/vitalets/playwright-bdd/assets/94455079/19aa7856-72ed-4770-9f6a-7c1f7aa97482)
