### ISSUE TITLE
Example for processing tabular data defined in feature file

### ISSUE THREAD

**Issue by jae-pea2** [vitalets/playwright-bdd#37]
Would it be possible to extend the current example to show how tabular data would be handled in the step definitions?

For instance, the step definition might be something like:
   When('I create an entity with properties', async ({ page }, data: DataTable) => { /* do stuff */ });

**Comment by vitalets** [comment]
Good point. Added [example](https://github.com/vitalets/playwright-bdd#using-datatables) to readme.
