### ISSUE TITLE
Unable to resolve signature of class decorator when called as an expression

### ISSUE THREAD

**Issue by NikkTod** [vitalets/playwright-bdd#41]
Hi @vitalets,

could you please help me set up the decotator tests. I am having an error on the export Fixture within the pages files:

![image](https://github.com/vitalets/playwright-bdd/assets/94455079/7cb55b1f-55d7-43e9-90b5-008ea385e1b0)

I have checked in google and tried out a lot of things, but still that error exists, currentlly I am using workplace version 5.1.6 

![image](https://github.com/vitalets/playwright-bdd/assets/94455079/3ba80293-1981-49f6-82ae-a41b0cf38d08)

But even on the vs code version is still the same error. 

Details: 
tsconfig
![image](https://github.com/vitalets/playwright-bdd/assets/94455079/73923a44-41e2-4adc-aab3-e03f3b341764)

**Comment by vitalets** [comment]
Hi @NikkTod ! Looks like you did everything right..
I've reproduced the behavior - when switching to typescript 4 the same error occurs. But when I switch back to ts 5 - it disappears.
Did you try to reload developer window? cmd + shift + p -> "reload..."
Also maybe just restart vscode / laptop =)

One more thing -> try to add to `.vscode/settings.json` this line (although by screenshots you are already using workspace ts, maybe it help):
```
{
  ...
  "typescript.tsdk": "node_modules/typescript/lib"
}
```

**Comment by NikkTod** [comment]
Hi @vitalets , thank you very much for the suggestion, somehow it worked I have made several things, but could not follow, which did the trick.

capitlize the "target": "ES2021"
removed experimentalDecorators:true
setting up "typescript.tsdk": "node_modules/typescript/lib"

All is good now :)

**Comment by vitalets** [comment]
Super!
I think this one did -> removed experimentalDecorators:true
