### ISSUE TITLE
Question: How to pass BaseUrl on decorator type tests

### ISSUE THREAD

**Issue by NikkTod** [vitalets/playwright-bdd#42]
Hi @vitalets,

just wondering if you could give me an example how to pass the baseURL, so that I will be able to use it inside the pages methods.

I was able to pass browser, request, etc., but I could not figure out the BaseUrl.

**Comment by vitalets** [comment]
@NikkTod could you provide a code sample?

By default `baseURL` is picked up from config as well as in regular Playwright tests:
```ts
export default defineConfig({
  use: {
    // Base URL to use in actions like `await page.goto('/')`.
    baseURL: 'http://127.0.0.1:3000',
  },
});
```
If you need to access `baseURL` itself, you can pass `baseURL` fixture to POM similar to passing `page`:
```ts
class TodoPage {
  constructor(public page: Page, public baseURL?: string) {
   // ...
  }

export const test = base.extend<{ todoPage: TodoPage }>({
  todoPage: async ({ page, baseURL }, use) => {
    await use(new TodoPage(page, baseURL));
  },
});
```

**Comment by NikkTod** [comment]
Great, thanks @vitalets this is exaclly what I needed, sorry I am new to JavaScript/TypeScript world.

**Comment by vitalets** [comment]
Never mind :)
