### ISSUE TITLE
Snapshot folder and file not being created when we use ToHaveScreenshot()

### ISSUE THREAD

**Issue by NikkTod** [vitalets/playwright-bdd#43]
Hi @vitalets,

because of the change (issue 40, concerning the Simplify generated directories structure) I had to delete the features-gen folder. 

Now after I run the 'npx bddgen' all features are being re-generated with the new structure and all is good with them.

The problem comes when we want to use visual comparison tests. 
So after I clean I do not have anymore the snapshots folder and the snapshots inside. 

Just for info, when using clean playwright that snapshot folder with the snapshot file will be automatically generated for me (cause they do not exist) when I use the ToHaveScreenshot() method. 

Unfortunatelly with playwright-bdd when the test come to the method ToHaveScreenshot it hangs and after a while test fails. 
The message I see is -> Internal error: worker process exited unexpectedlly (code=134, signal=null)

Last time I think I fix that when I manually created snapshot folder with a file inside, will try to do the same, but I was wondering if you can help with real fix, so that we do not need to create snapshot folder manually.

**Comment by vitalets** [comment]
Hi @NikkTod 
I've tried to reproduce this behavior, but can not catch yet. I've added screenshot comparison to [playwright-bdd-example](https://github.com/vitalets/playwright-bdd-example/blob/main/steps/TodoPage.ts#L46). Could clone it, remove `.features-gen` directory and run `npm t`?

**Comment by vitalets** [comment]
@NikkTod I've recorded a video with my steps - screenshots dir is still successfully created even for extension runs:
https://youtu.be/JZ7OWFHsZsw

Could you re-check?

**Comment by NikkTod** [comment]
Interesting, maybe because I am not administrator and in corporate virtual machine with applied firewalls and stuff. Nevertheless I have created them with the terminal, so I think I will close the ticket. Thank you for the support @vitalets :)

**Comment by vitalets** [comment]
You are welcome as usual :)
Fell free to report if there any issues.
