### ISSUE TITLE
Question: is there a possibility to import defineStep instead of gherkin keywords?

### ISSUE THREAD

**Issue by l-wysocki** [vitalets/playwright-bdd#45]
Is there a possibility to import defineStep instead of Given, When, Then to create a step definitions?

I'm using playwright style to create a step definition and some of the steps might be reused as Given/When and I don't want to duplicate the step definition. With defineStep, there is no need to specify the Gherkin keyword in the step definition.

**Comment by l-wysocki** [comment]
@vitalets Nope, naming is not important at all, jus the functionality of it :)

**Comment by vitalets** [comment]
Updated readme to highlight that there is also `Step` function.
