### ISSUE TITLE
Allow users to specify a custom path for feature files.

### ISSUE THREAD

**Issue by dipasqualew** [vitalets/playwright-bdd#5]
First of all, thank you for putting together this library! I am excited!

At the moment the `bddgen` bin expects the feature files to be found at `feature/*.feature`, however I'd love to define them in `tests/features/.feature`.

Creating an issue now and might work on a PR if there is interest!

**Comment by vitalets** [comment]
Hi! Playwright-bdd uses [cucumber config](https://github.com/cucumber/cucumber-js/blob/main/docs/configuration.md#finding-your-features) for searching features files. So, all you need is to set `paths` in `cucumber.js`:
```js
module.exports = {
  default: {
    paths: ['tests/features/**/*.feature'],
    // ...
  },
};
```
Updated readme for that. Thanks!
