### ISSUE TITLE
Bug: duplicated text does not support

### ISSUE THREAD

**Issue by wootra** [vitalets/playwright-bdd#50]
**Given**
What is your setup: paste your playwright config, feature file and directories structure
```
import { devices, defineConfig } from "@playwright/test";

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
import dotenv from "dotenv";
import { defineBddConfig } from "playwright-bdd";


dotenv.config({
	path: "./.env",
});
console.log("setting on env:"+ process.env.NODE_ENV);

dotenv.config({
	path: `./.env.${process.env.NODE_ENV}`,
});
dotenv.config({
	path: `./.env.${process.env.NODE_ENV}.local`,
});

console.log("public url is:", process.env.PUBLIC_URL);

const testDir = defineBddConfig({
	paths: ["./features"],
	importTestFrom: './steps/fixtures.ts',
	require: ['./steps/*.ts'],
	quotes: 'backtick' // when fixture filles are converted to spec.ts files, quotes will be replaced to the backticks
});

// 
export default defineConfig({
	testDir,
	timeout: 60 * 1000,
	expect: {
		/**
		 * Maximum time expect() should wait for the condition to be met.
		 * For example in `await expect(locator).toHaveText();`
		 */
		timeout: 10000,
	},
	/* Run tests in files in parallel */
	fullyParallel: true,
	/* Fail the build on CI if you accidentally left test.only in the source code. */
	forbidOnly: !!process.env.CI,
	/* Retry on CI only */
	retries: process.env.CI ? 2 : 0,
	/* Opt out of parallel tests on CI. */
	workers: process.env.CI ? 1 : undefined,
	reporter: [["html", { outputFolder: "./reports" }]],
	use: {
	  	actionTimeout: 0,
		/* Base URL to use in actions like `await page.goto('/')`. */
		baseURL: process.env.PUBLIC_URL ?? 'http://my-dev.dimensional.com',
		screenshot: 'only-on-failure',
		/* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
		trace: "on-first-retry",
		testIdAttribute: "data-qa",
	},
	projects: [
		{
			name: "setup",
			testMatch: /\/__[a-zA-Z0-9].[a-zA-Z0-9_-]+\.feature\.spec\.js$/,
		},
		{
			name: "chromium",
			use: {
				...devices["Desktop Chrome"],
				// Use prepared auth state.
				storageState: ".auth/user.json",
			},
			testMatch: /\/[a-zA-Z0-9].[a-zA-Z0-9_-]+\.feature\.spec\.js$/,
			dependencies: ["setup"],
		},
		
	],
	/* Run your local dev server before starting the tests */
	...((!process.env.CI || process.env.CI === 'false') && process.env.NODE_ENV === 'development' ? {
			webServer: {
			   command: 'echo \"running dev server\";cd ../../src/cra;npm run start',
			   port: 3006,
			   reuseExistingServer: (!process.env.CI || process.env.CI === 'false')
			 },
		}: 
		{}
	)
});


```
**When**
```
npx bddgen
```

**Then**
I have 2 `@When` decorators which have the same text. in the other fixtures i.e.
```

export 
@Fixture<typeof test>("smaBuildModal")
class SmaBuildModal extends Common {
   @When("I add direct equity")
	async addDirectEquity() {
		await this.page.getByTestId("tab-item-strategyDesign-sma").click();
		await this.page.locator(".direct-equity-on-sma-modal").first().click({timeout: 3000});
	}
}

export 
@Fixture<typeof test>("modelBuildModal")
class ModelBuildModal extends Common {
	@When("I add direct equity")
	async addDirectEquity() {
                // different selectors from smaBuildModal
		await this.page.getByTestId("tab-item-strategyDesign-model").click();
		await this.page.locator(".direct-equity-on-model-modal").first().click({timeout: 3000});
	}
}

```
my fixture file:
```
@fixture:smaBuildModal 
Feature: SMA strategy design
    Scenario: Direct equity select and deselect
        When I add direct equity
```

my fixtures.ts file
```

type Pages = {
	smaBuildModal: SmaBuildModal;
	modelBuildModal: ModelBuildModal;
};

export const test = base.extend<Pages>({
	smaBuildModal: async ({ page }, use) => use(new SmaBuildModal(page)),
	modelBuildModal:async ({ page }, use) => use(new ModelBuildModal(page)),
});

```

**Expected behavior**
What did you expect?
Since they have to be compiled using different fixture class, both should be parsed properly.
when I didn't have the second fixture(ModelBuildModal), I could get below file. I am expecting to have similar file for the second fixture using modelBuildModal instead of smaBuildModal.
```
/** Generated from: features/sma-build/sma-create-new-sma/sma-direct-equity-only.feature */
import { test } from "../../../../steps/fixtures.ts";

test.describe(`SMA strategy design`, () => {

  test.beforeEach(async ({ Given, smaBuildModal }) => {
    await Given(`I am on new sma build modal`, null, { smaBuildModal });
  });

  test(`Direct equity select and deselect`, async ({ When, And, Then, smaBuildModal }) => {
    await When(`I select "strategy design" tab`, null, { smaBuildModal });
    await And(`I add direct equity`, null, { smaBuildModal });
```

**Isolated demo**
It's very helpful if you try to reproduce your behavior on the reference repo [playwright-bdd-example](https://github.com/vitalets/playwright-bdd-example). Feel free to make a pull request and post link here.

**Environment**
Please run `npx bddgen env` and post output here:
```
> ddx-tools-playwright@1.0.0 watch:bdd
> nodemon -w ./features -w ./steps -w ./step-utils -e feature,js,ts --exec 'npx bddgen'

[nodemon] 3.0.1
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): features/**/* steps/**/* step-utils/**/*
[nodemon] watching extensions: feature,js,ts
[nodemon] starting `npx bddgen`
setting on env:development
public url is: http://localhost:3006
ERROR: Several step definitions found for text: I add direct equity (features/sma-build/funding-transition.feature)
- I add direct equity
- I add direct equity
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by wootra** [comment]
I tried to find where the fixture is received and try to use the right fixture when the step is retrieved, but only one fixture was received. When I use extend functionality of class, one step can belong to multiple fixture (parent and child fixture classes), but it was not easy to retrive all the fixtures to check what is current step to differentiate if the step is from parent fixture or current fixture. Not sure what is the best practice because if duplicated step text is not allowed, class structure will have no benefit.

**Comment by vitalets** [comment]
Having duplicated step text is not allowed (even in cucumber itself).
Isn't it work if you move it to common class?
```ts

class Common {
  @When("I add direct equity")
  async addDirectEquity() {
    await this.page.getByTestId("tab-item-strategyDesign").click();
    await this.page.locator(".item-name > [data-qa=direct-equity-select-button]").first().click({timeout: 3000});
  }
}

export 
@Fixture<typeof test>("smaBuildModal")
class SmaBuildModal extends Common {
  ...
}

export 
@Fixture<typeof test>("modelBuildModal")
class ModelBuildModal extends Common {
  ...
}
```

**Comment by wootra** [comment]
@vitalets thanks for the answer. Yes, for now I had to make common class like you mentioned above. But it creates a lot of necessity of handling internal states.
for example, smaBuildModal and modelBuildModal is different UI. to handle "I add direct equity", I have to hold state like `listType`, and the test will look like this:
```
   switch(this.uiType){
      case 'sma-build-modal':
        this.addDirectEquityOnSma();
        break;
      case 'model-build-modal':
       this.addDirectEquityOnModel();
       break;
   }

```
You see how much the logic become complex because of this limitation.

**Comment by wootra** [comment]
It will not be easy, but I was thinking about this approach:
when regEx parse the class structure, relate the fixture name with class name as well as its parent:
i.e.
```
@Fixture("modelBuildModal")
class ModelBuildModal extends Common

@When('some when')
...
```
will create below structure:
```
type Step = {
  type: 'When' | 'Then' | 'Given',
  text: string,
  arguments: Arguments[],
  logic: string,
}

type FixtureDefinition = {
  fixtureName: string;
  className: string;
  parentClass: string | null;
  steps: Step[],
}
type FixtureMap = Record<string, FixtureDifinition>;

const fixtureMap = {
  'modelBuildModal': {
     fixtureName: 'modelBuildModal',
     className: 'ModelBuildModal',
     parentClass: 'Common'
  },
  'common': {
    fixtureName: 'common',
    className: 'common',
    parentClass: null,
  }
}

```
Then we can have full structure to create the test.

**Comment by vitalets** [comment]
I've made a deeper research on that. General approach across all bdd implementations is to avoid duplicated steps. A few quotes:

> The reason for that is if a step is ambiguous for the machine, it probably is even more ambiguous for the people reading/writing those steps.

> the step definitions are global, it is an anti-pattern to create feature-specific steps : https://cucumber.io/docs/guides/anti-patterns/#feature-coupled-step-definitions

Some references:
- https://stackoverflow.com/questions/63178537/cucumber-bdd-different-features-requiring-similar-step
- https://github.com/cucumber/cucumber-js/issues/981
- https://github.com/cucumber/cucumber-js/issues/176#issuecomment-47572827

For that case with `I add direct equity` lets try to find a solution. In you sample code I see different implementations, could you share the bodies of `this.addDirectEquityOnSma()` and  `this.addDirectEquityOnModel()`? If actual implementations have differences, it's good to indicate that in the step names -> and it will solve the problem.

**Comment by wootra** [comment]
Thank you for the answer and I understand the concern. Agree that it can lead to the code explosion. 
In the beginning, I thought this was over management and should open the possibility, but on the second thought, it actually makes sense that can minimize redundant code. 
If the case is supposed to do different things for the same description, maybe that is because test-id is not well labeled for a similar task. 
There is a risk that the locator finds more than 1 element from the same selector or same test id, but it can be filtered by enabled/visible element instead of counting the hidden element.
For example, download buttons can be multiple on the screen (i.e. one on the modal, the other on the base screen under the backdrop), and both of them can be found by `data-testid="download-button"`  but BDD perspective, the download button that is visible should be just the one that the user is currently looking at.
But it can be tough if the test writer and UI coder is different. This is something that we need to think about more. 
With all considerations, I think not allowing feature separation is limiting what is supposed to be possible but should be used with caution (like most programming languages).

**Comment by wootra** [comment]
while I was thinking this is still needed, there is another workaround exists, and also it is defined as an anti-pattern, I will close this issue. thanks for the help!
