### ISSUE TITLE
Question: should new versions support only playwright >=1.33 version?

### ISSUE THREAD

**Issue by wootra** [vitalets/playwright-bdd#56]
My team recently had to downgrade playwright version from the latest version(1.38.1) to 1.32 version because of the VM's OS issue (Redhat 7) and it takes long time to upgrade OS.
The problem with playwright started, so we should downgrade it.
I already converted a lot of playwright tests into playwright-bdd tests, but I see this error message:
<img width="566" alt="image" src="https://github.com/vitalets/playwright-bdd/assets/6027633/66b9fe79-dcfd-4c5c-9a78-ac75e7ac38c7">
```
npm ERR! Could not resolve dependency:
npm ERR! peer @playwright/test@">=1.33" from playwright-bdd@5.3.0
npm ERR! node_modules/playwright-bdd
npm ERR!   dev playwright-bdd@"5.3.0" from the root project
```
I tried to find which version is working, and found `3.3.0` version is the latest version that supports playwright 1.32 version.
Okay, now I was ready to continue, but my whole script was broken saying "decorator" does not support in playright..
I'm stuck. Please help me.

**Comment by vitalets** [comment]
Hi @wootra , sorry for late response.
We need at least Playwright 1.33 to support decorators. 
Does Playwright 1.33 also have that OS issue? Maybe create corresponding ticket in Playwright repo - as sticking to old Playwright version is not good anyway..

**Comment by wootra** [comment]
@vitalets unfortunately, 1.33 is not available in Redhat 7 which is installed in our pipeline process ( as our DevOps engineer mentions ). This is unfortunate for us. But this is a great project! Thanks for the answer.
