### ISSUE TITLE
Question: global variable to share between steps and parallel execution

### ISSUE THREAD

**Issue by jzaratei** [vitalets/playwright-bdd#61]
Hi, I'm using the fixture approach to store a list of elements `elementType[]` that I get in step1 and use it to assert it in step2. The thing is that when I execute my test in parallel (more than 1 worker), `elementType[]` is storing all the elements from all the test cases and the assert fails. It just passes in the retry execution.
I did a research in google, and it seems that playwright reuse the same worker to make testing faster and only restart the worker when the test fails.

So, I was wondering if there is a way to accomplish global variables while doing parallel execution. Like, be able to reset the worker for a particular test case. Any idea on it would be appreciated.

This is the fixture:

```
export const test = base.extend<{
todoPage:  TodoPage;
elementList: elementType[]}>
  ({
  elementList: [];
  todoPage: async ({ page, elementList}, use) => {
      await use(new TodoPage(page, elementList));
    },
  )

--------------------------------------------
export
@Fixture("todoPage")
class TodoPage{

  constructor(
      public readonly page: Page,
      public elementList: elementType[],
    )

  async updateElementList(element) {
   this.elementList.push(element)
  }
}
```

**Comment by odeatomas** [comment]
I'm having the same issue  with the following code - the same code passes in the cucmber.js project I ported it from.  
counting video thumbnails - test  pass in serial but fails in parallel

this line fails as count is always wrong  
await expect(this.page.locator(imageThumbnailVideo)).toHaveCount(videoCount); 


`    @When('I capture video {string} duration {string}')
    async videosForLandmarks(numberOfImagesVideo: number, duration: number) {
        const basepage = new BasePage(this.page);

        console.log(duration)
        let videoCount = 1;
        const imageThumbnailVideo = `.cap-image.img-thumbnail`;
        while (videoCount <= numberOfImagesVideo) {
            //    await this.page.waitForTimeout(5000)
            console.log(`clicking video ${videoCount} of ${numberOfImagesVideo}`);
            await this.page.getByRole('button', { name: 'Start Recording' }).click();
            await this.page.getByRole('button', { name: `Stop (${duration}s)`, exact: true }).click();
            //  await this.page.getByText(`${duration}s`).isVisible()
            await basepage.waitForApiResponse('api/proceduremedia/prepare-upload', 'Prepare upload complete')
            await basepage.waitForApiResponse('api/proceduremedia/upload-complete?', 'Video uploaded successfully')
            await basepage.waitForApiResponse('api/proceduremedia/procedure-image-thumbnails', 'Thumnbnail created successfully')
            await expect(this.page.locator(imageThumbnailVideo)).toHaveCount(videoCount);
   
            videoCount++;

        }
    }`

  
it seems like I need to have a clean browser context for each test. 
not sure how I  do that in playwright bdd 
in cucumber js project I did it in hooks  



`Before( async function ({pickle, message}) {
    const tags = pickle.tags.map( tag => tag.name );
    // @ts-ignore
    console.log( "Scenario " + pickle.name + "", ' ' + ' ' + '\n' + " has started , tags are " + tags );
    //read env variables from .env file
    getEnv();
    // Create a global browser for the test session pass in options.
    // @ts-ignore
    browser = await invokeBrowser( playwrightConfig.use );
    //create a new browser context for each scenario pass in options.
    // @ts-ignore
    context = await browser.newContext( playwrightConfig.use );
    //create a new page for each scenario

    // @ts-ignore
    page = await context.newPage();
    await context.tracing.start( {
        snapshots: true,
        screenshots: true,
        name: pickle.name,
    } );`

**Comment by vitalets** [comment]
I think for sharing data between steps global variable is not needed, fixtures are shared between steps. So It looks to me you can put `elementList` into the `todoPage` fixture:
```ts
export
@Fixture("todoPage")
class TodoPage{
  public elementList: elementType[];

  constructor(public readonly page: Page)

  async updateElementList(element) {
   this.elementList.push(element)
  }
}
```

Or maybe you mean sharing data between scenarios?

**Comment by jzaratei** [comment]
@vitalets I follow your advice and I got the same results. I'm starting to think that this is some kind of bug. I will try to reproduce it in the bbd-example project.

**Comment by vitalets** [comment]
Ok, let me know when ready.

**Comment by jzaratei** [comment]
@vitalets I'm using global variables to share data between differents fixtures-pageObjects. Like in this scenario:

```
Scenario: parallel sharing
      When I add todo "item1"
      And I add todo "item2"
      And I add todo "item3"
      Then I assert all todos
```
https://github.com/jzaratei/playwright-bdd-example/tree/parallel

I have a todoPage and an assertPage. This last one is where I assert a list of items stored in previous steps (todoPage).

The issue here is that the step `When I add todo "item1"` is reused in other test cases in the same feature and it seems that the workers is sharing the same global variable during the execution. I'm don't fully understand how the workers works in parallel but I would say that they should have their own context (browser, variables, objects, etc) .

Another approach would be having a single fixture where I could define `And I add todo "item3"` and `Then I assert all todos`., but if I do that feels like I'm limited in how to organize the page objects.

Thank you for your support.

**Comment by jzaratei** [comment]
Finally, I manage to accomplish the global variable, and I guess it was a silly implementation by my side because, instead of assigning an empty string I just had to create a new array object every time the fixture is called. Like this:

```
todoList: async ({}, use) => {
    await use(new Array())
  },
```

That way, todoList is created for each test.

I'm closing this issue. Thanks!

**Comment by vitalets** [comment]
Yes, this is exactly the solution. You can also make it in oneline:
```ts
todoList: async ({}, use) => use([]),
```
