### ISSUE TITLE
Question: How can we sponsor this project

### ISSUE THREAD

**Issue by agoldis** [vitalets/playwright-bdd#62]
Kudos on the work done so far. Please share how can we help financially.

**Comment by vitalets** [comment]
Hi @agoldis ! I think I can setup open collective for it.
If you have more ideas, lets discuss on fb by link in my profile.

**Comment by agoldis** [comment]
@vitalets if you're open to GitHub Sponsorship - it would be the best, they also will give you some extra $$

**Comment by gzuppl** [comment]
@vitalets i will happily join the bandwagon on this. Already tried to "buy you a big coffee" but failed due to payment method including something easily accessible for me (say paypal ;)).

**Comment by vitalets** [comment]
Thanks for your supporting comments! I've GitHub Sponsorship request form.

**Comment by agoldis** [comment]
Hooray! https://github.com/sponsors/vitalets

**Comment by vitalets** [comment]
Thank you @agoldis !
Now currents.dev is in Sponsors section in readme 🎉
https://github.com/vitalets/playwright-bdd#sponsors

**Comment by agoldis** [comment]
yay! Thanks a ton!

**Comment by vitalets** [comment]
@jzaratei thank you for your support ❤️

**Comment by vitalets** [comment]
Big thanks to new sponsors ❤️
@timm-z
@NikkTod
@alescinskis

**Comment by vitalets** [comment]
Thanks to new sponsor ❤️
@kahuna227

**Comment by vitalets** [comment]
Thanks to new sponsors of playwright-bdd ❤️
* @alexhvastovich
* @synnksou

**Comment by vitalets** [comment]
@FrancescoBorzi, thanks for your support of playwright-bdd project ❤️

**Comment by vitalets** [comment]
Added a dedicated section for the sponsors in the docs: https://vitalets.github.io/playwright-bdd/#/sponsors
Will reflect all updates there.
