### ISSUE TITLE
Question: How can I conditionally skip a test?

### ISSUE THREAD

**Issue by vcardins** [vitalets/playwright-bdd#64]
Hi!

According to Playwright documentation, I can conditionally [skip a test](https://playwright.dev/docs/test-annotations#conditionally-skip-a-test). Is possible to do that?

Thanks

**Comment by jzaratei** [comment]
Use @skip (or @fixme) tag to skip a particular feature / scenario:
@skip
Feature: Playwright site

    @skip
    Scenario: Check title
        Given I open url "https://playwright.dev"

https://vitalets.github.io/playwright-bdd/#/writing-features?id=skip-feature

**Comment by vcardins** [comment]
@vitalets I believe I was not clear in my question. Just skipping a test is fine, but I want to **conditionally** slip it, just like
```
test('skip this test', async ({ page, browserName }) => {
  test.skip(browserName === 'firefox', 'Still working on it');
});
```

Based on your response, I assume it would be

```
Given('I do something', async ({ $test, $testInfo }) => { 
  $test.skip(browserName === 'firefox', 'Still working on it');
  console.log(`skipped test: ${$testInfo.title}`);
})
```
Is that correct?
Thanks

**Comment by vitalets** [comment]
Yes, you are right. Just use `browserName` fixture to get actual browser:
```ts
Given('I do something', async ({ $test, browserName }) => { 
  $test.skip(browserName === 'firefox', 'Still working on it');
});
```
