### ISSUE TITLE
Under configfile How can we add multiple file path using 'importTestFrom' 

### ISSUE THREAD

**Issue by AnanthaNagaraj** [vitalets/playwright-bdd#66]
i need to set multiple file path under 'importTestFrom'. when i try to use '[ ]' it throw 'Type 'string[]' is not assignable to type 'string | ImportTestFrom | undefined'.'

![image](https://github.com/vitalets/playwright-bdd/assets/84306116/409383c8-f924-476d-a62d-a9e6375d036b)

**Comment by vitalets** [comment]
Currently only single file can be passed to `importTestFrom`.
Could you share more details on your goal?
If `fixtures.ts` extends test from `test-base.js`, then there is no need to import `test-base.js`.

Support of several test instances is also tracked here: https://github.com/vitalets/playwright-bdd/issues/46
