### ISSUE TITLE
Question: Is there a recommended way to use this with Nx?

### ISSUE THREAD

**Issue by barrymichaeldoyle** [vitalets/playwright-bdd#68]
This library has been the closest way I could get to getting BDD testing working with playwright.

Nx recently added playwright generators to their toolset. It would be epic if there was a documented way on how to using this library with Nx. I'm really struggling to conceptualize how I would configure all of this.

**Comment by vitalets** [comment]
I've got it working with the following `project.json` ([full example code](https://github.com/vitalets/playwright-bdd-example/tree/nx)):
```json
{
  "targets": {
    "bddgen": {
      "command": "bddgen",
      "outputs": ["{workspaceRoot}/.features-gen"]
    },
    "e2e": {
      "executor": "@nx/playwright:playwright",
      "dependsOn": ["bddgen"],
      "options": {}
    }
  }
}
```
Running `npx nx e2e` executes `bddgen` first to generate tests and then runs Playwright.
Could you check does it work for you? And we will add it as a recipe to docs.

**Comment by barrymichaeldoyle** [comment]
The example code you provided is a little confusing.

I'm using the latest version of nx and I have multiple `apps` so I don't know what should go in my root directory vs at the project/app directory.

**Comment by vitalets** [comment]
> I'm using the latest version of nx and I have multiple `apps` so I don't know what should go in my root directory vs at the project/app directory.

Could you provide more details about your project structure - otherwise it's difficult to help. Do you run your e2e tests in each app separately, or you run them like integration tests over all apps?

**Comment by barrymichaeldoyle** [comment]
I have a layout like this:

```
/apps
  /app1
    /e2e
    /src
    project.json
    ...other project specific files
  /app2
    /e2e
    /src
    project.json
nx.json
...other root level files
```

Then I'll run my e2e tests like this:

```
nx e2e app1
```

or 

```
nx e2e app2
```

Or this if I wanted to run all `e2e` tests for my CI:

```
nx run-many --all --target=e2e
```

**Comment by vitalets** [comment]
Could you try to put targets from my `project.json` example to `app1/project.json` and `app2/project.json`.

**Comment by vitalets** [comment]
Yes, good point! 
I've found the following `project.json` to run these commands in the correct cwd:
```json
{
  "targets": {
    "bddgen": {
      "command": "bddgen",
      "outputs": ["{projectRoot}/.features-gen"],
      "options": {
        "cwd": "{projectRoot}"
      }
    },
    "e2e": {
      "executor": "@nx/playwright:playwright",
      "dependsOn": ["bddgen"],
      "options": {
        "config": "{projectRoot}"
      }
    }
  }
}
```

We can also move this as defaults to root `nx.json`:
```json
{
  "targetDefaults": {
    "bddgen": {
      "command": "bddgen",
      "outputs": ["{projectRoot}/.features-gen"],
      "options": {
        "cwd": "{projectRoot}"
      }
    },
    "e2e": {
      "executor": "@nx/playwright:playwright",
      "dependsOn": ["bddgen"],
      "options": {
        "config": "{projectRoot}"
      }
    }
  },
  "affected": {
    "defaultBase": "main"
  }
}
```
And then keep `project.json` simple:
```json
{
  "targets": {
    "bddgen": {},
    "e2e": {}
  }
}
```
(I didn't find the way to avoid these empty `{}` commands)

**Comment by barrymichaeldoyle** [comment]
@vitalets thank you! That did the trick 🎉

**Comment by vitalets** [comment]
You are welcome! 
I will add it as a recipe to the docs.

**Comment by barrymichaeldoyle** [comment]
One random thing I'm seeing is for this: `"outputs": ["{projectRoot}/.features-gen"],` no matter what valid path I set this value to, it always just generates at `{projectRoot}/.features-gen`. E.g. I want it to be `{projectRoot}/e2e/generated` but it still generates them to `.features-gen`.

**Comment by barrymichaeldoyle** [comment]
Looks like I sorted it out by setting `outputDir` in the `defineBddConfig`.

Seems like the `outputs` for the `project.json` wasn't necessary at all.

**Comment by vitalets** [comment]
Yes. I thought `outputs` can be useful for nx caching - to not re-generate test files when nothing changed.
But now I realize it should rely on inputs, not outputs :) 
Anyway this is kind of optimization, great that basically it works.

**Comment by vitalets** [comment]
Added to docs: https://vitalets.github.io/playwright-bdd/#/recipes?id=usage-with-nx
Thanks @barrymichaeldoyle for raising this!

**Comment by barrymichaeldoyle** [comment]
@vitalets I'm not sure if this just me but I've noticed that `@skip` for features isn't working with this setup 🤔

**Comment by barrymichaeldoyle** [comment]
Sorry I was a bit vague there.

The problem occurs when I try to `@skip` a Feature when it's step definitions aren't defined.

I get this message:

> Missing step definition for "e2e/features/my_special.feature:24:5"

I managed to get around this by either commenting out the steps that are missing definitions or I can create empty definitions and that also does the trick.

This error occurs during the `bddgen` step.

**Comment by vitalets** [comment]
Good case. Created a separate issue for that https://github.com/vitalets/playwright-bdd/issues/73
