### ISSUE TITLE
Question: can we get the tags/annotation in the final html or json report 

### ISSUE THREAD

**Issue by meeranharish** [vitalets/playwright-bdd#70]
Hi
Its common to use tags in the feature files. I would like to  see them in the reports 
eg:
@featuretagworks?
Feature: Login

  @scenariotagworks?
  Scenario: Successful login
    Given User navigate to the app
    When User logs in with valid creds
    Then User logged in successfully

I want the @scenariotagworks? @featuretagworks? to be available in the json and/or html report. 
Is this possible right now? @vitalets 

The reason behind this need is, I tag my scenario with test cases items ID of Azure Devops to maintain treaceablity between the scripts, test cases and execution results. 
Thanks

**Comment by vitalets** [comment]
Hi @meeranharish
Yes, tags are available as a `$tags` fixture. Playwright's html-report doesn't have built-in place for showing tags, but [custom annotations ](https://playwright.dev/docs/test-annotations#custom-annotations)look like a good option.
To automatically add tags to html-report for all scenarios, you can use the following auto-fixture:
```ts
import { test as base } from 'playwright-bdd';

const test = base.extend<{ addTags: void }>({
  addTags: [async ({ $tags }, use, testInfo) => {
    testInfo.annotations.push({
      type: 'tags',
      description: $tags.join(', '),
    });
    await use();
  }, { auto: true }],
});
```
Then you will get tags in the report:
<img src="https://github.com/vitalets/playwright-bdd/assets/1473072/01e1cfef-2c24-49c4-9ea4-64d45036f9c5">


Let me know if it works for you, and I will add it to the docs as I think this case is very useful.

**Comment by meeranharish** [comment]
Nice. It works :)
Thanks

**Comment by vitalets** [comment]
Added to [docs](https://vitalets.github.io/playwright-bdd/#/./writing-steps?id=example-2).
