### ISSUE TITLE
Bug: Not able to use AfterAll hook in BDD

### ISSUE THREAD

**Issue by magarwal19** [vitalets/playwright-bdd#75]
**Given**
I am using the latest version of Playwright-BDD

**When**
I try to use AfterAll hook and add below code to file:
const { createBdd } = require('playwright-bdd');
const { BeforeAll, AfterAll } = createBdd();
AfterAll(async function ({ $workerInfo, browser }) {
    // runs when each worker ends
  });

**Then**
on runnning command getting error
TypeError: AfterAll is not a function

**Expected behavior**
We should be able to use AfterAll hook

**Isolated demo**

**Environment**
Playwright-bdd environment info:

platform: darwin
node: v16.20.0
playwright-bdd: v5.4.0
@playwright/test: v1.39.0
@cucumber/cucumber: v9.4.0
Playwright config file: playwright.config.js
```
```

**Comment by vitalets** [comment]
> playwright-bdd: v5.4.0

Hi @magarwal19 ! Looks like you are using playwright-bdd 5.4.0, but hooks support was added in 5.5.0. Could you install the latest version and try again?
```
npm i -D playwright-bdd@latest
```

**Comment by magarwal19** [comment]
Hi @vitalets 
Thanks for updating.
Installed latest version and able to use Hooks now.
Not sure why but there is no information visible on npm page
![Screenshot 2023-11-27 at 12 30 49 PM](https://github.com/vitalets/playwright-bdd/assets/47243226/675f59ab-6e7e-4004-a40b-596882146d34)

**Comment by vitalets** [comment]
You are welcome!

> Not sure why but there is no information visible on npm page

Yes, it's strange. Maybe some issues with npm itself? I've checked now, it shows 
![image](https://github.com/vitalets/playwright-bdd/assets/1473072/93fc8f9c-b833-4a6a-b5e1-92041402c696)
