### ISSUE TITLE
Feature: Can we show execution time of each step within the feature file after a scenario run

### ISSUE THREAD

**Issue by NikkTod** [vitalets/playwright-bdd#76]
**The problem**
Within the test explorer tree we can see the features and the scenarios, but I am not able to expand a scenario to see the steps. 
I think this issue very much depends on the playwright team, but I was wondering if there is a way to show the execution time of each step within the feature file after a scenario has been executed. 

So maybe a something like that:

Given I log in to the environment      _- (last run 1,5 seconds)_

PS: 
When I start a test and if I open the feature.spec.js file, then I see a time for each step, the problem is that if you switch to another file the timing is lost.

**Comment by vitalets** [comment]
Closing as it's mainly on Playwright team side.
