### ISSUE TITLE
Question: how to move "background" step out of "beforeHooks"

### ISSUE THREAD

**Issue by alescinskis** [vitalets/playwright-bdd#78]
Hello,

I want to be able to utilise [background](https://cucumber.io/docs/gherkin/reference/#background) keyword in my scenarios, but I see that in html report, when such background section is present, it's listed under "beforeHooks", which hinders scenario readability.

report looks like this:
<img width="830" alt="image" src="https://github.com/vitalets/playwright-bdd/assets/29544469/7f30d6cf-5b64-43d9-ae95-7fe92aa73d77">
if we delve into "beforeEachHook" then we'll see the background step is there
<img width="985" alt="image" src="https://github.com/vitalets/playwright-bdd/assets/29544469/72732234-e4e8-4c4b-aadb-3201997997d9">
I'd like the background step be on the scenario level in the reporter, like this
<img width="965" alt="image" src="https://github.com/vitalets/playwright-bdd/assets/29544469/7924a4aa-81b6-4d04-b972-df96eee679da">

is it currently possible to move it on the scenario level? or this feature should be requested?

**Comment by vitalets** [comment]
Now playwright-bdd supports Cucumber reports, that show background step as in feature file.
There is another idea to enhance Playwright html reporter, tracked here https://github.com/vitalets/playwright-bdd/issues/122
