### ISSUE TITLE
Bug: Tests failing with latest version install due to changes in Cucumber package

### ISSUE THREAD

**Issue by magarwal19** [vitalets/playwright-bdd#80]
**Given**
I do the npm install in any existing project which do not. have lock file

**When**
I run the tests

**Then**
an error message is displayed with error

**Reason of Failure**
Changes done by Cucumber package in latest version in PR
https://github.com/cucumber/cucumber-js/pull/2361/files

**Environment**
node: v20.10.0
playwright-bdd: v5.6.0
@playwright/test: v1.36.2
@cucumber/cucumber: v10.1.0

I am able to replicate this with https://github.com/magarwal19/playwright-bdd if i update cucumber version to    "@cucumber/cucumber": "^10.1.0",
and recreate package.lock file
![terminal error](https://github.com/vitalets/playwright-bdd/assets/47243226/b44c302a-944c-4a57-ab2c-4b37e12152cd)

```
```

**Comment by vitalets** [comment]
Thanks for reporting! Fixing..

**Comment by osundwajeff** [comment]
Any progress on this @vitalets ?

**Comment by vitalets** [comment]
> Any progress on this @vitalets ?

I was on Christmas vacation, now investigating on this issue with top priority.

**Comment by vitalets** [comment]
Fixed in v5.7.0.
Please re-check on your side and reopen if there are any issues.
