### ISSUE TITLE
Feature: Cucumber.js json Report generation

### ISSUE THREAD

**Issue by dlitmano** [vitalets/playwright-bdd#82]
**The problem**
You have awesome reports, but I need the cucumber.js json report to connect my test automation to test management system. 

**A solution**
please provide a cucumber.js reporting solutions embeded inside your code

**Comment by vitalets** [comment]
Working on it in #9.
Just to clarify - do you mean Cucumber's [message](https://github.com/cucumber/cucumber-js/blob/main/docs/formatters.md#message) reporter?

**Comment by dlitmano** [comment]
I mean json reporter generated by cucumber.js. Here is an example https://docs.getxray.app/display/XRAYCLOUD/Import+Execution+Results+-+REST+v2#ImportExecutionResultsRESTv2-CucumberJSONresults

**Comment by vitalets** [comment]
> I mean json reporter generated by cucumber.js.

Noted. Hopefully, after adding support of `message` reporter, all other Cucumber reporters will be available with minimal edits.

**Comment by dlitmano** [comment]
do you need help with that?

**Comment by vitalets** [comment]
> do you need help with that?

The work is already in progress. I will need some help for checking reports as there are many cucumber messages and something could be missed. I'll post here when a beta version will be ready!

**Comment by vitalets** [comment]
Released in v6. Here is [the docs for json reporter](https://vitalets.github.io/playwright-bdd/#/reporters/cucumber?id=json).
Your feedback is welcome!
