### ISSUE TITLE
Project roadmap for 2024

### ISSUE THREAD

**Issue by vitalets** [vitalets/playwright-bdd#83]
I'd like to share my thoughts on playwright-bdd development in 2024. 
There are 3 main directions:

1. ✅ **Become less dependent on Cucumber internals**
Currently feature files and step definitions are loaded using Cucumber internal functions. It has several downsides:
   * changes in Cucumber can break playwright-bdd (as it was in #80)
   * tricky run for ESM: [need to pass](https://github.com/cucumber/cucumber-js/blob/main/docs/transpiling.md#with-ts-node) `NODE_OPTIONS: '--loader ts-node/esm --no-warnings'` for Cucumber although Playwright handles ESM internally without ts-node
   * need to configure `importTestFrom` manually, impossible to have several `test` instances (see #46)
   * performance: each Playwright worker loads full Cucumber package although runner is not used
   
   All these points will be resolved if playwright-bdd will load features and step definitions by own code. For features it can rely only on [@cucumber/gherkin](https://github.com/cucumber/gherkin) and for step definitions it can re-use Playwright's methods for loading test files. Actually, playwright-bdd already [uses Playwright's import](https://github.com/vitalets/playwright-bdd/blob/main/src/gen/index.ts#L91) for loading steps in decorator syntax.
   
2. ✅ **Support Cucumber reporters**
Playwright HTML reporter is not the best option for showing BDD test results, it is not designed for it. Background steps are hidden inside beforeHooks (see #78), Scenario Outline requires titles setup (see #67), there are unneeded details (e.g. fixtures). [Cucumber's HTML reporter](https://github.com/cucumber/cucumber-js/blob/main/docs/formatters.md#html) is definitely better for BDD and was proposed a long time ago (see #9). Current idea is to support Cucumber's [message formatter](https://github.com/cucumber/cucumber-js/blob/main/docs/formatters.md#message) and then use it for all other Cucumber compatible reporters and test automation tools (see #82). To validate messages output playwright-bdd should pass [Cucumber compatibility-kit](https://github.com/cucumber/compatibility-kit). It's important to generate Cucumber messages from Playwright's Blob output, because it allows to shard test runs and finally build Cucumber report with Playwright's [merge reports command](https://playwright.dev/docs/test-sharding#merge-reports-cli).

3. 🔲 **Create a tool for writing BDD scenarios**
This is more an experimental idea. I think about creating an online tool for writing BDD scenarios during collaboration sessions. It should have a simple UI and help people to quickly compose BDD scenarios following the best practices. Additionally, you can import steps from [`bddgen export`](https://vitalets.github.io/playwright-bdd/#/cli?id=bddgen-export) command and use them for inline suggestions to speedup the process.
The closest existing service is [CucumberStudio](https://cucumber.io/tools/cucumberstudio/), but it is not free and has a complicated UI (imho). If you know other similar services, feel free to share in the comments.

Any your ideas and thoughts are welcome here or in the corresponding issues!

**Comment by ronvoluted** [comment]
> 3. Create a tool for writing BDD scenarios
>If you know other similar services, feel free to share in the comments.

It's not Gherkin or E2E but for some good precedent on collaboration, good DX, nice design and support for various imports/exports there is [Stately](https://stately.ai), a UI for XState finite state machines.

**Comment by pateljigar** [comment]
Many teams have very common requirement to pass test data in the *.csv, *.xls, *.xml or *.json for different scenarios in the feature files. Currently we have a limitation of doing data driven testing using data tables only. This is really limiting lots of teams to design real life data driven tests.

can we please prioritise this in upcoming releases??

**Comment by CalebMacdonaldBlack** [comment]
@vitalets What are your plans around the html formatter? 

I'm trying to figure out where to focus my efforts regarding some possible improvements to the existing one.

Some options I've considered are:
1. Contributions to [cucumber/react-components](https://github.com/cucumber/react-components) and [cucumber/html-formatter](https://github.com/cucumber/html-formatter)
2. Contributions to [vitalets/playwright-bdd](https://github.com/vitalets/playwright-bdd)
3. Building a custom formatter based off of html-formatter

Some thought I have.
1. Contributions to the cucumber repos will likely be limited to changes that are within the scope of that project. So no playwright stuff. Fixes and enhancements to existing stuff is probably welcomed, but I additions will probably more difficult to get accepted.
2. Playwright-bdd looks to have recently changed how it depends on cucumber/html-formatter. Instead of importing the package, the code is copied instead. I suspect the intention is to build a html-formatter tailored to playwright-bdd using cucumber/html-formatter as a base. 
3. I'm not apposed to building my own customer formatter, but I would prefer to collaborate with others if I have the opportunity. 

@vitalets Do you have plans for building a html reporter for playwright-bdd? If so I would love to contribute.

**Comment by vitalets** [comment]
Hi @CalebMacdonaldBlack 

I think it's better to follow option 1 - contributions to [cucumber/react-components](https://github.com/cucumber/react-components) and [cucumber/html-formatter](https://github.com/cucumber/html-formatter). Cucumber team plans to make reporters more universal and less bound to Cucumber implementation. Recently they added external attachments and links list, that gives great opportunities to enrich this reporter with Playwright stuff, like trace-viewer and annotations.

> Playwright-bdd looks to have recently changed how it depends on cucumber/html-formatter. Instead of importing the package, the code is copied instead.

No. Playwright-bdd still [imports](https://github.com/vitalets/playwright-bdd/blob/7a15aed3e713a20d92d33e76f38bda45fa4d5cef/src/reporter/cucumber/html.ts#L8) cucumber/html-formatter.

Building own formatter for BDD is also a way to go. You can try to adopt existing Playwright html formatter for showing BDD stuff. We have an issue for that https://github.com/vitalets/playwright-bdd/issues/122. It can be even you personal project, that will be referenced in Playwright-bdd docs.

Building own Playwright-bdd HTML formatter from scratch is not planned for now.

**Comment by CalebMacdonaldBlack** [comment]
Thanks for the update @vitalets 

I'll have to think on this for a little bit.

**Comment by vitalets** [comment]
Some results and the next year roadmap are in https://github.com/vitalets/playwright-bdd/issues/260.
