### ISSUE TITLE
Bug: Usage with NX docs on nx.json settings

### ISSUE THREAD

**Issue by barrymichaeldoyle** [vitalets/playwright-bdd#87]
https://vitalets.github.io/playwright-bdd/#/recipes?id=usage-with-nx

In the docs here you've got this:

> If there are many projects with the same e2e setup, you can move default settings to `nx.json`:

When I added this to my `nx.json`:

```
    "bddgen": {
      "command": "bddgen",
      "options": {
        "cwd": "{projectRoot}"
      }
    },
    "e2e": {
      "executor": "@nx/playwright:playwright",
      "dependsOn": ["bddgen"],
      "options": {
        "config": "{projectRoot}"
      }
    },
```

I get this warning:

> Property command is not allowed.

<img width="386" alt="Screenshot 2024-01-31 at 17 56 22" src="https://github.com/vitalets/playwright-bdd/assets/4674486/46a64eb7-0218-4670-a9b3-cf6f2ce0bb62">

Is that an issue?

**Comment by barrymichaeldoyle** [comment]
It seems to work and taking it out causes it to break, but probably worth noting that there's a warning that occurs that we should ignore it.

**Comment by vitalets** [comment]
Interesting. In the [nx docs](https://nx.dev/core-features/run-tasks#define-tasks) I see the similar syntax:
<img width="50%" src="https://github.com/vitalets/playwright-bdd/assets/1473072/f5215ef7-beff-457f-9a81-e959f1827dbf">

I assume this shorthand is valid for `targets` in `project.json`, but not for `targetDefaults` in `nx.json`.
Could you try with full syntax using [nx:run-commands](https://nx.dev/nx-api/nx/executors/run-commands) executor?
```
"bddgen": {
  "executor": "nx:run-commands",
  "options": {
    "command": "bddgen",
    "cwd": "{projectRoot}"
  }
}
```
If warning goes out and everything works fine, we will update docs as well.

**Comment by barrymichaeldoyle** [comment]
> Interesting. In the [nx docs](https://nx.dev/core-features/run-tasks#define-tasks) I see the similar syntax: <img alt="" width="50%" src="https://private-user-images.githubusercontent.com/1473072/301277557-f5215ef7-beff-457f-9a81-e959f1827dbf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3Njk0MTUsIm5iZiI6MTcwNjc2OTExNSwicGF0aCI6Ii8xNDczMDcyLzMwMTI3NzU1Ny1mNTIxNWVmNy1iZWZmLTQ1N2YtOWE4MS1lOTU5ZjE4MjdkYmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMDFUMDYzMTU1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjEyZjIwZTU3ZmM5NmE4Y2JhOGMxOTBjYmMyZGQ4MmNiOTUwZDc5NzU3YTJlYjYyNTA5MjE1NDdkYmY2YThiNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vHOFuDb5zVtPPb6RJ9mQpnQy2xlRHGiByhxkrzam5eA">
> 
> I assume this shorthand is valid for `targets` in `project.json`, but not for `targetDefaults` in `nx.json`. Could you try with full syntax using [nx:run-commands](https://nx.dev/nx-api/nx/executors/run-commands) executor?
> 
> ```
> "bddgen": {
>   "executor": "nx:run-commands",
>   "options": {
>     "command": "bddgen",
>     "cwd": "{projectRoot}"
>   }
> }
> ```
> 
> If warning goes out and everything works fine, we will update docs as well.

Ah that's weird, it doesn't work. It gives me the same error that running just plain old `npx nx run app1:e2e`. Like I had to remind myself to run `npx nx e2e app1`.

The error is just a plain old 1 out of 2 tasks failed with no further context kind of message.

**Comment by vitalets** [comment]
I've checked on [playwright-bdd-example, nx branch](https://github.com/vitalets/playwright-bdd-example/tree/nx) - my vscode does not show with warning and it works with both shorthand and full syntax.
<img width="50%" src="https://github.com/vitalets/playwright-bdd/assets/1473072/659118fc-7595-48d1-9b42-f46286012f14">

Could you check out this branch and try this isolated example?

**Comment by barrymichaeldoyle** [comment]
Thanks, I’ll have a look later today and let you know :)

**Comment by barrymichaeldoyle** [comment]
Looks like it was all unrelated... My nx cache was just a mess. I fixed it by running `npx nx reset`. After that, my e2e tests started running correctly again.

**Comment by vitalets** [comment]
Cool, thanks for clarifying that!
