### ISSUE TITLE
Question: How can I integrate the results of BDD tests with reportportal.io?

### ISSUE THREAD

**Issue by anud22** [vitalets/playwright-bdd#88]

**Comment by vitalets** [comment]
You can use official [reportportal reporter for Playwright](https://github.com/reportportal/agent-js-playwright).

**Comment by anud22** [comment]
Thanks . It worked

**Comment by vitalets** [comment]
@anud22 great, thanks for the feedback!
fyi: after implementing #9 we will be able to use [reportportal agent-js-cucumber](https://github.com/reportportal/agent-js-cucumber) that provides more BDD-related report structure.
