### ISSUE TITLE
Support Cucumber reporters

### ISSUE THREAD

**Issue by vitalets** [vitalets/playwright-bdd#9]
Cucumber has several [built-in reporters](https://github.com/cucumber/cucumber-js/blob/main/docs/formatters.md) (also called formatters). It would be useful to output results of Playwright test runner to these reporters (especially [html-reporter](https://github.com/cucumber/html-formatter) or `messages` reporter).
There are different approaches:
1. Write [custom Playwright reporter ](https://playwright.dev/docs/test-reporters#custom-reporters) that will create Cucumber report
2. Use Playwright [json report](https://playwright.dev/docs/test-reporters#json-reporter) and convert it into Cucumber [messages](https://github.com/cucumber/cucumber-js/blob/main/docs/formatters.md#message), and then [convert to html](https://github.com/cucumber/cucumber-js/blob/main/src/formatter/html_formatter.ts)

Ideally, final usage should allow to use any Cucumber report:
```ts
import { defineConfig, devices } from '@playwright/test';
import { cucumberReporter } from 'playwright-bdd';

export default defineConfig({
  // ...
  reporter: cucumberReporter('json:cucumber-report.json'),
});
```

**Known problem - reporting Scenario Outline**. 
In Cucumber it is possible to have the same test title with different data. In Playwright each test must have unique title (it was also discussed in https://github.com/vitalets/playwright-bdd/issues/3#issuecomment-1496327063). Example of Cucumber html report for Scenario Outline:
<img src="https://user-images.githubusercontent.com/1473072/231519407-2808c129-63ef-4ef4-837e-e1c821df925e.png" width="30%">

I would appreciate more ideas on that from your reporting usage.

**Comment by evix1101** [comment]
Not elegant, and my needs are currently minimal.  I'm supporting tests against multiple environments at the project level via extending PlaywrightTestProject

`import { defineConfig, devices, PlaywrightTestProject } from '@playwright/test';

export interface ExtendedPlaywrightTestProject extends PlaywrightTestProject {
  testEnv?: string;
}

const config = defineConfig({ 
  testDir: './.features-gen',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: process.env.CI ? [ ['html'], ['junit', { outputFile: 'test-results/results.xml' }] ] : [ ['html'],['list']],
  use: {
    trace: 'retain-on-failure',
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'prod-chromium',
      use: {
        ...devices['Desktop Chrome'],
        baseURL: 'https://www.google.com/',
      },
      testEnv: 'prod',
    } as ExtendedPlaywrightTestProject, 
    {
      name: 'dev-chromium',
      use: {
        ...devices['Desktop Chrome'],
        baseURL: 'https://dev.google.com/',
      },
      testEnv: 'dev',
    } as ExtendedPlaywrightTestProject,
  ],
});

export default config;`

My thought was there might be a slick way to make this more dynamic to support the scenario outlines.

**Comment by Jag46** [comment]
import { defineConfig, devices } from '@playwright/test';
import { cucumberReporter } from 'playwright-bdd';

export default defineConfig({
  // ...
  reporter: cucumberReporter('json:cucumber-report.json'),
});


Hi @vitalets , when can we expect cucumberReporter function? It would be great if get this up running soon..Thank you..!

**Comment by vitalets** [comment]
@Jag46 can't give concrete date but will increase the priority for that.
Btw are you interested in particular json reporter or html?

**Comment by Jag46** [comment]
Thanks @vitalets , we are looking for a cucumber html report. That would great addition if you can help us with this blocker. Thanks

**Comment by harikishanl** [comment]
We are looking for a cucumber style html report as well, the current report is poorly formatted in playwright style and is not really making use of the BDD style reporting. If we can bring this enhancement soon, it will help our team use the html report without much hassle.

**Comment by vitalets** [comment]
> We are looking for a cucumber style html report as well, the current report is poorly formatted in playwright style and is not really making use of the BDD style reporting. If we can bring this enhancement soon, it will help our team use the html report without much hassle.

Ok, got it. Could you clarify what parts of cucumber html reporter are the most important for you? E.g. formatting Scenario Outlines or something else? As there are a lot of events in both playwright and cucumber test run flows.

**Comment by harikishanl** [comment]
```
> > We are looking for a cucumber style html report as well, the current report is poorly formatted in playwright style and is not really making use of the BDD style reporting. If we can bring this enhancement soon, it will help our team use the html report without much hassle.
> 
> Ok, got it. Could you clarify what parts of cucumber html reporter are the most important for you? E.g. formatting Scenario Outlines or something else? As there are a lot of events in both playwright and cucumber test run flows.


```
Hi @vitalets - It would be helpful if we can cover: 'Feature, Scenario Outline, Scenario, Given, When, Then & Examples' in the report

**Comment by vitalets** [comment]
Cucumber messages can be validated with https://github.com/cucumber/compatibility-kit

**Comment by dlitmano** [comment]
@vitalets please inform me if i can help you. I love this project and want to support it!

**Comment by vitalets** [comment]
Thank you @dlitmano ! Answered in #82

**Comment by magarwal19** [comment]
Looking forward for this feature!!

**Comment by vitalets** [comment]
> Looking forward for this feature!!

It's already 80% complete. Planning to include it in the nearest release.

**Comment by magarwal19** [comment]
Hi @vitalets 
do we have any planned ETA for this?
My team is working on integrating test management tool and it needs the results to be pushed using cucumber jsons

**Comment by vitalets** [comment]
> Hi @vitalets do we have any planned ETA for this? My team is working on integrating test management tool and it needs the results to be pushed using cucumber jsons

Hi @magarwal19 , I would say it's within 1-2 weeks. Cucumber json will be supported.

**Comment by magarwal19** [comment]
This is great news!!
thank you :)

**Comment by magarwal19** [comment]
Hi @vitalets 
do we have any update on this?

**Comment by magarwal19** [comment]
> Hi @magarwal19 Base part is ready, I need some time to write documentation. Would it be helpful for you, if I push it in a separate branch and you will pull `playwright-bdd` directly from github and check Cucumber reporters?

Hi @vitalets 
i have integrated it by installing the version of playwrigh-bdd npm package..
if we can get a beta release, then i can surely use that and check the cucumber reports

**Comment by vitalets** [comment]
I've published `playwright-bdd` **beta** with Cucumber reporters support.
Please follow the instructions below to check it with your projects.
I will appreciate any feedback on that!
@magarwal19 and everybody :)

1.Install `playwright-bdd@next`:
```
npm i -D playwright-bdd@next
```
2.Use `cucumberReporter` helper in the playwright config:
```ts
import { defineConfig } from '@playwright/test';
import { defineBddConfig, cucumberReporter } from 'playwright-bdd';

const testDir = defineBddConfig({
  importTestFrom: 'steps/fixtures.ts',
  paths: ['features'],
  require: ['steps/*.ts'],
});

export default defineConfig({
  testDir,
  reporter: [
    cucumberReporter('html', { outputFile: 'cucumber-report/report.html' }),
    cucumberReporter('json', { outputFile: 'cucumber-report/report.json' }),
    cucumberReporter('junit', { outputFile: 'cucumber-report/report.xml' }),
    cucumberReporter('message', { outputFile: 'cucumber-report/report.ndjson' }),
  ],
});
```
Here is [the diff example](https://github.com/vitalets/playwright-bdd-example/pull/10/files).

Example of html report:
<img width="50%" src="https://github.com/vitalets/playwright-bdd/assets/1473072/08c359d3-d237-4fb8-b341-2d1732802514">

Please note that minimal Playwright version is 1.34.

**Comment by magarwal19** [comment]
Hi @vitalets 
thank you for sharing this!
two things i observed:
1. It is adding keyword as After, even when i do not have after. Also After is not BDD keyword so it throws error when i import in test management tool
2. There is huge data added as part of key "embeddings", not sure for what part do we need this..


HTML reports look good :)

**Comment by vitalets** [comment]
@magarwal19 could you provide more details on both two points?

**Comment by magarwal19** [comment]
Hi @vitalets 
few updates here..
1. When we are creating junit reports, we need to add <testsuites> </testsuites>
and then add the current report under this..  Due to this, whenever we use any utility to parse our junit xml it is failing 
also not sure if we can add encoding at first step like
<?xml version="1.0" encoding="UTF-8"?>
currently we are getting it like <?xml version="1.0"?>

**Comment by magarwal19** [comment]
> @magarwal19 could you provide more details on both two points?

Hi @vitalets 
i analysed this and this seems to be dependent on Playwright execution. Since i have Screenshot and videos to be on in my playwright.config.js file, there gets an entry added for After in results.json

If we can remove this, it will make this result json more light and easy to read

[Automate_E2E_flow_for_CO_state_when_claim_in_Agency_as_eligible.cucumber.json](https://github.com/vitalets/playwright-bdd/files/14329745/Automate_E2E_flow_for_CO_state_when_claim_in_Agency_as_eligible.cucumber.json)

**Comment by vitalets** [comment]
> If we can remove this, it will make this result json more light and easy to read

Yes, Playwright's automatic screenshots are attached as an after step, b/c we need some entity to attach them.
So if you don't need screenshots and videos in the report, why you can't just disable them in playwright.config.js?

**Comment by magarwal19** [comment]
> Hi @vitalets few updates here..
> 
> 1. When we are creating junit reports, we need to add `<testsuites> </testsuites>`
>    and then add the current report under this..  Due to this, whenever we use any utility to parse our junit xml it is failing
>    also not sure if we can add encoding at first step like
>    `<?xml version="1.0" encoding="UTF-8"?>`
>    currently we are getting it like `<?xml version="1.0"?>`

Hi @vitalets 
have updated this comment.. some how it was not showing complete information earlier

**Comment by vitalets** [comment]
@magarwal19 

1. Will check on `<testsuites> </testsuites>` and `<?xml version="1.0" encoding="UTF-8"?>`. Btw, does your parser correctly handles Cucumber's original junit report? b/c I've ported this code from Cucumber without changes.
2. Got it. So the problem is large files due to embedded screenshots and videos, that are actually not needed? I will think about it. Also related to https://github.com/cucumber/html-formatter/issues/281

**Comment by vitalets** [comment]
@magarwal19 I've checked original Cucumber junit report, it returns the same structure as playwright-bdd:

* starts with `<?xml version="1.0"?>`, not `<?xml version="1.0" encoding="UTF-8"?>`
* does not contain `<testsuites> </testsuites>`

This is the full Cucumber report. Could you try to load it with your tool?
```xml
<?xml version="1.0"?>
<testsuite failures="4" skipped="0" name="cucumber-js" time="0.004758075" tests="4">
  <testcase classname="Playwright site" name="Check title" time="0.000913249">
    <failure type="Error" message="foo"><![CDATA[Error: foo
    at World.<anonymous> (/Users/vitalets/projects/bdd-playground/steps/cucumber-raw/index.ts:15:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)]]></failure>
    <system-out><![CDATA[Given I open url "https://playwright.dev".................................failed
When I click link "Get started"..........................................skipped
Then I see in title "Playwright".........................................skipped]]></system-out>
  </testcase>
  <testcase classname="Playwright site" name="Check title 2" time="0.000599414">
    <failure type="Error" message="foo"><![CDATA[Error: foo
    at World.<anonymous> (/Users/vitalets/projects/bdd-playground/steps/cucumber-raw/index.ts:15:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)]]></failure>
    <system-out><![CDATA[Given I open url "https://playwright.dev".................................failed
When I click link "Get started"..........................................skipped
Then I see in title "Playwright".........................................skipped]]></system-out>
  </testcase>
  <testcase classname="Playwright site" name="A Get started step is Playwright" time="0.002910996">
    <failure type="Error" message="foo"><![CDATA[Error: foo
    at World.<anonymous> (/Users/vitalets/projects/bdd-playground/steps/cucumber-raw/index.ts:15:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)]]></failure>
    <system-out><![CDATA[Given I open url "https://playwright.dev".................................failed
When I click link "Get started"..........................................skipped
Then I see in title "Playwright".........................................skipped]]></system-out>
  </testcase>
  <testcase classname="Playwright site" name="A Get started step is Play" time="0.00033441600000000003">
    <failure type="Error" message="foo"><![CDATA[Error: foo
    at World.<anonymous> (/Users/vitalets/projects/bdd-playground/steps/cucumber-raw/index.ts:15:10)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)]]></failure>
    <system-out><![CDATA[Given I open url "https://playwright.dev".................................failed
When I click link "Get started"..........................................skipped
Then I see in title "Play"...............................................skipped]]></system-out>
  </testcase>
</testsuite>
```

**Comment by magarwal19** [comment]
Hi @vitalets 
sure will check this.. thank you for sharing this!
i think teams integration plugin expects testsuites to be there..

**Comment by NikkTod** [comment]
Hi @vitalets, the html report looks great. 
One thing I wanted to ask if you can make it possible the traces of a failed test to be opened directly within the browser with a click. Currently I need to download the trace file and open it with command 'npx playwright show-trace ....'.

Within TeamCity when I am using the playwright html report I also have the option to just click it and it will open in a frame, so no need to download it. 


![image](https://github.com/vitalets/playwright-bdd/assets/94455079/154a6673-b277-4de4-9dc6-22a1ed436472)

![image](https://github.com/vitalets/playwright-bdd/assets/94455079/0195e55d-5c1f-4686-bba1-2acfa244e5ba)

this is sample from the html how it is opened in TeamCity iframe

![image](https://github.com/vitalets/playwright-bdd/assets/94455079/6d13e1c6-8523-485b-9665-2e3e7594ca52)

Maybe passing the URL of the traces could help 

![image](https://github.com/vitalets/playwright-bdd/assets/94455079/6a18bf1a-8a99-4f4c-99a5-b946e5b564cb)

**Comment by vitalets** [comment]
> One thing I wanted to ask if you can make it possible the traces of a failed test to be opened directly within the browser with a click. Currently I need to download the trace file and open it with command 'npx playwright show-trace ....'.

@NikkTod 
Interesting idea, should think about it. 
The main point here is that `trace.zip` should be uploaded to some public storage to be opened with `trace.playwright.dev`.

There are two questions:
1. Could you check, that artefacts from your teamcity server are available to `trace.playwright.dev`? I mean checking that url like this `https://trace.playwright.dev/?trace=https://you-teamcity-server/../trace.zip` shows trace?
2. if you use Playwright's original HTML reporter, do you still need to download trace.zip to open it? If yes, do you use `attachmentsBaseURL` option?

**Comment by vitalets** [comment]
**Finally, Cucumber reporters are released in playwright-bdd v6 🥳**
It was not-easy journey, but result is worth the efforts.
There were two main challenges during development:

1. **Attachments**. In Cucumber attachments are bound to the steps, but in Playwright attachments are bound to the whole test. Although there is no 100% way to [map attachments to steps](https://github.com/microsoft/playwright/issues/29323) in Playwright, for BDD steps it's possible, b/c they are always serial. I've changed the approach several times, because I wanted to support Playwright's [merge-reports](https://playwright.dev/docs/test-sharding#merge-reports-cli) mode, that provides a bit different data to the Reporter API. Now you can fully benefit from Playwright's sharding: run BDD tests on the multiple machines and get combined Cucumber report.

2. **Projects**. Cucumber reports do not support concept of projects that exists in Playwright. In Cucumber you get separate reports for Chrome, Firefox, etc, but in Playwright it's a single run and output. Playwright-bdd adopts Cucumber [messaging protocol](https://github.com/cucumber/messages) to handle several projects: basically it prepends project name to the feature uri making it unique. You can observe the result in the html reporter:
   ![image](https://github.com/vitalets/playwright-bdd/assets/1473072/507b0552-0ac1-48f8-a8af-a002d697b3dd)
   Having all browsers in a single run & report is also a good performance boost! 

Thank you all for your help to achieve this goal. Feel free to share your feedback in separate issues ❤️
