### ISSUE TITLE
Generated files contain different paths depending on whether `npx bddgen` is executed in Windows or Mac/Unix

### ISSUE THREAD

**Issue by andreasnovak** [vitalets/playwright-bdd#91]
When I execute command `npx bddgen` in Windows, the generated .spec.js files contain the following import:
`import { test } from "..\\fixtures\\fixtures.ts";`
 
But when I execute command `npx bddgen` on a Mac, the generated .spec.js files contain the following import:
`import { test } from "../fixtures/fixtures.ts";`
 
The Windows-style-backslash syntax does only work in Windows. The Unix-style-forwardslash syntax does work in both Unix and Windows.

Is there a configuration option that enables to generate Unix-style import paths when running `npx bddgen` in Windows?
Thank you!

**Comment by vitalets** [comment]
@andreasnovak good point.
Now there is no such option. But I think we can just always generate these paths in Unix-style without additional option.
Will add in the nearest release.

Btw, what scenario does it break? You generate spec files on Win and then run them on Unix?

**Comment by andreasnovak** [comment]
@vitalets Great, thank you very much!
Yes, my scenario is that I generate spec files on Win and run them on Unix.

**Comment by pjdaye** [comment]
In my case, it does cause an error on Windows:
"Error: ERR_INVALID_MODULE_SPECIFIER ..\..\..\features\project1\steps\fixtures.project1.ts is not a valid package name C:\projects\QA.Test\.features-gen\project1\create\create-new-item.project1.feature.spec.js"

**Comment by vitalets** [comment]
@pjdaye don't generated spec files contain double escaped backslash? e.g.:
```
C:\\projects\\QA.Test.features-gen\\project1\\create\\create-new-item.project1.feature.spec.js
```

The fix with forward slashes  is on the way to the nearest release.

**Comment by pjdaye** [comment]
It generates:
```
import { test } from "..\\..\\..\\features\\project1\\steps\\fixtures.project1.ts"
```
That may be slightly off - in typing this on my phone and from memory, but the basic gist is correct.

**Comment by vitalets** [comment]
Fixed in v6.
@andreasnovak @pjdaye pls re-check on your side and re-open if there are any issues

**Comment by pjdaye** [comment]
Working as expected. Thank you.

**Comment by andreasnovak** [comment]
Works as expected, generated import paths are now using Unix-style forward slashes. Thank you so much @vitalets ! <3 <3 <3
