### ISSUE TITLE
Question: In playwright report, the scenario is displayed twice

### ISSUE THREAD

**Issue by anud22** [vitalets/playwright-bdd#92]
In playwright report, the scenario is displayed twice.
```gherkin
 Scenario Outline: Metrics - Verify metrics Cost  Is displayed for region "<region>"
                        //steps

Examples:
  | region   |
  | USB   |
  | NCH   |
```

Is there a way we can just display the scenario with the data only in the playwright report ?

![image](https://github.com/vitalets/playwright-bdd/assets/37387148/8c674f62-c88e-44c0-821b-3c81ffdaa6f7)

**Comment by vitalets** [comment]
I agree, it's a bit verbose for BDD scenario outlines.
Currently we can't change the structure of Playwright report that shows full path for each test.
I'm going to provide adapter for Playwright html report that shows only BDD-related items.
Possible workarounds for now:
1. Reduce length of scenario title using [comment syntax](https://vitalets.github.io/playwright-bdd/#/writing-features?id=_2-use-special-comment-syntax):
```gherkin
Scenario Outline: Metrics
   //steps

# title-format: Metrics - Verify metrics Cost  Is displayed for region "<region>"
Examples:
  | region   |
  | USB   |
  | NCH   |
```

2. Try out [Cucumber html reporter](https://github.com/vitalets/playwright-bdd/issues/9#issuecomment-1945673635), it's still in beta but should work well. Feel free to report any issues.

**Comment by anud22** [comment]
Thanks @vitalets . It was very helpful
