### ISSUE TITLE
Bug: Not able to execute tests with latest version of playwright

### ISSUE THREAD

**Issue by magarwal19** [vitalets/playwright-bdd#96]
**Given**
I am using latest version of playwright v1.42.0

**When**
I execute tests

**Then**
It is not executing tests and giving below error:
Error: [Pirates] A hook returned a non-string, or nothing at all! This is a violation of intergalactic law!

**But I expect**
The tests should be executed successfully

**Note**
If i downgrade playwright version to v1.41.0, then it is working as expected
```
```
![Screenshot 2024-02-28 at 2 27 57 PM](https://github.com/vitalets/playwright-bdd/assets/47243226/6e3ceebf-ed6a-4b92-918d-724419a16d7f)

**Comment by jonyo** [comment]
I'm seeing the same problem.

At the time earlier yesterday there were no bug reports, so I tried to eliminate my own config as the cause... Plus I saw this part of the error:

> You might want to debug this.

And laughed, plus I took it as a challenge 😂 

It seems to be linked somehow to the `require` option when using `defineBddConfig`, at least that is what the stack trace points to, something with how the newer version tries to require stuff is broken maybe? I noticed also the trace sounded like it was in a "check" section that was trying to check if require works, so maybe there is some type of environment check that used to fail gracefully but is now causing things to exit.  Or I may be totally wrong.

 I tried switching over to `import` instead, went down a rabbit hole with module stuff, but never got anything that worked. So for now I'm pinning playwright to the older version and that works for me as well.

**Comment by vitalets** [comment]
Thanks for reporting! Taking this challenge as well :) Will try to fix it asap.

**Comment by magarwal19** [comment]
Hi @vitalets 
will it be fixed in beta version also? as I am using currently beta version for cucumber reports

**Comment by vitalets** [comment]
> Hi @vitalets will it be fixed in beta version also? as I am using currently beta version for cucumber reports

Yes, will do it.

**Comment by vitalets** [comment]
> Hi @vitalets can you please push this to beta version also? as I am using currently beta version for cucumber reports and there it is failing

Published as `6.0.0-1`. Please, re-install `playwright-bdd@next`.

**Comment by magarwal19** [comment]
It is working now
Thank you!!

**Comment by cchantep** [comment]
Hi @vitalets it seems that a similar issue happens with playwright 1.43, then with playwright-bdd it raises `ReferenceError: exports is not defined in ES module scope`

**Comment by vitalets** [comment]
> Hi @vitalets it seems that a similar issue happens with playwright 1.43, then with playwright-bdd it raises `ReferenceError: exports is not defined in ES module scope`

Hi @cchantep
Could you provide a reproducible demo using https://github.com/vitalets/playwright-bdd-example?

**Comment by cchantep** [comment]
Will try but any build with `"playwright-bdd": "6.1.1"` and the latest playwright will fails I guess (for us even a minimal spec fails).

**Comment by alescinskis** [comment]
I have no issues with 
```
"devDependencies": {
    "@playwright/test": "1.43.0",
    "playwright-bdd": "6.1.1",
    ...
```
nor locally, nor locally running in docker with `playwright:v1.43.0-jammy`, or in docker on gitlab.
